### ISSUE TITLE
Failures related to EE profile changes 

### ISSUE THREAD

**Issue by akurtakov** [eclipse-tycho/tycho#1003]
As can be seen at https://github.com/eclipse-platform/eclipse.platform.swt/runs/6796883085?check_suite_focus=true there is the following error during SWT build:
```
Error:  Failed to execute goal org.eclipse.tycho.extras:tycho-p2-extras-plugin:3.0.0-SNAPSHOT:compare-version-with-baselines (compare-attached-artifacts-with-release) on project org.eclipse.swt: Execution compare-attached-artifacts-with-release of goal org.eclipse.tycho.extras:tycho-p2-extras-plugin:3.0.0-SNAPSHOT:compare-version-with-baselines failed: Cannot set full specification for a custom profile more than once -> [Help 1]
```

**Comment by akurtakov** [comment]
And another one from equinox :
 [ERROR] Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:3.0.0-SNAPSHOT:compile (default-compile) on project org.eclipse.osgi: useJDK = BREE configured, but no toolchain of type 'jdk' with id 'JavaSE/compact1-1.8' found. See https://maven.apache.org/guides/mini/guide-using-toolchains.html -> [Help 1]

Can be seen at https://ci.eclipse.org/equinox/job/rt.equinox.framework/job/PR-63/1/console

**Comment by laeubi** [comment]
@akurtakov I'll take a look but wont be able to provide a fix as of today, for the equinox stuff please keep in mind that we don't want to support JDK < 9 anymore with the Tycho 3.0 so one option would to upgrade equinox to use at least BREE-11.

Currently it requires

> Require-Capability: osgi.ee; filter:="(| (&(osgi.ee=JavaSE)(version=1.8)) (&(osgi.ee=JavaSE/compact1)(version=1.8)) )"

**Comment by laeubi** [comment]
@akurtakov the SWT PR actually fails with:

> Failed to execute goal org.eclipse.tycho.extras:tycho-p2-extras-plugin:3.0.0-SNAPSHOT:compare-version-with-baselines (compare-attached-artifacts-with-release) on project org.eclipse.swt.tools.feature: Only qualifier changed for (org.eclipse.swt.tools.feature.feature.jar/3.108.500.v20220608-1533). Expected to have bigger x.y.z than what is available in baseline (3.108.500.v20220423-0849) -> [Help 1]

now, so was this probably already fixed?

**Comment by akurtakov** [comment]
Still waiting for the build. One failed with network issue https://ci.eclipse.org/tycho/job/tycho-github/job/master/420/console . Hopefully this one succeeds

**Comment by mickaelistria** [comment]
I think this is now fixed. Please reopen if I miss something.
