### ISSUE TITLE
Create an automatic version bump plugin

### ISSUE THREAD

**Issue by laeubi** [eclipse-tycho/tycho#1034]
Currently versions are bumped manually, but actually this is waste of developer time and manual work is prone to errors.

Once we successfully have extracted the resolution into the maven build phase (and thanks to the new tycho-ci-friendly-versions it should finally be possible to fully automate the process with different levels:

1. I could just let it bump as required
2. I could forbid automatic major bumps
3. I could forbid automatic minor bumps
4. ...

that way, for example the usual micro bumps while developing a new release could be avoided.

FYI @vogella

**Comment by mickaelistria** [comment]
I once imagined that the Maven bot could generate files to then suggest edits as GitHub comments.
I think it's better to suggest an edit than automatically apply it as it leaves opportunity for developer to decide differently.

**Comment by HannesWell** [comment]
Alternatively PDE's API-tools could be enhanced to inform about necessary service-version bumps as well:
https://github.com/eclipse-pde/eclipse.pde/discussions/165
