### ISSUE TITLE
Create a 'tycho-baseline' plugin

### ISSUE THREAD

**Issue by laeubi** [eclipse-tycho/tycho#115]
Getting semantic versioning right is not an easy task. BND allows for [comparing a baseline versus an actual version](https://bnd.bndtools.org/commands/baseline.html), it would be good if tycho could offer a mojo that helps in doing this in an automated way.

**Comment by mickaelistria** [comment]
Such mojo would better be provided by BND directly, and then maybe used by Tycho.
Tycho already has ways to include PDE API Tools analysis during build, which helps with doing semver in.some extent by reporting errors against baseline. This is for example enabled as part of Platform Build and allows to report wrong versioning of packages/bundles as errors during CI/Gerrit builds. So nothing more is needed from Platform POV.

**Comment by laeubi** [comment]
BND already offers a maven plugin for this but this would require to build my projects by BND and the goal would be to have this available in Tycho itself.

As you wrote PDE API Tools ' helps with doing semver in.some extent' but I really like full support without binding to eclipse specific tools.

> So nothing more is needed from Platform POV.

Tycho is more than platform needs :-)

**Comment by mickaelistria** [comment]
> Tycho is more than platform needs :-)

Sure, but just beware that in practice, most of its current contributors (at least @akurtakov and I) are only caring about Platform and won't provide much support for cases that are not part of Platform.

**Comment by laeubi** [comment]
> Sure, but just beware that in practice, most of its current contributors

Looking at the [monthly pulse](https://github.com/eclipse/tycho/pulse/monthly) I won't see this to pessimistic.

**Comment by HannesWell** [comment]
> Tycho already has ways to include PDE API Tools analysis during build, which helps with doing semver in.some extent by reporting errors against baseline. This is for example enabled as part of Platform Build and allows to report wrong versioning of packages/bundles as errors during CI/Gerrit builds.

As written on some mailing-list in the past (I think it was m2e), the setup currently used in Platform could be moved into a dedicated API analysis plug-in to simply its use in other projects (yes one could copy past it, but that's IMHO not very elegant).
This would also have the advantage, that the plug-in could be automatically enabled/disabled depending if a plug-in has the APIAnalysis builder listed in its `.project` build-commands. Which would avoid the `skipAPIAnalysis=true` properties in many test projects.
Indeed it would bind the plug-in to PDE's API-Analysis, which was not the original request, but in case this is first implemented by making the API-check profile of Eclipse Platform a Tycho plug-in this would be a handy feature. If this is implemented based on bnd-tools (and does not require PDE's API-tools to be used in the IDE) then it would be good to find other reliable ways to detected plug-ins that do not participate in the API-analysis. At the moment it has to be disabled for many test plug-ins using `skipAPIAnalysis=true`.

**Comment by HannesWell** [comment]
> > This would also have the advantage, that the plug-in could be automatically enabled/disabled depending if a plug-in has the APIAnalysis builder listed in its .project build-commands. Which would avoid the skipAPIAnalysis=true properties in many test projects.
> 
> You already have this for PDE Analysis if you copy the configuration from the platform parent. There is an Ant task that reads .project and skip API analysis when nature is not set.

This is the case for the [`api-generation` profile in the `eclipse-platform-parent`](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/98587de13683cfe1419b2a13786f98bf34bafddf/eclipse-platform-parent/pom.xml#L754) but I did not found anything like that for the [`api-check` profile](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/98587de13683cfe1419b2a13786f98bf34bafddf/eclipse-platform-parent/pom.xml#L829).

But I think it would be definitely be very hand to use that in the `api-check` profile too. If skipAPIAnalysis is explicitly set it should the analysis should be executed accordingly and by default the presence of the nature should be used.
This would make many poms trivial so that they could be removed.
