### ISSUE TITLE
Adjust the JUnit Classpath Container

### ISSUE THREAD

**Issue by laeubi** [eclipse-tycho/tycho#1165]
With commit https://github.com/eclipse-jdt/eclipse.jdt.ui/commit/dc19a3bca7474410f9bb86adbb8b262eaa30d77b JDT changed how the JUnit container behaves. We need to adjust this for Tycho, at best in a way that is backward compatible to older releases.

**Comment by akurtakov** [comment]
@laeubi Are you looking into this one?

**Comment by laeubi** [comment]
I played around a bit but not yet very satisfied, my current idea is to wait until the 2022-09 release when we upgrade or try to use an approach that search for packages instead of bundle names, but all has it pro and cons. The best might be to allows alternative names, but this is a bit hard with the current implementation.

So I'm not sure what is the best approach not breaking the usage of "old" update sites...

**Comment by laeubi** [comment]
@akurtakov @mickaelistria given that Tycho 3.x is a breaking-change and 2022-09 is already out, it might be ok to from now on only support the "new" names?

**Comment by mickaelistria** [comment]
There will most likely people who'll complain they're broken and interpret it as a regression, but that's not my case and I don't personally have any reason to support the older org.junit bundles from Orbit. So no objection to remove support.

**Comment by laeubi** [comment]
Alright, I started with adding a test that uses the JUnit5 container as a first step here:
https://github.com/eclipse-tycho/tycho/pull/1360
