### ISSUE TITLE
Tycho failed to resolve target definition file for zipped P2 repository if authentication is required

### ISSUE THREAD

**Issue by mfsoliveira** [eclipse-tycho/tycho#1190]
I am trying to use a zipped P2 repository, which was uploaded into a private NEXUS server inside a RAW repository.
I am getting the following error: 

` Failed to resolve target definition file:/D:/path/to/target/file.target: Failed to load p2 metadata repository from location jar:https://server.url/repository/raw-p2-private-repository/plugin_dependency/latest/plugin_dependency.zip!/: Unable to read repository at: jar:https://server.url/repository/raw-p2-private-repository/plugin_dependency/latest/plugin_dependency.zip!/site.xml. Too many failed login attempts.`

What we already tested (Thanks @cdietrich for additional tests) :
- Referring to  a local path like  <repository  location="jar:file//d:/path/to/plugin_dependency.zip!/"/> is working fine
- Referring to the same P2 repository in the same server but unzip is working fine
- Referring to a zipped P2 location without authentication is working fine.
- Referring to a zipped P2 location using a local server is failing with the same error message

I am using Java 11 and tycho version 2.7.4

The server is configured in settings.xml like that:

```
<servers>
  <server>
    <id>artifacts.server</id>
    <username>${env.NEXUS_USER}</username>
    <password>${env.NEXUS_PASS}</password>
  </server>
</servers>
```

I have the repository defined in my configuration POM and it uses the same id used in settings.xml:

```
<repositories>
  <repository>
    <id>artifacts.server</id>
    <url>https://server.url/repository/raw-p2-private-repository/plugin_dependency/latest</url>
    <layout>p2</layout>
  </repository>
</repositories>
```
Finally, the repository is defined in the target platform file:
```
<location includeAllPlatforms="false" includeConfigurePhase="false" includeMode="planner" includeSource="true" type="InstallableUnit">
  <unit id="com.required.unit.feature.group" version="1.2.3"/>	
  <repository id="artifacts.server" location="jar:https://server.url/repository/raw-p2-private-repository/plugin_dependency/latest/plugin_dependency.zip!/"/>
  </location>
</locations>
```

The above setup is based on [Tycho - Target_Platform](https://wiki.eclipse.org/Tycho/Target_Platform#Layout_p2) and [Tycho - Authentication and Mirrors](https://wiki.eclipse.org/Tycho/Target_Platform/Authentication_and_Mirrors) documentation. In special the following paragraph:

> When accessing a p2 repository, Tycho will check if there is a  <server> entry with matching ID and use these credentials. The ID of a p2 repository can be specified explicitly, e.g. when the repository is [added in the POM](https://wiki.eclipse.org/Tycho/Target_Platform#Layout_p2). If no ID is specified, e.g. in a target file, the repository URL (without trailing slash) is used as ID (since Tycho 0.16.0).

**Comment by cdietrich** [comment]
i did some remote debugging and saw the the RemoteRepositoryLoadingHelper.certainlyNoRemoteURL may return true as the uri will be opaque

```
public class Main2 {

	public static void main(String[] args) throws URISyntaxException {
		URI uri = new URI("jar:http://localhost:8008/org.eclipse.xtext.sdk.p2-repository-2.28.0-SNAPSHOT.zip!/");
		System.out.println(uri.isOpaque());

	}

}
```
so the code that sets up auth may not be called at all

**Comment by laeubi** [comment]
1. What version of Tycho are you using?
2. Please note that your current approach will download the file **multiple times**, P2 do not support zipped P2 sites nor does PDE
3. You may better consume it as a regular maven dependecy with `mvn:<groupid>:<artifactid>:<version>:zip` instead
