### ISSUE TITLE
tycho version 2.7.4 dependency conflict when calling a custom p2 eclipse touchpoint action for eclipse 2022-06

### ISSUE THREAD

**Issue by boglisGeorgiana** [eclipse-tycho/tycho#1250]
If we are dealing with custom p2 eclipse touchpoint action a dependency conflict will cause the build to fail. Using eclipse 2022-06.
See log bellow:

_The actions required to successfully install the requested software can not be installed. 
	Cannot complete the install because of a conflicting dependency.
		Software being installed: org.eclipse.equinox.p2.engine.actions.root.DefaultProfile 1.0.0.1659706953488
		Software currently installed: org.eclipse.tycho.p2 2.7.4 (tycho-bundles-external 2.7.4)
		Only one of the following can be installed at once: 
			Eclipse Jobs Mechanism 3.12.100.v20220120-1329 (org.eclipse.core.jobs 3.12.100.v20220120-1329)
			Eclipse Jobs Mechanism **3.13.0.v20220512-1935** (org.eclipse.core.jobs 3.13.0.v20220512-1935)_

tycho is specifying an older version than the one in eclipse:

		**Cannot satisfy dependency:
			From: org.eclipse.tycho.p2 2.7.4 (tycho-bundles-external 2.7.4)
			To: org.eclipse.equinox.p2.iu; org.eclipse.core.jobs [3.12.100.v20220120-1329,3.12.100.v20220120-1329]**

Without the call to the eclipse touchpoint action this dependency conflict does not occur.

**Comment by laeubi** [comment]
Please try out the current [tycho snapshot](https://github.com/eclipse/tycho/wiki#getting-tycho-snapshots) build if you need the latest eclipse version support.

**Comment by boglisGeorgiana** [comment]
This indeed fixes the issue, any estimation on when will tycho 3.0 be released ?
Thank you for your support!

**Comment by laeubi** [comment]
Thanks for confirmation, see https://github.com/eclipse-tycho/tycho/milestone/5
