### ISSUE TITLE
PGP signature incorrectly generated for feature if the ID & version also match a bundle

### ISSUE THREAD

**Issue by Kummallinen** [eclipse-tycho/tycho#1261]
When using tycho-gpg-plugin on a repository containing a feature with the same ID & version as a bundle, for example org.eclipse.rcp, a PGP signature for the bundle is attached to the feature. This results in the p2 repository being unusable as the signature check on the feature fails on installation.

Looks like the problematic code is here: https://github.com/eclipse-tycho/tycho/blob/d9efa1acf42c74371c6115786be5951cbdf7f151/tycho-gpg-plugin/src/main/java/org/eclipse/tycho/gpg/SignRepositoryArtifactsMojo.java#L123

I guess it should be checking the artifact type attribute rather than just checking for the presence of a matching file in "plugins"

I've only been able to test with Tycho 2.7.1 due to bugs preventing me from using later versions, but the code is unchanged so I assume it still happens.

**Comment by mickaelistria** [comment]
Thanks @Kummallinen !
