### ISSUE TITLE
Support JUnit 5.9

### ISSUE THREAD

**Issue by rimuln** [eclipse-tycho/tycho#1275]
Mockito 4.7 depends not on JUnit 5.9.
During prepare update of our TP I need add Junit 5.9 too and later test fall on unknow junit provider version.

**Comment by rimuln** [comment]
PR #1276 created.

ECA I have signed. but the rest about IP I didn't fully understood. It is new for me since last contribution to this project. (It was in Gerrit and was about add support for JUnit 5.7 If remember correctly.

**Comment by rimuln** [comment]
@mickaelistria could you probably port it to 2.7.x too? now it is for 3.0.0-SNAPSHOT

**Comment by akurtakov** [comment]
Looking at junit58 provider it was supposed to cover newer JUnit versions unless there is breaking change - https://github.com/eclipse-tycho/tycho/blob/98a248c5b7c0d0581404c616a526cab4d87b33dc/tycho-surefire/org.eclipse.tycho.surefire.junit58/bnd.bnd#L2 . 
So what exactly went wrong for you when using 5.9.0?

**Comment by rimuln** [comment]
Hi,

it is same as was in past with when I add new provider to thi plugin too (5.6 or 5.7):

```[ERROR] Failed to execute goal org.eclipse.tycho:tycho-surefire-plugin:2.7.4:test (default-test) on project de.ids.acos.et.shared.tests: Could not determine test framework provider. Available providers: [junit3, junit4, junit5, junit57withvintage, testng, junit58withvintage, junit47, junit56, junit55, junit57, junit58, junit54] -> [Help 1]```

Lumi(r)

**Comment by rimuln** [comment]
PR #1276 is merged to master

**Comment by mickaelistria** [comment]
There are some incompatibilities between JUnit 5.8 and 5.9 that make that current support for JUnit 5.9 in Tycho (basically using 5.8) is sometimes not working with JUnit Jupiter 5.9 as dependency.
