### ISSUE TITLE
Add regression test for memory leak caused by surefire

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-tycho/tycho#1322]
See https://github.com/eclipse-tycho/tycho/issues/879 and https://github.com/eclipse-tycho/tycho/pull/1321.

It makes no sense to update to surefire as long as it still has this bug not fixed https://issues.apache.org/jira/browse/SUREFIRE-2072

**Comment by mickaelistria** [comment]
Contribuitons welcome!

**Comment by laeubi** [comment]
As the leak is not introduced by Tycho and there is no real good way for Tycho to test this and no one has stepped up to do anything here, I'll close this for now.

I think if one wants to have a test, it would be much more suitable to do such testing in the surefire directly (one can contribute there with Github PRs as well).
