### ISSUE TITLE
Many classes are licensed under EPL v1.0

### ISSUE THREAD

**Issue by HannesWell** [eclipse-tycho/tycho#1324]
I just noticed that many classes in Tycho have a License-header that states that they are licensed under EPL v1.0. When I search my Tycho workspace for `https://www.eclipse.org/legal/epl-v10.html` I get 441 hits in `*.java` files.

Until know I assumed Tycho is entirely licensed under EPL-2 and now wonder if this is intentional and relevant and if it should be changed?

**Comment by mickaelistria** [comment]
I think those are leftovers and can/should be changed to newer license header. The copyright owner and date must remain, so a search pattern should only find/replace the next lines.
