### ISSUE TITLE
Resolve p2 dependencies against central to get the real GAV

### ISSUE THREAD

**Issue by laeubi** [eclipse-tycho/tycho#1345]
P2 dependencies are not very useful in plain maven and are often confusing. Because of this the update-consumer-pom should be enhanced to make this configurable and omit p2 dependencies by default.

FYI: @hd42

**Comment by hd42** [comment]
Even better would be to replace them with the corresponding Maven-Dependencies
<dependency>
      <groupId>p2.eclipse.plugin</groupId>
      <artifactId>org.eclipse.core.runtime</artifactId>
      <version>3.17.100.v20200203-0917</version>
      <type>eclipse-plugin</type>
      <scope>provided</scope>
      <optional>true</optional>
</dependency>

should become

<dependency>
      <groupId>org.eclipse.platform</groupId>
      <artifactId>org.eclipse.core.runtime</artifactId>
      <version>3.17.100</version>
</dependency>

There might not be an easy way to generalize this for any bundle in the wild, but for official Eclipse bundles, this should be feasible, as they are available on Maven Central and a search for https://search.maven.org/search?q=a:org.eclipse.core.runtime%20AND%20v:3.17.100 (the version number without the .vYYYYMMDD-hhmm part) reveals exactly one artifact for current Eclipse versions.

**Comment by laeubi** [comment]
Yes, but Tycho can't "search central" and guess what the right artifact is :-)

All artifacts that promote "correct" metadata are already replaced, platform sadly don't do this.

**Comment by laeubi** [comment]
@mickaelistria are your enhancements regarding fixed group/artifact id already included in the 2022-09 release? If yes can you give an example of such an item?

**Comment by mickaelistria** [comment]
> are your enhancements regarding fixed group/artifact id already included in the 2022-09 release? 

No, they're not, and this work is far from being complete anyway.

> Yes, but Tycho can't "search central" and guess what the right artifact is :-)

Why not? seach.maven.org allows to [search artifacts by checksum](https://central.sonatype.org/search/rest-api-guide/). It would be nice to use it.

**Comment by laeubi** [comment]
> Why not? seach.maven.org allows to [search artifacts by checksum](https://central.sonatype.org/search/rest-api-guide/). It would be nice to use it.

okay if there is no concern I can add such an option, but this then would only work for central not sure if we maybe can have similar for nexus or other ...

**Comment by laeubi** [comment]
The fix for this issue was gently sponsored by [Faktor Zehn GmbH](https://www.faktorzehn.com).
