### ISSUE TITLE
Pomless Build extension can't be found using 3.0.0-SNAPSHOT

### ISSUE THREAD

**Issue by Phillipus** [eclipse-tycho/tycho#1393]
I have in main pom:

```xml
<properties>
     <tycho-version>3.0.0-SNAPSHOT</tycho-version>
     <maven.compiler.source>11</maven.compiler.source>
     <maven.compiler.target>11</maven.compiler.target>
</properties>

<pluginRepositories>
    <pluginRepository>
        <id>tycho-snapshots</id>
        <url>https://repo.eclipse.org/content/repositories/tycho-snapshots/</url>
    </pluginRepository>
</pluginRepositories>
```

And file `.mvn/extensions.xml`:

```xml
<extensions>
  <extension>
    <groupId>org.eclipse.tycho</groupId>
    <artifactId>tycho-build</artifactId>
    <version>3.0.0-SNAPSHOT</version>
  </extension>
</extensions>
```

Output:

[WARNING] The POM for org.eclipse.tycho:tycho-build:jar:3.0.0-SNAPSHOT is missing, no dependency information available
[ERROR] Error executing Maven.
[ERROR] Extension org.eclipse.tycho:tycho-build:3.0.0-SNAPSHOT or one of its dependencies could not be resolved: Could not find artifact org.eclipse.tycho:tycho-build:jar:3.0.0-SNAPSHOT
[ERROR] Caused by: Could not find artifact org.eclipse.tycho:tycho-build:jar:3.0.0-SNAPSHOT

**Comment by mickaelistria** [comment]
The pom is here: https://repo.eclipse.org/content/repositories/tycho-snapshots/org/eclipse/tycho/tycho-build/3.0.0-SNAPSHOT/tycho-build-3.0.0-20220921.114050-299.pom . You might have been unluncky and should maybe just try again (with the `-U` flag to increase luck)

**Comment by joeshannon** [comment]
Isn't there an issue that the `<pluginRepositories>` in the build pom doesn't work with Maven extensions so you have to add the repo to `~/.m2/settings.xml` (or install the extension locally first)? Looks to be described [here](https://github.com/eclipse-tycho/tycho/wiki#configure-snapshots-repository-globally).

**Comment by Phillipus** [comment]
> Isn't there an issue that the `<pluginRepositories>` in the build pom doesn't work with Maven extensions so you have to add the repo to `~/.m2/settings.xml` (or install the extension locally first)? Looks to be described [here](https://github.com/eclipse-tycho/tycho/wiki#configure-snapshots-repository-globally).

Yes, `~/.m2/settings.xml` works.

> or install the extension locally first

How would one do that?

**Comment by joeshannon** [comment]
> How would one do that?

I've only done this before when working on Tycho directly, using `mvn clean install` from the git repository but I imagine there is some command/plugin that can install an artifact locally from a remote repository.

**Comment by laeubi** [comment]
@Phillipus 3.0.0 is out and you seem to have a working soloution, so I think we can close.
