### ISSUE TITLE
Tycho pomless does not take custom pom-names into account

### ISSUE THREAD

**Issue by pbalint** [eclipse-tycho/tycho#1415]
When custom pom names are used (e.g. mvn -f pom-ts.xml package), tycho-pomless still searches for pom.xml-s, failing to find the proper one...

https://github.com/eclipse-tycho/tycho/blob/44b540436305adb9fc198a9d6dad12b91a6d301c/tycho-extras/tycho-pomless/src/main/java/org/eclipse/tycho/pomless/AbstractTychoMapping.java#L79

**Comment by laeubi** [comment]
@pbalint I think you need to give a more complete example and what you would expect here. "Custom pom names" are nothing that is really supported concept as there is no convention or name to find out the custom name (and thus you need to explicitly name it on commandline).

**Comment by pbalint** [comment]
The issue is that despite any name you specify on the command line, tycho-pomless will be still looking for pom.xml...
The idea for specifying custom pom-names is that instead pom.xml you have something-else.xml everywhere, so you won't have any pom.xml...

**Comment by laeubi** [comment]
> The idea for specifying custom pom-names is that instead pom.xml you have something-else.xml everywhere, so you won't have any pom.xml...

As said, this is simply not true, specifying **a file-name (!)** on the commandline, simply tells maven to look there instead of the default (look in the current working directory) for the initial pom file. It does not has (or must have) any influence on any other thing (e.g. parent pom references).

**Comment by pbalint** [comment]
I was hoping that there would be a possibility to have multiple sets of poms usable to build a tycho pomless project: 
Attached example project structure below:
[test.zip](https://github.com/eclipse-tycho/tycho/files/9640157/test.zip)
In the supplied example, if you issue mvn validate, you get:
```
---> Echoing from: Parent pom.xml
---> Echoing from: Module pom.xml
```
While, if you issue mvn -f pom-ts.xml validate, you get:
```
---> Echoing from: Parent pom-ts.xml
---> Echoing from: Module pom-ts.xml
```
This is done in 2 steps:
-In the custom pom-ts.xml, the module reference is made directly to the custom module pom-ts.xml
-Execution started with mvn -f pom-ts.xml in the parent.

So this seems to be possible with just maven, but not, when tycho-pomless is involved, as far as I can tell...
(If needed, I can provide an example that also has tycho-pomless added, but would rather not have to do it on the weekend...)

**Comment by laeubi** [comment]
> I was hoping that there would be a possibility to have multiple sets of poms usable to build a tycho pomless project:

Having multiple "poms" obviously defeats the purpose of having a "pomless" build :-)
So the first step would probably to describe why exactly this is required, and probably pomless is not the right choice for you the anyways.

Just note, the "pom.xml" in pomless, is only used to **disable** pomless, that mean for one or more module you just want to configure things explicitly. Bend this to having even multiple pom files (what will duplicate and complicate configuration a lot) seems a bit strange. still you can create an completely empty file named "pom.xml" for such purpose.

> Attached example project structure below:

As you can see in your example, the parameter .`-f` is not really used, you simply encode "everything" again in the pom.xml so maven itself does not support the described use-case either...

> The motivation for this is trying to add a temporary build system to a project that already has one, but is not perfect...

Maybe it is more valuable to improve that "not perfect build system" than trying to build one in parallel (that could easily get out of sync)?

**Comment by pbalint** [comment]
> Having multiple "poms" obviously defeats the purpose of having a "pomless" build :-)
When you have a fairly complicated project structure, the pomless part is really only about not having to write poms for your osgi bundles; You still have to point maven TO those bundles, nested x folders deep...

> Maybe it is more valuable to improve that "not perfect build system" than trying to build one in parallel (that could easily get out of sync)?
On paper, yes, but that existing build system has been in development for >1.5 years, while still inheriting some of the idiosyncrasies of the old, ant based build system, while a quick-and-dirty one could be conjured up in about a week...

I can live with "tycho-pomless is not designed for your usecase", I just wanted an official opinion...

**Comment by laeubi** [comment]
> When you have a fairly **complicated** project structure,

I think the highlighted part it the actual the problem here, I have pomless build with hundreds of bundles, spanning multiple git-repositories, nested in different structures, still I do not need any pom (just because I follow the recommended project layouts), so this is still possible.

> I can live with "tycho-pomless is not designed for your usecase", I just wanted an official opinion...

The use-case seems very rare and rather complicated with lots of customization that diverge from the usual layouts, so I think one can say yes it is not designed for such setups (and probably can not work well in such cases).

You might want to take a look at https://github.com/eclipse-tycho/tycho/wiki/Tycho-Pomless to check if some of the low-level customization still help you with that.
