### ISSUE TITLE
Support junit-jupiter-api bundles

### ISSUE THREAD

**Issue by sthdev** [eclipse-tycho/tycho#1420]
I have switched to a Eclipse 2022-09 target, which provides JUnit bundles from Orbit (JUnit 5.8) and Maven Central (JUnit 5.9). See https://github.com/eclipse-platform/eclipse.platform.common/blob/master/bundles/org.eclipse.platform.doc.isv/porting/4.25/incompatibilities.html for more information. 

Now, if a test fragment imports JUnit packages as package imports, the classpath validation fails with this message 

`Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:2.7.5:validate-classpath`
`Unresolved requirement: Import-Package: org.junit.jupiter.engine.execution`

If the bundles containing those packages are declared explicitly as plugin dependencies, it works only for the now obsolete `org.junit.jupiter.*` bundles from Orbit. If dependencies to `junit-jupiter-*` bundles from Maven Central are declared, the test execution fails because no tests can be found.

**Comment by laeubi** [comment]
Please try out the current [tycho snapshot](https://github.com/eclipse/tycho/wiki#getting-tycho-snapshots) build which include the latest platform changes. Neverless it is a bit unclear what/how you use Tycho here and what work/don't work, because the error indicates that your target platfrom do not contain a suitable JUnit provider (of whatever bundle name).

If you still think there is a problem provide an [integration-test](https://github.com/eclipse/tycho/wiki#providing-an-integration-test) to demonstrate the issue would help to analyze/fix this.

**Comment by sthdev** [comment]
Extracting a proper integration test takes some time. But I suppose, the problem is related to this comment in https://github.com/eclipse-tycho/tycho/blob/3a61f9e256c987128631fcffc5f085cfa49edee2/tycho-bundles/tycho-bundles-target/tycho-bundles-target.target

```
<location includeAllPlatforms="false" includeConfigurePhase="false" includeMode="slicer" includeSource="true" type="InstallableUnit">
			<!-- Currently still using Orbit variants instead of upstream one in Platform
				because Tycho 2.7.x which is used to build current Tycho 3.0.0-SNAPSHOT
				doesn't support new/official JUnit bundles -->
			<unit id="org.junit.jupiter.api" version="5.8.1.v20211018-1956"/>
			<repository location="https://download.eclipse.org/tools/orbit/downloads/drops/R20220531185310/repository"/>
		</location>
```

**Comment by mickaelistria** [comment]
@sthdev The change you mention is not related. This file has no impact on how surefire behaves.
Please try the 3.0.0-SNAPSHOT which has received more improvements about JUnit support.

**Comment by sthdev** [comment]
For some reason, it works now with tycho 3.1.0-SNAPSHOT. Maybe due to caching? Anyway, I am closing this issue.
