### ISSUE TITLE
Tycho Setup seems outdated

### ISSUE THREAD

**Issue by laeubi** [eclipse-tycho/tycho#1437]
I tried to use the Tycho setup, but Oomph refuses to install, some settings seem outdated. @HannesWell can you take a look? do we need to updates the setup e.g. for new m2e 2.x? The setupa also mention "gerrit" on some places what seems wrong.

**Comment by HannesWell** [comment]
There are two connectors that are incompatible with M2E-2.0 in the setup. I removed them and their p2-repos (and one orphan) via #1439.
I also searched for "Gerrit" but did not find that string in the setup?
