### ISSUE TITLE
eclipse-plugin JUnit test execution is tied to .classpath

### ISSUE THREAD

**Issue by lppedd** [eclipse-tycho/tycho#1458]
As described [here](https://github.com/eclipse-tycho/tycho/blob/master/RELEASE_NOTES.md#execute-unit-tests-with-eclipse-plugin-packaging), I was trying to execute JUnit tests as part of an `eclipse-plugin` packaging.  
I found myself having to explicitly add a classpath entry in the .classpath file, which is specific to the Eclipse IDE.

![image](https://user-images.githubusercontent.com/19871649/193639509-767a636e-d587-4594-909e-e5cb159a48ab.png)

I was wrongly supposing the test classes discovery would have been based on the `testSourceDirectory` configuration value.
Is there a roadmap item to make this IDE-agnostic?

**Comment by laeubi** [comment]
> which is specific to the Eclipse IDE.

Tycho is specially made for building Eclipse/PDE artifacts :-)

> I was wrongly supposing the test classes discovery would have been based on the `testSourceDirectory` configuration value

The current discovery might be enhanced in this regard, but actually it is *not* the JUnit execution, it is the test-source compilation that currently uses the classpath to detect the "test sources folder"....

**Comment by lppedd** [comment]
> Tycho is specially made for building Eclipse/PDE artifacts :-)

That's a fair point.

> currently uses the classpath to detect the "test sources folder"

Oh yes I noticed this after posting the issue. Basically Surefire was telling me "No tests to run" because nothing under test was getting compiled.

I mean as of now I can just fire up Eclipse and check that my .classpath file is ok, but in the future I would like to have only a single IDE/editor, not necessarily Eclipse.

**Comment by laeubi** [comment]
I think there is nothing wrong in enhance the test-compile mojo to be more "maven like" and also consider the `testSourceDirectory` **but** this should only be used if no classpath file is found because eclipse projects often don't follow the maven convention.

**Comment by lppedd** [comment]
> should only be used if no classpath file

For this specific case, what about giving priority to `classpathentry`(s), and if none is found going back to the Maven way? Could this work?

For example in my team most devs use Eclipse, I use IntelliJ, someone else edits using VSCode.

**Comment by lppedd** [comment]
As an alternative, I would be perfectly okay with your option, if I could find an XSD/DTD file to have completion inside `.classpath`.
Eclipse doesn't seem to offer one tho.

**Comment by laeubi** [comment]
It depends a bit, if you would fallback, then some code might only be compiled while the maven build while in the IDE it won't be compiled at all.

We generally try to avoid such inconsistency between IDE + Build, but actually nothing prevents you from define the source+output folders in eclipse to the maven defaults, this usually looks like this:

```
<classpath>
	<classpathentry kind="src" output="target/classes" path="src/main/java">
		<attributes>
			<attribute name="optional" value="true"/>
			<attribute name="maven.pomderived" value="true"/>
		</attributes>
	</classpathentry>
	<classpathentry excluding="**" kind="src" output="target/classes" path="src/main/resources">
		<attributes>
			<attribute name="maven.pomderived" value="true"/>
		</attributes>
	</classpathentry>
	<classpathentry kind="src" output="target/test-classes" path="src/test/java">
		<attributes>
			<attribute name="test" value="true"/>
			<attribute name="optional" value="true"/>
			<attribute name="maven.pomderived" value="true"/>
		</attributes>
	</classpathentry>
	<classpathentry excluding="**" kind="src" output="target/test-classes" path="src/test/resources">
		<attributes>
			<attribute name="test" value="true"/>
			<attribute name="maven.pomderived" value="true"/>
		</attributes>
	</classpathentry>
	<classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-17">
		<attributes>
			<attribute name="module" value="true"/>
			<attribute name="maven.pomderived" value="true"/>
		</attributes>
	</classpathentry>
	<classpathentry kind="output" path="target/classes"/>
</classpath>
```

> , if I could find an XSD/DTD file to have completion inside `.classpath`

I'm not aware of any but you can ask here: https://github.com/eclipse-jdt/eclipse.jdt.core

**Comment by jgsuess** [comment]
I have a similar issue and would like advice on this.  We are [Developing Ant tasks and types within Eclipse](https://help.eclipse.org/latest/topic/org.eclipse.platform.doc.isv/guide/ant_developing.htm?cp=2_0_18_3).

The dynamic class loading places some special requirements. It requires that

> the project contributing the Ant tasks or types must be configured to exclude the output folders containing the Ant tasks and types. 

and

> The JAR file containing the Ant tasks and types and specified in the org.eclipse.ant.core.extraClasspathEntries extension, must be built manually, or using an external tool builder.

When I write a JUnit test within the plugin environment, I can execute it in Eclipse. The classes in the ant environment are found. When I run this same test as part of Tycho, the test fails. This is despite the fact that tycho has access to the .classpath file which specifies the execution.

This leaves me with the following choices:

1. Live with untested code. => Flat no
2. Create OSGi plugin test. => Not nice, as framework is unnecessary and slow. I do not need OSGi
3. Build the whole thing *outside* tycho and import Maven artifacts. => Not nice, as it requires two build systems just to create a unit test.

Is there a way that I can add a **local** classpath fragment to the eclipse plugin JUnit test classpath that contains classes that are **not be included in the plugin**?

**Comment by jgsuess** [comment]
I guess what I am asking at the core is 

* how does `surefire.test.class.path` get composed and 
* how can I influence it in Tycho using just
   - `build.properties`
   - `.classpath`

**Comment by jgsuess** [comment]
It seems like there is no way to add anything as this is hardwired to the [project output directory](https://github.com/eclipse-tycho/tycho/blob/master/tycho-surefire/tycho-surefire-plugin/src/main/java/org/eclipse/tycho/surefire/TestPluginMojo.java#L50). :(

**Comment by jgsuess** [comment]
Configuring the extra dependency explicitly like the below works, but prompts the warning at the bottom:

```xml
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<dependencies>
					<dependency>
						<groupId>org.junit.jupiter</groupId>
						<artifactId>junit-jupiter-engine</artifactId>
						<version>5.9.0</version>
					</dependency>
				</dependencies>
				<configuration>
					<additionalClasspathElements>
						<additionalClasspathElement>plugins/org.eclipse.epsilon.emc.ant/target/lib/com.codebots.botlearn.ant.jar-classes</additionalClasspathElement>
					</additionalClasspathElements>
				</configuration>
			</plugin>
```

```bash
# Created at 2022-10-04T12:57:38.253
Boot Manifest-JAR contains absolute paths in classpath 'plugins/org.eclipse.epsilon.emc.ant/target/lib/com.codebots.botlearn.ant.jar-classes'
Hint: <argLine>-Djdk.net.URLClassPath.disableClassPathURLCheck=true</argLine>
'other' is different type of Path

```

**Comment by laeubi** [comment]
I'm not sure if this is related, and even not sure if I fully understand what you want to archive, but PDE builds a lot of extra ant stuff and you probably like to take a look how it is done there:
https://github.com/eclipse-pde/eclipse.pde/blob/master/ui/org.eclipse.pde.core/build.properties

**Comment by jgsuess** [comment]
I am very aware of this. I will make a documented example and remove the brain dump above. It is too disorganized. I am sorry.

**Comment by laeubi** [comment]
Thanks, usage-questions are also better placed here: https://github.com/eclipse-tycho/tycho/discussions

**Comment by laeubi** [comment]
I have now added documentation and an example how to use this with standard maven layout here:
- https://tycho.eclipseprojects.io/doc/master/TestingBundles.html#maven-surefire-plugin
- https://github.com/eclipse-tycho/tycho/tree/master/demo/testing/surefire/with-maven-layout
