### ISSUE TITLE
Direct integration with m2eclipse

### ISSUE THREAD

**Issue by laeubi** [eclipse-tycho/tycho#146]
m2e allows mojos to participate in the incremental build. It would be good to have tycho mojos to support this.

See https://www.eclipse.org/m2e/documentation/m2e-making-maven-plugins-compat.html

**Comment by vogella** [comment]
Will be very nice to not have errors in Eclipse. 

I avoided installing m2e over the years to avoid getting such errors but with the amazing m2e-pde integration from you I see these annoying errors now again.

**Comment by laeubi** [comment]
@mickaelistria I'm trying to getting started here with a simple "hello world" example but must confess the documentation is a bit vague to me. Taking a look at the example I get the feeling that `BuildContext` is not the right way to go here (or I can't find a valuable example) as it seems only suitable if I'd like to generate some kind of data due to a change in a resource file.

So I assume that for complex setups like tycho a ProjectConfigurator seems more suitable but I don't understand how I can do this from a maven-plugin as it requires plugin.xml. Is this actually supported?

Or is it supposed that way that one only configures the `<id>` of the configurator in the maven plugin and the user needs to install it manual in his eclipse? I'm attaching a code snippet for clarity:

```
<lifecycleMappingMetadata>
   <pluginExecutions>
     <pluginExecution>
       <pluginExecutionFilter>
         <groupId>org.eclipse.tycho</groupId>
         <artifactId>target-platform-configuration</artifactId>
         <versionRange>[2.0.0,)</versionRange>
          <goals>
            <goal>target-platform-configuration</goal>
          </goals>
       </pluginExecutionFilter>
       <action>
         <configurator>
           <id>my.configurator.id</id>
         </configurator>
       </action>
     </pluginExecution>
   </pluginExecutions>
</lifecycleMappingMetadata>
```

If yes, do you think it would be suitable to enhance the XML in a way one can reference the configurator in the form of a maven coordinate and m2e loads necessary stuff from there?
```
<configurator>
   <groupId>org.eclipse.tycho</groupId>
   <artifactId>my.configurator.id</artifactId>
   <version>1.0.0</version>
   <class>org.eclipse.tycho.m2e.TargetConfigurator
 </configurator>
```

or is something like that already possible?

**Comment by mickaelistria** [comment]
Most Tycho mojos shouldn't be run in the Eclipse IDE because PDE has the responsibility of performing those steps.
So one possibility is to assume that PDE is always installed in the IDE when doing Plugin Development, and then just configure the `META-INF/m2e/lifecycle-mapping-metadata.xml` to ignore the various steps at the moment.

**Comment by laeubi** [comment]
> Most Tycho mojos shouldn't be run in the Eclipse IDE because PDE has the responsibility of performing those steps.

While this is often true, I think more towards *not* requiring PDE when developing tycho-build bundle (as it works if one use felix-bundle plugin or bnd-bundle plugin as well without PDE).

The most visible impact to the usual maven-developer is, that if you import a project into eclipse via "import existing maven project" that it fails as PDE does not understand the pom-declared target platform and one needs to set the active target according to the pom (if even possible, e.g. repository declared items or multipel targets are not supported by PDE).

So my first attempt to provide better tycho<->m2e integration would be to actually support making the tycho-target platform available to Eclipse (whatever will be choose as the best approach here), but this will require me to participate not in the *build* but on the configurator part of m2e. For sure I can create a seperate "tycho-connector" that people need to install, but think having other ways would improve user-experience (in m2e) much more, e.g even just a hint in the `lifecycleMappingMetadata` to an updatesite would help so people can get automatic choice to install. But that might be more a topic for m2e itself (if there is no such option already available).

**Comment by mickaelistria** [comment]
You won't be able to achieve configuration of the IDE from the Maven API, you can only edit resources and other "common" info allowed by BuildContext; this would indeed have to be a specific m2e/tycho connector.

**Comment by laeubi** [comment]
> You won't be able to achieve configuration of the IDE from the Maven API

Yeah but the m2e lifecycle-mapping-metadata.xml allows both(!) things thats why I wrote I don't need a "simple" `execution` mapping but a `configurator` mapping. The point is, that currently a configurator has just an `<id>` so I wonder if it could have either (or we should add support for thin in m2e):

1. support an additional update-site to install the missing connector for that ID from, 
 .... or even better ...
2. support specify a maven GAV that could be downloaded and contains the code.

**Comment by laeubi** [comment]
I think we have a similar case here https://github.com/eclipse-m2e/m2e-core/issues/147 if the AspectJ-Maven Plugin would be ablte to embeeed (or reference) some (additional) code that supplies a m2e project configurator it would be much more sensible for the user than searching for and installing additional plugins.

**Comment by mickaelistria** [comment]
How do you expect the target-platform mojo would configure the IDE without involving PDE?

> The most visible impact to the usual maven-developer is, that if you import a project into eclipse via "import existing maven project" that it fails as PDE does not understand the pom-declared target platform and one needs to set the active target according to the pom (if even possible, e.g. repository declared items or multipel targets are not supported by PDE).

I don't think it's an issue in Tycho but in m2e. m2e should at import add the Maven Depdencies container (unless a .project already exists), and resolving the "Maven Dependencies" should list the dependencies coming from Tycho. No specific mojo mapping would be necessary.
This is probably an instance of https://github.com/eclipse-m2e/m2e-core/issues/118

**Comment by laeubi** [comment]
> I don't think it's an issue in Tycho but in m2e. m2e should at import add the Maven Depdencies container (unless a .project already exists), and resolving the "Maven Dependencies" should list the dependencies coming from Tycho.

but that's the point where I think we are having a circle, as this would require to execute tycho-plugin (what is not happening atm) doesn't it? The extension think should be more related to the .mvn folder?

I'm also not sure if this really works because tycho only adds reactor project dependencies as far as I can see and the classpath is only computed/taken into account in the compile-mojo but never published to the model (but maybe I'm getting just something wrong here).

> How do you expect the target-platform mojo would configure the IDE without involving PDE?

it could simply add corresponding classpath entries, or even a custom classpathcontainer.

**Comment by mickaelistria** [comment]
> as this would require to execute tycho-plugin (what is not happening atm) doesn't it? 

Yes, it's what about support for Maven extensions in m2e is about: resolving the model taking extensions into account.

> I'm also not sure if this really works because tycho only adds reactor project dependencies as far as I can see and the classpath is only computed/taken into account in the compile-mojo but never published to the model (but maybe I'm getting just something wrong here).

Try `mvn dependency:list`, dependency from target-platform are resolved early.

> it could simply add corresponding classpath entries, or even a custom classpathcontainer.

That's not a Tycho-specific problem, it should be m2e-core taking the resolved deps into accout in the classpath container, executing Tycho lifecycle extension to get the resolved deps.

**Comment by laeubi** [comment]
Then eclipse-m2e/m2e-core#118 should be resolved first I think to see what actually is missing on the tycho side then...

**Comment by laeubi** [comment]
There is an unmaintained project for tycho: https://github.com/tesla/m2eclipse-tycho the new errors seem to originate from some recent changes that are not covered by this plugin.
I think tycho should be in charge of such a plugin thus I wonder if we could integrate this into tycho (it seems to be EPL 1.0) I'm currently investigate ways to better support such connector in a more "maven-way" and this would be a good use-case.

@mickaelistria what do you think? Could you or @akurtakov help here with the legal stuff?

**Comment by mickaelistria** [comment]
Instead of bringing new code here, aren't there some related things we should fix instead to get a similar result?
Eg add some lifecycle-mapping info to Tycho mojos and make m2e able to support Maven extensions?

**Comment by laeubi** [comment]
I'm currently try to sort some things out in that area but it has shown that project configurators can often give a much better user experience. So I'd like to check what options we have without "reinvent the wheel".
Beside that this code seems to ship by default with eclipse (or at laest: could be installed by default) and its really annoying that it is not maintained anymore.
Currently this will for example interfere with tycho provided mappings (if we would provide one).

**Comment by mickaelistria** [comment]
> I'm currently try to sort some things out in that area but it has shown that project configurators can often give a much better user experience

OK

> So I'd like to check what options we have without "reinvent the wheel".

It's not reinventing the wheel; it's supporting things as natively as possible with less need for specific code to execute and maintain while increasing the functional value of upstream content ;)

Anyway, I trust your judgement here, although I don't plan to get involved in it (if time permits me to work on this story one day, I'll focus on https://github.com/eclipse-m2e/m2e-core/issues/118 which will make m2e work much better for a wide variety of cases, including this one), but I think this would have to be a different Git repo for the tycho project.

**Comment by mickaelistria** [comment]
actually, wouldn't it be better to just put this project configurator in m2e instead of Tycho? That would make things much simpler, and now m2e has a PDE integration, having some Tycho support in it wouldn't seem bad.

**Comment by laeubi** [comment]
> actually, wouldn't it be better to just put this project configurator in m2e instead of Tycho?

I think this would also be a good place, the only thing if we host that at tycho we can bind it to the tycho reslease-cycle whereas if m2e adds support we would need a new m2e release to support new tycho features (if any) but I think the projects are already a bit dependent on some features so I won't mind to place it there.

**Comment by laeubi** [comment]
This is related:
- https://github.com/eclipse-m2e/m2e-core/issues/605

**Comment by laeubi** [comment]
Basic work has been done and further work is better done in m2e directly
