### ISSUE TITLE
Get rid of transitive version ranges

### ISSUE THREAD

**Issue by kwin** [eclipse-tycho/tycho#1464]
Some transitive Eclipse dependencies rely on version ranges, which 

a) makes dependency resolution take long as the version range is re-resolved usually every 24 hours
b) makes the build non-reproducible

Please manage all transitive dependencies with version ranges to a fix version.
Example:

org.eclipse.tycho:tycho-maven-plugin:jar:3.0.0 -> org.eclipse.tycho:tycho-core:jar:3.0.0 -> org.eclipse.tycho:p2-maven-plugin:jar:3.0.0 (https://github.com/eclipse-tycho/tycho/blob/4cffc3a08dee5dd004d2a1b55283674a73572889/p2-maven-plugin/pom.xml#L77) -> org.eclipse.platform:org.eclipse.equinox.frameworkadmin.equinox:jar:1.2.200 -> org.eclipse.platform:org.eclipse.equinox.common:jar:[3.16.0,)

When trying to build with Tycho 3.0.0 I run into 

```
[ERROR]   The project org.apache.sling.ide:sling-ide-tooling:1.2.3-SNAPSHOT (/home/jenkins/jenkins-agent/workspace/_modules_sling-ide-tooling_PR-14/eclipse/pom.xml) has 1 error

[ERROR]     Unresolveable build extension: Plugin org.eclipse.tycho:tycho-maven-plugin:3.0.0 or one of its dependencies could not be resolved: Failed to collect dependencies at org.eclipse.tycho:tycho-maven-plugin:jar:3.0.0 -> org.eclipse.tycho:tycho-core:jar:3.0.0 -> org.eclipse.tycho:p2-maven-plugin:jar:3.0.0 -> org.eclipse.platform:org.eclipse.equinox.frameworkadmin.equinox:jar:1.2.200 -> org.eclipse.platform:org.eclipse.equinox.common:jar:[3.16.0,): No versions available for org.eclipse.platform:org.eclipse.equinox.common:jar:[3.16.0,) within specified range -> [Help 2]
```

(in https://ci-builds.apache.org/blue/organizations/jenkins/Sling%2Fmodules%2Fsling-ide-tooling/detail/PR-14/20/pipeline/50).

**Comment by laeubi** [comment]
Please see 
- https://github.com/eclipse-platform/eclipse.platform.releng/issues/119

**Comment by kwin** [comment]
I don't think that Eclipse will fix this soon and even so this would still require an update to the Eclipse dependency in the first place from Tycho, so I think this issue should be kept open until the issue is fixed in Tycho as well.
You can also workaround that in Tycho by maintaining your own dependencyManagement.

**Comment by laeubi** [comment]
> until the issue is fixed in Tycho as well.

This is not an issue of Tycho.

> You can also workaround that in Tycho by maintaining your own dependencyManagement.

At least I won't "manage" hundreds of versions that needs manual updates and testing on each eclipse release just because platform refuses to publish correct metadata. If you are willing to do this it would be mostly @akurtakov to negotiate about a manageable way.

**Comment by akurtakov** [comment]
Hey, I'm all for using strict versions not ranges. How to do that is better discussed at https://github.com/eclipse-platform/eclipse.platform.releng/issues/119

**Comment by kwin** [comment]
> This is not an issue of Tycho.

I beg to differ, from a consumer perspective it broke with Tycho 3 (with the introduction of https://github.com/eclipse-tycho/tycho/commits/master/p2-maven-plugin)

**Comment by laeubi** [comment]
> I beg to differ, from a consumer perspective it broke with Tycho 3

There is literally nothing we can do for 3.0.0 release, so please 
provide an [integration-test](https://github.com/eclipse/tycho/wiki#providing-an-integration-test) to demonstrate the issue and "we" probably change something. I just can say that at least the last builds of platform with Tycho 3.0.0 seem successful.

Also I tested another build with success, and according to 
https://mvnrepository.com/artifact/org.eclipse.platform/org.eclipse.equinox.common

there **are** versions of org.eclipse.platform:org.eclipse.equinox.common:jar with version >= 3.16.0

So there must be some thing in this build that triggers a problem that is not discovered with the usual tycho builds, e.g. you probably include some other build plugin that prevents maven from resolving the required items for Tycho.

**Comment by kwin** [comment]
The ASF Jenkins with which I build defines another repository for repository "apache.snapshots" in its settings.xml (https://github.com/apache/infrastructure-p6/blob/494f8354d9102625673d912ab692bf31cdbe041f/modules/buildbot_node/templates/m2_settings.erb#L30). If that is used for version range resolution requests it fails as https://repository.apache.org/snapshots/org/eclipse/platform/org.eclipse.equinox.common/maven-metadata.xml returns a 404! This is most probably related to https://issues.apache.org/jira/browse/MNG-7529 but unfortunately there is no Maven version released which fixes this.

**Comment by mickaelistria** [comment]
> This is most probably related to https://issues.apache.org/jira/browse/MNG-7529 but unfortunately there is no Maven version released which fixes this.

if this is the root issue for you, then you should invest in getting it fixed it in Maven directly rather than investing to trying to have workarounds downstream in Tycho or Platform. The world will be a much better place if existing bugs are fixed, instead of new workarounds implemented.

**Comment by tomaswolf** [comment]
I ran into similar problems when trying to build m2e-core (thanks @kwin for the link), getting "Project build error: Unresolveable build extension: Plugin org.eclipse.tycho:tycho-maven-plugin:3.0.0 or one of its dependencies could not be resolved: Failed to collect dependencies at org.eclipse.tycho:tycho-maven-plugin:jar:3.0.0 -> org.eclipse.tycho:tycho-core:jar:3.0.0 -> org.eclipse.tycho:p2-maven-plugin:jar:3.0.0 -> org.eclipse.platform:org.eclipse.equinox.p2.core:jar:2.9.200 -> org.eclipse.platform:org.eclipse.equinox.registry:jar:3.9.0 -> org.eclipse.platform:org.eclipse.equinox.common:jar:[3.13.0,4.0.0)"

Irrespective of whether version ranges are a good or bad idea with maven resolution: I notice that tycho 3.0.0 only downloaded the poms, but not the jars. It created only the following in my local .m2 repository:
```
$ ls -al .m2/repository/org/eclipse/platform/org.eclipse.equinox.common/3.16*
.m2/repository/org/eclipse/platform/org.eclipse.equinox.common/3.16.0:
total 32
drwxr-xr-x   6 thomas  staff   192 Oct 16 14:40 .
drwxr-xr-x  24 thomas  staff   768 Oct 16 14:40 ..
-rw-r--r--   1 thomas  staff   188 Oct 16 14:40 _remote.repositories
-rw-r--r--   1 thomas  staff  1931 Oct 16 14:40 org.eclipse.equinox.common-3.16.0.pom
-rw-r--r--   1 thomas  staff   361 Oct 16 14:40 org.eclipse.equinox.common-3.16.0.pom.lastUpdated
-rw-r--r--   1 thomas  staff    40 Oct 16 14:40 org.eclipse.equinox.common-3.16.0.pom.sha1

.m2/repository/org/eclipse/platform/org.eclipse.equinox.common/3.16.100:
total 32
drwxr-xr-x   6 thomas  staff   192 Oct 16 14:40 .
drwxr-xr-x  24 thomas  staff   768 Oct 16 14:40 ..
-rw-r--r--   1 thomas  staff   190 Oct 16 14:40 _remote.repositories
-rw-r--r--   1 thomas  staff  1948 Oct 16 14:40 org.eclipse.equinox.common-3.16.100.pom
-rw-r--r--   1 thomas  staff   361 Oct 16 14:40 org.eclipse.equinox.common-3.16.100.pom.lastUpdated
-rw-r--r--   1 thomas  staff    40 Oct 16 14:40 org.eclipse.equinox.common-3.16.100.pom.sha1
```
Maven central does have these versions currently, and it also has a 3.16.200. Where are the JARs? The error message above says it cannot find the JAR. Apparently it only looks for the JAR wherever it found the pom. So it puts the pom in my local repo and later claims (somewhat correctly) the JAR was missing since its not in the local repo. It could just go resolve again and download the JAR, or download it right away.

After I made m2e download 3.16.200 (by just adding it as a dependency in some other maven project I had lying around), I got
```
$ ls -al .m2/repository/org/eclipse/platform/org.eclipse.equinox.common/3.16*
.m2/repository/org/eclipse/platform/org.eclipse.equinox.common/3.16.0:
total 32
drwxr-xr-x   6 thomas  staff   192 Oct 16 14:40 .
drwxr-xr-x  24 thomas  staff   768 Oct 16 14:40 ..
-rw-r--r--   1 thomas  staff   188 Oct 16 14:40 _remote.repositories
-rw-r--r--   1 thomas  staff  1931 Oct 16 14:40 org.eclipse.equinox.common-3.16.0.pom
-rw-r--r--   1 thomas  staff   361 Oct 16 14:40 org.eclipse.equinox.common-3.16.0.pom.lastUpdated
-rw-r--r--   1 thomas  staff    40 Oct 16 14:40 org.eclipse.equinox.common-3.16.0.pom.sha1

.m2/repository/org/eclipse/platform/org.eclipse.equinox.common/3.16.100:
total 32
drwxr-xr-x   6 thomas  staff   192 Oct 16 14:40 .
drwxr-xr-x  24 thomas  staff   768 Oct 16 14:40 ..
-rw-r--r--   1 thomas  staff   190 Oct 16 14:40 _remote.repositories
-rw-r--r--   1 thomas  staff  1948 Oct 16 14:40 org.eclipse.equinox.common-3.16.100.pom
-rw-r--r--   1 thomas  staff   361 Oct 16 14:40 org.eclipse.equinox.common-3.16.100.pom.lastUpdated
-rw-r--r--   1 thomas  staff    40 Oct 16 14:40 org.eclipse.equinox.common-3.16.100.pom.sha1

.m2/repository/org/eclipse/platform/org.eclipse.equinox.common/3.16.200:
total 648
drwxr-xr-x  11 thomas  staff     352 Oct 19 20:11 .
drwxr-xr-x  24 thomas  staff     768 Oct 16 14:40 ..
-rw-r--r--   1 thomas  staff     296 Oct 19 20:11 _remote.repositories
-rw-r--r--   1 thomas  staff      99 Oct 19 20:11 m2e-lastUpdated.properties
-rw-r--r--   1 thomas  staff  151421 Oct 19 20:11 org.eclipse.equinox.common-3.16.200-sources.jar
-rw-r--r--   1 thomas  staff      40 Oct 19 20:11 org.eclipse.equinox.common-3.16.200-sources.jar.sha1
-rw-r--r--   1 thomas  staff  149919 Oct 16 14:40 org.eclipse.equinox.common-3.16.200.jar
-rw-r--r--   1 thomas  staff      40 Oct 16 14:40 org.eclipse.equinox.common-3.16.200.jar.sha1
-rw-r--r--   1 thomas  staff    1941 Oct 16 14:40 org.eclipse.equinox.common-3.16.200.pom
-rw-r--r--   1 thomas  staff     361 Oct 16 14:40 org.eclipse.equinox.common-3.16.200.pom.lastUpdated
-rw-r--r--   1 thomas  staff      40 Oct 16 14:40 org.eclipse.equinox.common-3.16.200.pom.sha1
```
Notice that the JAR is present for 3.16.200, put into my local repo by m2e.

And since then the m2e maven build using tycho 3.0.0 (in particular, its generate-OSGi-metadata step) succeeds.

To me this looks like a tycho bug: as if tycho somehow does not download all it should. (m2e also downloads the missing JARs for the 3.16.100 version, where only the pom is already in my local repo.)

**Comment by laeubi** [comment]
> I notice that tycho 3.0.0 only downloaded the poms

Tycho do not download **anything** here, it is **maven** that downloads (and complains) before Tycho can even run.
