### ISSUE TITLE
No goal pages linked from https://tycho.eclipseprojects.io/doc/3.0.0/tycho-ds-plugin/index.html

### ISSUE THREAD

**Issue by kwin** [eclipse-tycho/tycho#1467]
When opening https://tycho.eclipseprojects.io/doc/3.0.0/tycho-ds-plugin/index.html there is no link to any descendant pages like https://tycho.eclipseprojects.io/doc/3.0.0/tycho-ds-plugin/plugin-info.html or https://tycho.eclipseprojects.io/doc/3.0.0/tycho-ds-plugin/declarative-services-mojo.html.

Similarly for other plugins like https://tycho.eclipseprojects.io/doc/3.0.0/tycho-packaging-plugin/index.html or https://tycho.eclipseprojects.io/doc/3.0.0/tycho-p2/tycho-p2-publisher-plugin/index.html and probably others.

There should be a proper multi-module site like outlined at https://maven.apache.org/plugins/maven-site-plugin/examples/multimodule.html with dedicated sidebars (which may inherit some parts from a common parent).

**Comment by mickaelistria** [comment]
Such a contribution would be highly welcome!
