### ISSUE TITLE
Clarify values for "declarative-services" mojo parameter "dsVersion"

### ISSUE THREAD

**Issue by kwin** [eclipse-tycho/tycho#1473]
It seems that the parameter https://github.com/eclipse-tycho/tycho/blob/663a1e16aaa77854823c3f825373b01b5d1fd25c/tycho-ds-plugin/src/main/java/org/eclipse/tycho/ds/DeclarativeServicesMojo.java#L62 is not passed to Bnd at all. On the other hand the version may be useful to set in the context of https://github.com/eclipse-m2e/m2e-core/pull/967. PDE only supports the following values though: https://github.com/eclipse-pde/eclipse.pde/blob/8312046eb6c566df0846f4125c2a5d41dcf0d0a3/ds/org.eclipse.pde.ds.annotations/src/org/eclipse/pde/ds/internal/annotations/DSAnnotationVersion.java.

Please clarify the intent of this parameter and outline possible values.

**Comment by laeubi** [comment]
BND can automatically detect the version, this parameter is only used inside PDE to tell the user if he is using "newer" features, so has no real meaning for the Tycho build. Maybe it could be used later but I personally always use the latest version supported and as you have noticed PDE is way behind what actually is supported already.

**Comment by kwin** [comment]
Which values to expect here, "1.1" or "V1_1" or both?

**Comment by laeubi** [comment]
PDE uses `V1_3` syntax in preference files but Tycho support also 1.3 variant see:
https://github.com/eclipse-tycho/tycho/blob/e40a547f19b389047b19bc4e030c449b5bc84403/tycho-core/src/main/java/org/eclipse/tycho/artifacts/configuration/DeclarativeServiceConfigurationReader.java#L59-L64
