### ISSUE TITLE
Regression: JUnit ParametrizedTest fail because of missing dependencies

### ISSUE THREAD

**Issue by azoitl** [eclipse-tycho/tycho#1481]
After Upgrading to Eclipse Tycho 3.0.0 our parametrized unit tests keep failing becuase of some strange unresolved abstract method problems:

```
org.eclipse.fordiac.ide.structuredtextfunctioneditor.tests.STFunctionValidatorTest.testBinaryOperatorNotApplicableErrorValidator(String,String,String)  Time elapsed: 0.019 s  <<< ERROR!
java.lang.AbstractMethodError: Receiver class org.junit.jupiter.engine.descriptor.TestTemplateExtensionContext does not define or inherit an implementation of the resolved method 'abstract org.junit.jupiter.api.extension.ExecutableInvoker getExecutableInvoker()' of interface org.junit.jupiter.api.extension.ExtensionContext.
```

It seems that the problem already was once in Eclipse Tycho:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=568717

Is this a regression or do I need to change something more with the new Tycho release?

**Comment by laeubi** [comment]
Can you provide an [integration-test](https://github.com/eclipse/tycho/wiki#providing-an-integration-test) to demonstrate the issue?

**Comment by mickaelistria** [comment]
I believe this is already fixed with https://github.com/eclipse-tycho/tycho/commit/91cc9c7e9531da9ca3100dfb60d7ec7cc203bb3a . Please try 3.1.0-SNAPSHOT.

**Comment by azoitl** [comment]
Yes it is thx for letting me know.

**Comment by hengsin** [comment]
would this be back ported to 3.0.* branch ?

**Comment by laeubi** [comment]
@hengsin have you tried Tycho 3.0.3 ?

**Comment by hengsin** [comment]
@laeubi , indeed it is working fine now with 3.0.3, thanks.
