### ISSUE TITLE
Promote checksums from the maven repository for maven-target locations

### ISSUE THREAD

**Issue by laeubi** [eclipse-tycho/tycho#1483]
P2 supports checksum and maven repositories have checksum as well. We should (if available) promote those. 
Similar to
- https://github.com/eclipse-tycho/tycho/issues/661

it would be good to make this configurable.

**Comment by mickaelistria** [comment]
> it would be good to make this configurable.

Why? Can anything bad happen with extra checksums?

**Comment by laeubi** [comment]
> > it would be good to make this configurable.
> 
> Why? Can anything bad happen with extra checksums?

At least they might require extra I/O to be fetched and there is always a case where someone complains ;-)

**Comment by mickaelistria** [comment]
> there is always a case where someone complains ;-)

I think it's not really true. Often people don't complain about what they don't know is happening; also I think this is very hypothetical someone complains, so better not introduce more complexity and more user options until we have 1 serious complaint.
