### ISSUE TITLE
target-platform-configuration cannot be used in parent pom anymore

### ISSUE THREAD

**Issue by Zegveld** [eclipse-tycho/tycho#1501]
we have a parent pom which contains most of our tycho configuration among which the target platform configuration.
This parent pom is then used by multiple maven modules in multiple git repositories.

Since 3.0.0 this usage results in the following exception:
`Execution prepare-test of goal org.eclipse.tycho:target-platform-configuration:3.0.0:target-platform failed: Tycho build extension not configured for MavenProject`
With 2.6.0 this one was allowed inside a `pom` packaging module.

I find no mention of this change in the release-notes.

**Comment by laeubi** [comment]
Can you provide an [integration-test](https://github.com/eclipse/tycho/wiki#providing-an-integration-test) to demonstrate the issue? It seems you are using a custom execution here, so I don't think it is the configuration itself that is causing issues here.

**Comment by Zegveld** [comment]
interesting, was just looking at the integration-tests that are already there, and the situation is listed.
though it might then be related to one of the options we have enabled there.

```
                    <pomDependencies>consider</pomDependencies>
                    <resolver>p2</resolver>
                    <targetDefinitionIncludeSource>force</targetDefinitionIncludeSource>
```

currently working on the integration-test.

**Comment by Zegveld** [comment]
I totally missed that about the id `prepare-test`.
I think this issue might be closable then, because we have a second reference to this plugin outside the tests profile.

Closing this for now, I'll reopen it in case this was not the problem. But preliminary results indicate that this is most likely the issue.

Thanks for the fast response @laeubi
