### ISSUE TITLE
Tycho do not understands BUNDLE_ROOT_PATH

### ISSUE THREAD

**Issue by laeubi** [eclipse-tycho/tycho#1516]
One can change the root of the bundle (for example)

`BUNDLE_ROOT_PATH=src/main/resources`

in `org.eclipse.pde.core.prefs` but then Tycho fails as it search for the manifest always at the root.

**Comment by HannesWell** [comment]
That should not be too complicated. It should be sufficient to read the pde.core preferences and consider the value for `BUNDLE_ROOT_PATH` in `TychoBundleMapping`:
https://github.com/eclipse-tycho/tycho/blob/6bfcb4fee113b3058907efa61086b3cac0e114e8/tycho-extras/tycho-pomless/src/main/java/org/eclipse/tycho/pomless/TychoBundleMapping.java#L68-L74
