### ISSUE TITLE
Add prerequisites to each Maven plugin

### ISSUE THREAD

**Issue by kwin** [eclipse-tycho/tycho#1526]
Currently the Maven prerequisites is only stated in https://github.com/eclipse-tycho/tycho/blob/ac83caac1d94c795d5c62ee9d84f538549048bb9/pom.xml#L61. This is not inherited to child modules though: 

> By default, every model field is inherited as-is from parent, with a few exceptions that are intentionally not inherited: modelVersion, artifactId, profiles (injected in phase 1) and prerequisites.

(from https://maven.apache.org/ref/3.8.6/maven-model-builder/#inheritance-assembly)

That leads to the fact that all Maven plugins (packaging: `maven-plugin`) don't have prerequisites which are automatically evaluated by Maven.

In addition the prerequisites in the root pom.xml should be removed and replaced by an according m-enforcer-p rule as prerequisites are only ever evaluated for packaging `maven-plugin` (compare with https://maven.apache.org/pom.html#Prerequisites)

**Comment by akurtakov** [comment]
Do you think you can spend the time to provide a patch fixing that?

**Comment by laeubi** [comment]
@kwin do you plan a fix, as we are currently prepare for a 3.0.5 Tycho release this might then be worth being included.
