### ISSUE TITLE
Tycho-surefire-plugin should not trim stack traces by default

### ISSUE THREAD

**Issue by Kellindil** [eclipse-tycho/tycho#1551]
The maven-surefire-plugin documentation indicates that the default value for "trimStackTrace" is false (https://maven.apache.org/surefire/maven-surefire-plugin/test-mojo.html#trimStackTrace). Tycho, on the opposite, makes that value true by default https://github.com/eclipse-tycho/tycho/blob/master/tycho-surefire/org.eclipse.tycho.surefire.osgibooter/src/main/java/org/eclipse/tycho/surefire/osgibooter/OsgiSurefireBooter.java#L96

This makes the error reports completely useless in many cases, with no way to salvage them. For example, there is absolutely no way to debug the following:

10:17:26 testConversion[resources/conversion/Exchanges/AddFunctionalExchange](<redacted>.exchanges.ExchangesTest)  Time elapsed: 4.159 s  <<< ERROR!
10:17:26 java.util.ConcurrentModificationException
10:17:26 
10:17:26 testConversion[resources/conversiontomei/Exchanges/AddFunctionalExchange](<redacted>.exchanges.ExchangesTest)  Time elapsed: 4.159 s  <<< ERROR!
10:17:26 java.lang.NullPointerException
10:17:26 

This is made even worse by the fact these two are random failures which I cannot reproduce by running the tests in eclipse and not tycho... so only by having the actual stack trace would I be able to understand what kind of programming error I did leading to a CME.

Understanding that these stack traces weren't there because of tycho not using the same defaults as maven made it pretty time consuming. At the very least, there should be an equivalent documentation to https://maven.apache.org/surefire/maven-surefire-plugin/test-mojo.html that lists the available configuration (since iirc some maven-surefire-plugin options are not available in tycho-surefire-plugin) and defaults used by tycho so that we can find this kind of information.

**Comment by laeubi** [comment]
@Kellindil do you like to propose a patch?

**Comment by Kellindil** [comment]
Well if it's a matter of changing the "_getProperty("trimStackTrace", "true")_", yeah, I can change them all to "false" instead and push a MR, but I think more info about why the decision to change the default value has been initially made could be helpful :).

From what I can see, this "trimStrackTrace" being false means debugging unit tests is impossible, "true" is the only value that makes sense by default imho, and users _can_ disable it if they want... but why did tycho initially decided on making it false? Is this reason still valid today? Any possible issue this could involve if we change a default?

**Comment by laeubi** [comment]
> Well if it's a matter of changing the "_getProperty("trimStackTrace", "true")_", yeah, I can change them all to "false" instead and push a MR, but I think more info about why the decision to change the default value has been initially made could be helpful :).

Simply add a note tho the RELEASE_NOTES.MD informing about the new default and that should be fine.

**Comment by Kellindil** [comment]
I couldn't start the unit tests locally with "mvn clean verify -Pits" because of earlier failures in tycho-document-bundle-plugin so I'll rely on the CI here to get feedback on any test failure.

For more details about the issue : 
"trimStackTrace" trims any stack line that is not present in the test itself. In my case, what I'm starting are parameterized tests so I have a single class with the parameters and the actual code of the test is in a super-class... so the exception is in the super-class and everything gets trimmed. The same would happen for any exception stemming from test utilities.
I think the maven-surefire-plugin default of false is the good option here since we can't make the assumption that all tests will follow the specific pattern required for the trimming to be useful, and finding out why a stack trace is -not- there is pretty hard.
