### ISSUE TITLE
Documentation to Tycho Versions prior 3.0.0

### ISSUE THREAD

**Issue by krit0n** [eclipse-tycho/tycho#1566]
In the Readme the documentation to the latest tycho-Version is referenced. Where do I find the documentation of previous versions?

**Comment by krit0n** [comment]
The readme in [tycho-2.7.x](https://github.com/eclipse-tycho/tycho/tree/tycho-2.7.x) links to https://tycho.eclipseprojects.io/doc/index.html where I find a reference to version 3.0.0

**Comment by laeubi** [comment]
@krit0n I have uploaded the docs for Tycho 2.7.5 here:
https://tycho.eclipseprojects.io/doc/2.7.5/
