### ISSUE TITLE
automatically mark target folders derived in eclipse

### ISSUE THREAD

**Issue by Bananeweizen** [eclipse-tycho/tycho#1591]
I would like to add the https://nodj.github.io/AutoDeriv/ plugin to the Tycho Oomph setup. It allows marking workspace files as derived via a simple gitignore-like config file. That way, stuff in target folders is no longer included in search results etc. I'm using this since years in company projects.
Any objections? Otherwise I would just create a PR.

**Comment by akurtakov** [comment]
Interesting plugin I didn't know about it. I'm a bit concerned it hasn't been released in years.

**Comment by Bananeweizen** [comment]
It hasn't needed any upgrades, since it is basically just a resource change listener implementation. And even if it would break on a future Eclipse platform version, removing it again would be trivial and without problem, since it's functionality is not mandatory, but just "nice to have".

**Comment by akurtakov** [comment]
OK, I don't mind it .

**Comment by laeubi** [comment]
@Bananeweizen maybe this can be integrated in eclipse platform? Or maybe as part of Egit? Would be cool when gitignores would be automatically be ignored....

**Comment by laeubi** [comment]
btw. maybe we can even fix that at m2e? You shouldn't need an additional plugin for that...
