### ISSUE TITLE
wrapped artifacts have a blank in their version

### ISSUE THREAD

**Issue by Bananeweizen** [eclipse-tycho/tycho#1601]
The version of wrapped target artifacts is consistently shown with a leading blank in 2.7.5:
```
[INFO] io.github.glytching:junit-extensions:2.6.0 is wrapped as a bundle with bundle symbolic name wrapped.io.github.glytching.junit-extensions
[INFO] The artifact can be referenced in feature files with the following data: <plugin id="wrapped.io.github.glytching.junit-extensions" version=" 2.6.0" download-size="0" install-size="0" unpack="false"/>
[INFO] nl.jqno.equalsverifier:equalsverifier:3.10.1 is wrapped as a bundle with bundle symbolic name wrapped.nl.jqno.equalsverifier.equalsverifier
[INFO] The artifact can be referenced in feature files with the following data: <plugin id="wrapped.nl.jqno.equalsverifier.equalsverifier" version=" 3.10.1" download-size="0" install-size="0" unpack="false"/>
```
I'm wondering if the manifest parser really leaves the leading blank after the colon, e.g. "Bundle-Name: foo" has the value " foo" then.

**Comment by laeubi** [comment]
Have you checked that ut is really the manifest or just the log message? What about Tycho 3.0?

**Comment by Bananeweizen** [comment]
I've seen the change in https://github.com/eclipse-tycho/tycho/blob/master/tycho-bundles/org.eclipse.tycho.core.shared/src/main/java/org/eclipse/tycho/p2/resolver/WrappedArtifact.java#L147, that is sufficient for me without testing.
