### ISSUE TITLE
Maintain redirect for https://tycho.eclipseprojects.io/

### ISSUE THREAD

**Issue by kwin** [eclipse-tycho/tycho#1603]
Currently https://tycho.eclipseprojects.io/ just exposes "Hello World".
It should redirect to either https://tycho.eclipseprojects.io/doc/latest/ or https://tycho.eclipseprojects.io/doc/

**Comment by laeubi** [comment]
@kwin the idea was actually to build a little front page for Tycho see discussion here:

https://github.com/eclipse-tycho/tycho/issues/1260#issuecomment-1276451709

**Comment by kwin** [comment]
Fixed in https://github.com/eclipse-tycho/eclipse-tycho.github.io/commit/704bb660e9b7431bc0168660470647d648e68228
