### ISSUE TITLE
thousands of fakeRepoXYZ temp folders

### ISSUE THREAD

**Issue by Bananeweizen** [eclipse-tycho/tycho#1614]
The fakeRepo1234567 folders are probably never deleted, I have several thousand of them in my temp folder. Content is always just a single file, like here:
![image](https://user-images.githubusercontent.com/406876/198901975-bace185d-1ac0-442f-8e71-b8035d0d7fd7.png)

**Comment by laeubi** [comment]
Can you try out latest m2e snapshot? See
- https://github.com/eclipse-m2e/m2e-core/pull/934

**Comment by Bananeweizen** [comment]
Not really, but I'm fine with closing, since that has already been fixed.
