### ISSUE TITLE
Do not overwrite MANIFEST.MF and feature.xml files during packaging

### ISSUE THREAD

**Issue by lppedd** [eclipse-tycho/tycho#1621]
Currently, I'm trying to implement multi-branding for an application.
This means I process resources via filtering, `MANIFEST.MF` and `feature.xml` files too to rename bundle symbolic names at build time.

The Tycho Packaging Plugin however always overwrite those two files when packaging the product, even if they're already present under `${project.build.directory}`.

https://github.com/eclipse-tycho/tycho/blob/77243cebc93d0bdbaf31e0e1b1055e29182958d8/tycho-packaging-plugin/src/main/java/org/eclipse/tycho/packaging/PackagePluginMojo.java#L267-L269

And

https://github.com/eclipse-tycho/tycho/blob/77243cebc93d0bdbaf31e0e1b1055e29182958d8/tycho-packaging-plugin/src/main/java/org/eclipse/tycho/packaging/PackageFeatureMojo.java#L124-L130

The proposed change is checking for `!file.exists()` before writing.  
If it's ok I have a PR ready, as I haven't found any workaround.

**Comment by laeubi** [comment]
@lppedd I think this is "by intend" and I'm not sure if it would work nice to change the defaults, e.g. if one do not perform clean then maybe outdated content might be used.

The usual solution to this in maven is to allow to configure the **source** of the file to use instead, so you could write your feature to `target/my_enhanced_feature.xml` and then configure the mojo read its from there instead.

**Comment by mickaelistria** [comment]
I agree `!file.exists()` is not a good check here as we want the file in `target/` to be overwritten if necesary between different invocations of `mvn`. I believe what you want to try is to customize your MANIFEST.MF/feature.xml with a mojo executed during the `process-resources` phase, directly modifying the file in the `target/` folder.

**Comment by laeubi** [comment]
> I believe what you want to try is to customize your MANIFEST.MF/feature.xml with a mojo executed during the `process-resources` phase, directly modifying the file in the `target/` folder.

The file is only copied in the package phase, thus I think a config parameter where the package-mojo reads the file from is more suitable and flexible.

**Comment by lppedd** [comment]
@laeubi done as best as I could. I'm using a custom `MavenResourcesFiltering` so this complicates it a bit.
I'll provide a test for `feature.xml` too as soon as I understand why `maven-resources-plugin` is not running for the `eclipse-feature` packaging.

**Comment by lppedd** [comment]
Nevermind, I've simplified the test.

**Comment by lppedd** [comment]
I think the `eclipse-feature` lifecycle is missing resource processing. Am I right?

https://github.com/eclipse-tycho/tycho/blob/be27fb51ebfaac42a49b6931fb644a93ac080c5c/tycho-maven-plugin/src/main/resources/META-INF/plexus/components.xml#L121-L161

**Comment by laeubi** [comment]
> I think the `eclipse-feature` lifecycle is missing resource processing. Am I right?

at laest ti does not contain it with the default lifecycle, so one needs an explicit binding, but actually I don't see why we should not be able to add it.

**Comment by lppedd** [comment]
> so one needs an explicit binding

Yeah that's fine anyway, but it's just not evident that it is missing in the lifecycle. I had to dig into the plugin code.

**Comment by lppedd** [comment]
I've been working on a fix with your proposed solution.
In the end it's not only related to the feature or to the MANIFEST, but also to categories and products. So it's a bit more complicated.

**Comment by laeubi** [comment]
That sounds great, looking forward to your PR!

**Comment by lppedd** [comment]
@laeubi  I'm stuck on the `eclipse-repository` project build.

I've managed to correctly filter and rename `Bundle-SymbolicName`s and feature IDs for `eclipse-plugin` and `eclipse-feature`.  

However for repositories, the `assemble-repository` mojo fails miserably. It tells me it cannot find dependencies, e.g. `my.old.name`, which is mostly true because that bundle has been built with a MANIFEST `Bundle-SymbolicName` called `my.new.name` thanks to filtering.

Does Tycho cache stuff at the beginning of the session? Where does `assemble-repository` look to understand which features and plugins should be packaged inside the p2 repository?

**Comment by laeubi** [comment]
@lppedd if you like you can still open a PR as draft if you like so we can look at the code directly. If you are changing the coordinates of features/bundles, this can become really tricky, and this is really unusual case. At least you have then call 

```
<plugin>
	<groupId>org.eclipse.tycho</groupId>
	<artifactId>tycho-p2-plugin</artifactId>
	<version>${tycho-version}</version>
	<executions>
		<execution>
			<id>attach-p2-metadata</id>
			<phase>...</phase>
			<goals>
				<goal>p2-metadata</goal>
			</goals>
		</execution>
	</executions>
</plugin>
```

but be aware that Tycho in its default mode might still be confused because it uses the collected data to setup dependencies between modules _before_ starting the build! Using the new resolver (`-Dtycho.resolver.classic=false`) might help here if you setup dependencies in the pom if required to help Tycho as then resolving is only performed *after* the dependents are build.

**Comment by lppedd** [comment]
@laeubi done. Do we want to continue the discussion there?
