### ISSUE TITLE
Lots of plexus.osgi.xxxxx files created in temp folder but not deleted

### ISSUE THREAD

**Issue by Phillipus** [eclipse-tycho/tycho#1624]
Tycho 3.0.0

Each time we build our product a new folder is created in the temp folder with the format `plexus.osgi.cdab2503-28f7-420e-9ceb-f459b84278ef`. These are not deleted so after a while there are very many of these that need to be manually deleted.

These are our poms:

https://github.com/archimatetool/archi/blob/master/pom.xml
https://github.com/archimatetool/archi/blob/master/com.archimatetool.editor.product/pom.xml

**Comment by Bananeweizen** [comment]
reminds me of https://github.com/eclipse-tycho/tycho/issues/1614, but the file seems to be different.

**Comment by Phillipus** [comment]
Thanks for the fix. Will it be backported to Tycho 3.0.x?

**Comment by laeubi** [comment]
> Thanks for the fix. Will it be backported to Tycho 3.0.x?

If someone want do this, see https://github.com/eclipse-tycho/tycho/blob/master/CONTRIBUTING.md#backporting

**Comment by Phillipus** [comment]
Confirmed fixed in 4.0.0.
