### ISSUE TITLE
Target platform resolved multiple times

### ISSUE THREAD

**Issue by Bananeweizen** [eclipse-tycho/tycho#1660]
I've just converted Eclipse-CS from a target platform module to a plain target file reference. Doing that I noticed the target is resolved as many times as modules refer to it. Shouldn't we resolve it only once?
configuration is `${basedir}/../somedir/somefile.target`, which resolves to the same absolute path each time. This is 2.7.5, I still have to verify on 3.0.

See first and last line of this snippet:
```
[INFO] Resolving target definition file:/C:/dev/eclipse-cs/git/eclipse-cs/net.sf.eclipsecs.branding/../net.sf.eclipsecs.target/net.sf.eclipsecs.target.target for environments=[win32/win32/x86_64, linux/gtk/x86_64, macosx/cocoa/x86_64], include source mode=honor, execution environment=StandardEEResolutionHints [executionEnvironment=OSGi profile 'JavaSE-11' { source level: 11, target level: 11}], remote p2 repository options=org.eclipse.tycho.p2.remote.RemoteAgent@2006fdaa...
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[INFO] Resolving dependencies of MavenProject: net.sf.eclipsecs:net.sf.eclipsecs.branding:10.3.3-SNAPSHOT @ C:\dev\eclipse-cs\git\eclipse-cs\net.sf.eclipsecs.branding\pom.xml
[INFO] Resolving target definition file:/C:/dev/eclipse-cs/git/eclipse-cs/net.sf.eclipsecs.checkstyle/../net.sf.eclipsecs.target/net.sf.eclipsecs.target.target for environments=[win32/win32/x86_64, linux/gtk/x86_64, macosx/cocoa/x86_64], include source mode=honor, execution environment=StandardEEResolutionHints [executionEnvironment=OSGi profile 'JavaSE-11' { source level: 11, target level: 11}], remote p2 repository options=org.eclipse.tycho.p2.remote.RemoteAgent@2006fdaa...
...
```

**Comment by laeubi** [comment]
@Bananeweizen do I get ti correctly that you have different targets that point to the same target file via includes? 
Can you provide an [integration-test](https://github.com/eclipse/tycho/wiki#providing-an-integration-test) to demonstrate the issue with a minimal setup?

**Comment by Bananeweizen** [comment]
@laeubi Check lines 341, 343, ... in https://app.travis-ci.com/github/checkstyle/eclipse-cs/jobs/588317951#L341. That's always the same .target file being resolved again and again. I can try to convert that into an integration test with 2 modules and 1 target file.

**Comment by laeubi** [comment]
Backport for 3.x:
- https://github.com/eclipse-tycho/tycho/pull/2068
