### ISSUE TITLE
tycho-versions-plugin should update versions in .target files

### ISSUE THREAD

**Issue by hd42** [eclipse-tycho/tycho#1677]
We use Eclipse .target files that reference other .target files via their maven coordinates, see https://github.com/faktorips/faktorips.base/blob/eeafd2e973075858e409313bbbdd0a2385f3f273/devtools/eclipse/targets/2020-03/eclipse-2020-03.target#L49

When we run a release build, it would be good to replace those references as well (because the target is part of the build and its version is updated by the tycho-versions-plugin). We can do that via a script, but it would be nice if Tycho could do it for us, as it should already have all the necessary information.

**Comment by laeubi** [comment]
The fix for this issue was gently sponsored by [Faktor Zehn GmbH](https://www.faktorzehn.com).

@hd42 this should shortly show up in the current [tycho snapshot](https://github.com/eclipse/tycho/wiki#getting-tycho-snapshots) builds.
