### ISSUE TITLE
create a tycho-spi module

### ISSUE THREAD

**Issue by laeubi** [eclipse-tycho/tycho#1696]
We have some interfaces that are actually meant to be provided by other plugins:

- Timestamp provider
- Tycho Resolver (?)
- P2MetadataProvider
- 

To check if a plugin must be scanned for those we currently have for example:

- `org.eclipse.tycho.p2resolver.P2DependencyResolver.isTychoP2Plugin(PluginDescriptor)`
- `org.eclipse.tycho.p2maven.InstallableUnitGenerator.hasPluginDependency(PluginDescriptor)`

that checks actually for p2-facade, but with the recent changes this does not make much sense now.

The idea is that we probably could instead use a new module "tycho-spi" that hosts items that might be provided by other plugins outside of Tycho (or with Tycho itself)...

This is also closely related to the `PluginRealmHelper` what then might better be part of such a tycho-spi module as well.

**Comment by laeubi** [comment]
For timestamp providers we currently using a different approach that requires to add an artifact to the additional dependencies of Tycho... with special requirements to the configuration, so probably it would be good to reuse the `PluginRealmHelper` concept instead.

**Comment by lppedd** [comment]
This is a great idea. It's also a good idea to give a name to default Tycho beans, e.g., `@Named("tycho")`, and a priority.
This is useful in case a third party wants to replace a default bean with a custom one, maybe delegating some functionalities without referencing internal classes.

```
class TychoBean {
  @Inject
  TychoBean(final TychoDep dep) {
    ...
  }
}
```

where TychoDep is
```
@Named("tycho")
@Priority(0)
class TychoDepImpl implement TychoDep {
  ...
}
```

and where a custom implementation might be
```
@Named
@Priority(1)
class CustomTychoDep implement TychoDep  {
  @Inject
  TychoBean(@Named("tycho") final TychoDep dep) {
    ...
  }
}
```
