### ISSUE TITLE
gpg signing works for the first p2 repo build but not for the second one

### ISSUE THREAD

**Issue by akurtakov** [eclipse-tycho/tycho#1728]
Look at https://ci.eclipse.org/linuxtools/job/linuxtools/job/PR-137/15/console :

* [INFO] --- tycho-gpg-plugin:4.0.0-SNAPSHOT:sign-p2-artifacts (pgpsigner) @ org.eclipse.linuxtools.releng-site --- completes
* [INFO] --- tycho-gpg-plugin:4.0.0-SNAPSHOT:sign-p2-artifacts (pgpsigner) @ org.eclipse.linuxtools.docker-site ---
gpg: signing failed: Bad passphrase
gpg: signing failed: Bad passphrase
fails

I've tried locally and both succeeds but not on Jenkins so if someone has ideas what could be the reason or how to debug it?
The relevant part from the errorlog :
```
Caused by: org.apache.maven.plugin.MojoExecutionException: Exit code: 2
    at org.apache.maven.plugins.gpg.ProxySignerWithPublicKeyAccess.generateSignature (ProxySignerWithPublicKeyAccess.java:109)
    at org.eclipse.tycho.gpg.SignRepositoryArtifactsMojo.handle (SignRepositoryArtifactsMojo.java:274)
    at org.eclipse.tycho.gpg.SignRepositoryArtifactsMojo.lambda$execute$0 (SignRepositoryArtifactsMojo.java:186)
    at java.util.stream.ForEachOps$ForEachOp$OfRef.accept (ForEachOps.java:183)
```

**Comment by akurtakov** [comment]
@merks considering your latest work maybe you have some interest in this one?

**Comment by merks** [comment]
I'll have a look tomorrow. 

Have you done all the magical things described here?

https://github.com/eclipse-tycho/tycho/issues/1724

E.g., maybe `-Dgpg.passphrase="${KEYRING_PASSPHRASE}"` is missing though I see it there, so the message suggest it's not actually correct though...

**Comment by merks** [comment]
The only thing I see that's missing/different that I see in other places where it works is specifying the `<keyname>b6d3ab9bcc641282</keyname>` like here:

https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/c6cc4ae1713b3023b97dfecf0cae20b2cdac575b/eclipse.platform.releng.tychoeclipsebuilder/pom.xml#L46

In your build log I see this:
```
gpg: key F5CBCFD82F07D82E: public key "Eclipse Linux Tools Project <linuxtools-dev@eclipse.org>" imported
```
and in the platform I see this:
```
gpg: key B6D3AB9BCC641282: public key "Eclipse Platform Project <platform-releng-dev@eclipse.org>" imported
```
So I think that's your key.  I think you can also try setting it via a system property:

https://tycho.eclipseprojects.io/doc/latest/tycho-gpg-plugin/sign-p2-artifacts-mojo.html#keyname

**Comment by akurtakov** [comment]
Unfortunately, this doesn't see help https://ci.eclipse.org/linuxtools/job/linuxtools/job/PR-137/18/console

**Comment by merks** [comment]
I see messages like this:
```
[INFO] --- tycho-gpg-plugin:4.0.0-SNAPSHOT:sign-p2-artifacts (pgpsigner) @ org.eclipse.linuxtools.docker-site ---
gpg: /home/vnc/.gnupg/gpg.conf:3: invalid option
gpg: /home/vnc/.gnupg/gpg.conf:4: invalid option
gpg: /home/vnc/.gnupg/gpg.conf:5: invalid option
gpg: /home/vnc/.gnupg/gpg.conf:6: invalid option
gpg: /home/vnc/.gnupg/gpg.conf:7: invalid option
```
So the failure is different now I think.  I'll look more closely right now....

**Comment by merks** [comment]
No that was there in 17 as well.   But I see `tycho-gpg-plugin:4.0.0-SNAPSHOT:sign-p2-artifacts (pgpsigner)` only once in the log so I don't think one site is working by the other not...

**Comment by merks** [comment]
I do see this:
```
[INFO] --- tycho-gpg-plugin:4.0.0-SNAPSHOT:sign-p2-artifacts (pgpsigner) @ org.eclipse.linuxtools.releng-site ---
```
and there seems to failure there, then later this:
```
[INFO] --- tycho-gpg-plugin:4.0.0-SNAPSHOT:sign-p2-artifacts (pgpsigner) @ org.eclipse.linuxtools.docker-site ---
gpg: /home/vnc/.gnupg/gpg.conf:3: invalid option
gpg: /home/vnc/.gnupg/gpg.conf:4: invalid option
gpg: /home/vnc/.gnupg/gpg.conf:5: invalid option
gpg: /home/vnc/.gnupg/gpg.conf:6: invalid option
gpg: /home/vnc/.gnupg/gpg.conf:7: invalid option
```
So how is that the gpg.conf could become invalid?

Note that the platform does not mess around with the gpg.conf:

https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/c6cc4ae1713b3023b97dfecf0cae20b2cdac575b/Jenkinsfile#L15-L22

I've seen that simplified form in several Jenkins files...

**Comment by akurtakov** [comment]
I have another run not playing with gpg.conf (I've added that yesterday for the sake of "trying).

**Comment by akurtakov** [comment]
So back to bad passphrase https://ci.eclipse.org/linuxtools/job/linuxtools/job/PR-137/19/console

**Comment by merks** [comment]
Yes, and again, only for the second one.  It's really strange and inexplicable.   I wonder if it's really just the second one, i.e., if you disabled the first one that works would the second one then start to work instead?

I don't know if you want to be a guinea pig and try the bc signer or even the the simplified configuration approach; the one that bypasses gpg completely? 

I'll test that on a different build now to see if that actually works on a real ci instance...

**Comment by akurtakov** [comment]
> Yes, and again, only for the second one. It's really strange and inexplicable. I wonder if it's really just the second one, i.e., if you disabled the first one that works would the second one then start to work instead?
> 
> I don't know if you want to be a guinea pig and try the bc signer or even the the simplified configuration approach; the one that bypasses gpg completely?

Just tell me how.

**Comment by merks** [comment]
Let me test that it works on a sample and then I will share the details...

**Comment by akurtakov** [comment]
I remembered smth that might be related - there could be second  revoked key https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/2282

**Comment by laeubi** [comment]
@merks I think you can just suggest a change to the Jenkinsfile as PR then @akurtakov can replay the build with the changed jenkins file (select the Job, then "Replay" then insert new Jenkinsfile content in the box).

**Comment by merks** [comment]
Yes, but i have a much smaller example that runs in 1 minute that will shorten the feedback loop...

**Comment by merks** [comment]
I see a failure like this trying the new approach:
```
Caused by: java.lang.NullPointerException: Cannot invoke "org.bouncycastle.openpgp.PGPPrivateKey.getKeyID()" because "<parameter2>" is null
    at org.bouncycastle.openpgp.operator.jcajce.JcaPGPContentSignerBuilder.build (Unknown Source)
    at org.bouncycastle.openpgp.PGPSignatureGenerator.init (Unknown Source)
    at org.eclipse.tycho.gpg.BouncyCastleSigner.generateSignature (BouncyCastleSigner.java:138)
    at org.apache.maven.plugins.gpg.ProxySignerWithPublicKeyAccess.generateSignature (ProxySignerWithPublicKeyAccess.java:101)
    at org.eclipse.tycho.gpg.SignRepositoryArtifactsMojo.handle (SignRepositoryArtifactsMojo.java:286)
    at org.eclipse.tycho.gpg.SignRepositoryArtifactsMojo.lambda$execute$0 (SignRepositoryArtifactsMojo.java:198)
```
So further work is required.  :-(

I think additional useful logging needs to be added...  I would expect not creating/finding a private key to throw an exception very early...

**Comment by laeubi** [comment]
Just keep in mind that in your example Jenkins snippet yesterday there was an error because you use PGP_PASSPHRASE two times, just in case you copied it from your live example ...

**Comment by merks** [comment]
FYI, I created a separate runnable jar with trimmed down BC signer jar that I could run on a real ci instance until I got it to work:
```
	public static void main(String[] args) throws Exception {
		var signer = new BouncyCastleSigner();
		if (args.length == 3) {
			String secretKeys = Files.readString(Path.of(args[2]));
			signer.configure(args[0], args[1], null, secretKeys);
		} else {
			String secretKeys = Files.readString(Path.of(args[1]));
			signer.configure(null, args[0], null, secretKeys);
		}
		var target = Files.createTempFile("pgp", ".info");
		SignatureStore signature = signer.generateSignature(target.toFile());
	}
```
The tricky thing is the Foundation key has a subkey and only the subkey is a signing key so some additional logic is needed to find it.
```
Copying file to bc.jar
[test-bc] $ /bin/sh -xe /tmp/jenkins3789068084081486807.sh
+ java -jar bc.jar 2E8E9CF8 **** ****
Secret key available for public key: 1e6f99794576b6032d257293c34aebd62e8e9cf8
Secret key available for public key: 4777dd30711ea6af367f3478eb3c38f6c7a0f00d
??c34aebd62e8e9cf8
Trying to get the private key of the secret key of public key: 4777dd30711ea6af367f3478eb3c38f6c7a0f00d
Got the private key of the secret key of public key: 4777dd30711ea6af367f3478eb3c38f6c7a0f00d
Finished: SUCCESS
```
I need to put that logic back into the Tycho class, but I have to go out for a while before I get to that.

It's probably worth the wait...

**Comment by laeubi** [comment]
@merks you might want to get some inspirations from: https://www.simplify4u.org/sign-maven-plugin/index.html as suggested by @kwin

**Comment by mickaelistria** [comment]
This doesn't look like a Tycho issue but maybe more a linuxtools CI config or infra issue.
