### ISSUE TITLE
No documentation for tycho-p2-plugin

### ISSUE THREAD

**Issue by LorenzoBettini** [eclipse-tycho/tycho#1732]
I seem to understand that the goals and arguments of `tycho-p2-plugin` are not shown in https://tycho.eclipseprojects.io/doc/latest

For example, things like https://wiki.eclipse.org/Tycho/Release_Notes/1.3#download.stats_artifact_metadata_property

**Comment by laeubi** [comment]
The documentations seems here: 
https://tycho.eclipseprojects.io/doc/latest/tycho-p2/tycho-p2-plugin/plugin-info.html
but missing in the navigation, do you like to prepare a PR?

**Comment by LorenzoBettini** [comment]
@laeubi I created the PR.

However, I think there is still some missing documentation for some configuration properties and some goals. We can open new issues for those. I don't think I'll be able to document those goals and properties though
