### ISSUE TITLE
error log spammed by "foo and bar names differ only by case. This may lead to an unexpected outcome on case-insensitive filesystems."

### ISSUE THREAD

**Issue by Bananeweizen** [eclipse-tycho/tycho#1789]
During a build the error log is flooded by entries like below:
![grafik](https://user-images.githubusercontent.com/406876/205358333-c9f94452-9712-46d1-9231-bdefaf7f122d.png)

The only reference I have found is https://github.com/codehaus-plexus/plexus-archiver/pull/180. I guess it might have come with the recent maven-dependency-plugin update (at least I could trace one occurrence of that log message in a pure maven build back to that upgrade), but I'm not really sure. Anyone else with more insights?

**Comment by Bananeweizen** [comment]
Am I the only one seeing those?

**Comment by laeubi** [comment]
> Am I the only one seeing those?

If I understand correctly this only happens on windows. The question is, what can Tycho do about this? I fear we can only hope the bug is fixed, released and then update Tycho?

**Comment by Bananeweizen** [comment]
We could downgrade the maven-dependency-plugin update which I linked above. But I'm not really sure if that is really what introduced the error.

**Comment by Bananeweizen** [comment]
Just in case someone else than me sees that issue, I've forwarded this to https://github.com/codehaus-plexus/plexus-archiver/issues/248
