### ISSUE TITLE
Support additionalFileSets for package-feature Mojo

### ISSUE THREAD

**Issue by lppedd** [eclipse-tycho/tycho#1869]
I've noticed the `additionalFileSets` parameter of `tycho-packaging-plugin` is supported only for plugins, not for features.
I'm trying to filter `feature*.properties` files, and would like to include them instead of what's used via `build.properties`.

I can give it a go myself in case.

**Comment by lppedd** [comment]
I've started working on this, @laeubi were there any practical reasons as to why this was not done before?

**Comment by laeubi** [comment]
not that I'm aware of...
