### ISSUE TITLE
MirroringArtifactProvider.getArtifactDescriptors(IArtifactKey) downloads items

### ISSUE THREAD

**Issue by laeubi** [eclipse-tycho/tycho#1980]
I just noticed that `MirroringArtifactProvider.getArtifactDescriptors(IArtifactKey) `actually downloads the artifact.

This is called as part of `org.eclipse.equinox.p2.repository.artifact.IArtifactRepository.getArtifactDescriptors(IArtifactKey)` that says:

>  Return the set of artifact descriptors describing the ways that this repository can supply the artifact associated with the given artifact key

I think the important part is the "can supply the artifact", so downloading at this point seems wrong, especially as `IArtifactRepository` has a method `IArtifactRepository.getArtifact(IArtifactDescriptor, OutputStream, IProgressMonitor)`, @mickaelistria can you remember why this was done that way? If I understand correctly this is mostly so we can return a "local" descriptor but this should be possible without downloading the item first?

**Comment by mickaelistria** [comment]
I don't know the reason for the current implementation; and I agree with your interpretation that downloading seems too happen too eagerly in this method; the descriptor indeed doesn't require the artifact to be usable locally.
