### ISSUE TITLE
Tycho doesn't respect --no-transfer-progress

### ISSUE THREAD

**Issue by Bananeweizen** [eclipse-tycho/tycho#1981]
Building m2e with "mvn verify -ntp" all the non-Tycho downloads are silenced, but Tycho still shows progress messages, although it shouldn't:
![grafik](https://user-images.githubusercontent.com/406876/212534423-d5f6fae5-765b-4a20-ad49-4ac913ddcaaa.png)

**Comment by laeubi** [comment]
Tycho currently only support `-B`  option.

**Comment by Bananeweizen** [comment]
Surprisingly, I did not even find a related getter in MavenExecutionRequest, while I would have expected that in the version of the maven-core.jar already. Am I looking into the wrong part of the code?

**Comment by laeubi** [comment]
Usual sequence is:

1. Checkout maven code
2. Search for `"-ntp"` (Should be somewhere in `MavenCli` or near to it...
3. Check how this is then passed and where this set the value, some values are even not accessible from the plugin at all
4. now use that in Tycho e.g. `org.eclipse.tycho.p2maven.transport.TychoRepositoryTransport` wher currently only interactive is evaluated (from `session.getRequest().isInteractiveMode()`)

**Comment by laeubi** [comment]
@Bananeweizen I think this is fixed now, do you like to propose a patch for maven to add an explicit accessor here:

https://github.com/apache/maven

I think this would be useful for others as well.
