### ISSUE TITLE
Allow configuring of tycho-p2-publisher locations

### ISSUE THREAD

**Issue by kjsmita6** [eclipse-tycho/tycho#2002]
Tycho p2 publisher plugin only looks at files in the project root. Usually, this is fine but it doesn't allow things like resource filtering to take place. For example, say I have a `category.xml` file that has the following contents:

```xml
<repository-reference location="https://download.eclipse.org/tools/orbit/downloads/${eclipse-release.version}" enabled="true" />
<repository-reference location="https://download.eclipse.org/releases/${eclipse-release.version}" enabled="true" />
```
where `eclipse-release.version` is defined in the pom. By only reading at the root of the project, this resource filtering doesn't work without doing something like:

```xml
            <plugin>
                <artifactId>maven-clean-plugin</artifactId>
                <configuration>
                    <filesets>
                        <fileset>
                            <directory>.</directory>
                            <includes>
                                <include>category.xml</include>
                            </includes>
                        </fileset>
                    </filesets>
                </configuration>
            </plugin>
            <plugin>
                <artifactId>maven-resources-plugin</artifactId>
                <configuration>
                    <outputDirectory>${project.basedir}</outputDirectory>
                </configuration>
            </plugin>
```

This would be unnecessary if you could configure the publisher to look elsewhere, say `target/category.xml`. Looking at the mojo source there is a property to control this. Setting this property to `${project.build.outputDirectory}` (where the filtered `category.xml` is put) appears to do nothing as the resulting site is empty.

**Comment by laeubi** [comment]
See https://tycho.eclipseprojects.io/doc/master/tycho-p2/tycho-p2-repository-plugin/assemble-maven-repository-mojo.html#categoryFile (included in the current [tycho snapshot](https://github.com/eclipse/tycho/wiki#getting-tycho-snapshots) build)

**Comment by kjsmita6** [comment]
I see, thank you. So there is no way to do this in 3.x?

**Comment by laeubi** [comment]
Not unless someone takes the effort to [backport](https://github.com/eclipse-tycho/tycho/blob/master/CONTRIBUTING.md#backporting) this....
