### ISSUE TITLE
Investigate Text compare OOM

### ISSUE THREAD

**Issue by laeubi** [eclipse-tycho/tycho#2006]
Build fails with (unrelated) OOM in tycho code. 
I assume this is some new tycho issue, unrelated to the change here => merging.

@laeubi : FYI, you mentioned recently tycho did some upgrade, may be related: https://ci.eclipse.org/platform/job/eclipse.platform.releng.aggregator/job/PR-813/1/console
```
17:16:05  [ERROR] Java heap space -> [Help 1]
17:16:05  java.lang.OutOfMemoryError: Java heap space
17:16:05      at java.util.Arrays.copyOf (Arrays.java:3481)
17:16:05      at java.util.ArrayList.grow (ArrayList.java:237)
17:16:05      at java.util.ArrayList.grow (ArrayList.java:244)
17:16:05      at java.util.ArrayList.add (ArrayList.java:454)
17:16:05      at java.util.ArrayList.add (ArrayList.java:467)
17:16:05      at org.apache.commons.io.IOUtils.readLines (IOUtils.java:1991)
17:16:05      at org.apache.commons.io.IOUtils.readLines (IOUtils.java:1945)
17:16:05      at org.eclipse.tycho.zipcomparator.internal.TextComparator.createDelta (TextComparator.java:108)
17:16:05      at org.eclipse.tycho.zipcomparator.internal.TextComparator.getDelta (TextComparator.java:46)
17:16:05      at org.eclipse.tycho.zipcomparator.internal.ZipComparatorImpl.getDelta (ZipComparatorImpl.java:112)
17:16:05      at org.eclipse.tycho.zipcomparator.internal.ZipComparatorImpl.getDelta (ZipComparatorImpl.java:71)
17:16:05      at org.eclipse.tycho.plugins.p2.BaselineValidator.getDelta (BaselineValidator.java:238)
17:16:05      at org.eclipse.tycho.plugins.p2.BaselineValidator.validateAndReplace (BaselineValidator.java:92)
17:16:05      at org.eclipse.tycho.plugins.p2.P2MetadataMojo.attachP2Metadata (P2MetadataMojo.java:195)
17:16:05      at org.eclipse.tycho.plugins.p2.P2MetadataMojo.execute (P2MetadataMojo.java:150)
17:16:05      at org.eclipse.tycho.plugins.p2.P2MetadataDefaultMojo.execute (P2MetadataDefaultMojo.java:34)
17:16:05      at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
17:16:05      at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:301)
17:16:05      at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:211)
17:16:05      at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:165)
17:16:05      at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:157)
17:16:05      at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:121)
17:16:05      at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
17:16:05      at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
17:16:05      at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:127)
```

_Originally posted by @iloveeclipse in https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/813#issuecomment-1398622149_

**Comment by laeubi** [comment]
FYI @iloveeclipse I'll try to investigate on this seems some big files still can cause issues (or build is near memory limit)

**Comment by iloveeclipse** [comment]
I have no idea how big heap is set in Jenkins build for releng build. On JDT project I saw it was always limited to 1 GB.

**Comment by laeubi** [comment]
Actually full diffs should be disabled by default and comparing limited to files < 5 mb so I'm a bit confused but will check if something slipped in unwanted...

**Comment by iloveeclipse** [comment]
Afeter ome successful build, SDK fails now with **yet another** error: https://ci.eclipse.org/releng/job/Builds/job/I-build-4.27/83/console

I assume this is caused by tycho changes (this one), since there were no SDK code changes...

**Comment by laeubi** [comment]
Why do you assume this? I can't see any stacktrace or error that indicates anything in this direction...

**Comment by iloveeclipse** [comment]
Could you please check if the tycho version used for last failed SDK build was different one compared to the previous successfull one? If yes, could you please check which changes were in that version. Since there were no SDK changes between builds, my assumption is that some external reason is responsible for the build failure, and if the tycho changed, this would be the mkst obvious one.

**Comment by laeubi** [comment]
Currently there is an open PR that indicates that the actuall number of runs can be an issue:
- https://github.com/eclipse-tycho/tycho/pull/2010

so I assume one first waits until this is fixed before further investigation.

**Comment by iloveeclipse** [comment]
> so I assume one first waits until this is fixed before further investigation.

Not sure how a **planned** PR can affect the broken build.

AS IS: 
- build https://ci.eclipse.org/releng/job/Builds/job/I-build-4.27/82/ succeeds.
- build few hours later https://ci.eclipse.org/releng/job/Builds/job/I-build-4.27/83/ fails.

The **only** SDK change between is this commit: https://github.com/eclipse-jdt/eclipse.jdt.ui/commit/468dc484376d34880dd8725927f4ce35c6cb0d97 and that has no relationship to failure.

So my naive assumption is that some recent tycho change affects the SDK build.

The tycho change between the builds is most likely only this one: https://github.com/eclipse-tycho/tycho/commit/9a5ea65a7e20988f37a34bc6caa86a70e1516986.
However I'm not sure when tycho is deployed and when SDK build picks up the new version, so it could be that some other recent tycho changes could be the problem. 

Unfortunately, looks like I can't find exact tycho build version, all what I see is `Tycho Version:  4.0.0-SNAPSHOT` in the log files.

- **Are** there any traces of **exact** tycho version used except that one?
- If not, could the "snapshot" build print additionally **commit** hash on which it was built please?

**Comment by laeubi** [comment]
> * If not, could the "snapshot" build print additionally **commit** hash on which it was built please?

Possibly yes, but its currently not implemented.
