### ISSUE TITLE
Issue getting sources

### ISSUE THREAD

**Issue by mickaelistria** [eclipse-tycho/tycho#2009]
See attached project [jdom-sources.zip](https://github.com/eclipse-tycho/tycho/files/10469777/jdom-sources.zip), and build it with a clean repo.
Expected: Build works
Got:
```
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-p2-repository-plugin:4.0.0-SNAPSHOT:assemble-repository (default-assemble-repository) on project include-jdom-sources: Could not assemble p2 repository: Mirroring failed: Messages while mirroring artifact descriptors.: [Failed to transfer artifact packed: osgi.bundle,org.jdom.source,1.1.1.v201101151400.: [Download of osgi.bundle,org.jdom.source,1.1.1.v201101151400 failed on repository file:/resolution-context-artifacts@%252Fhome%252Fmistria%252Fgit%252Feclipse.platform.releng.aggregator-GitHub%252Feclipse.platform.releng.tychoeclipsebuilder%252Feclipse.platform.repository-test. Retrying. : [Artifact packed: osgi.bundle,org.jdom.source,1.1.1.v201101151400 is not available in the repository file:/home/mistria/sandbox/lolrepo/]; Artifact not found: packed: osgi.bundle,org.jdom.source,1.1.1.v201101151400.]] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
```

**Comment by mickaelistria** [comment]
Note that on the 2nd build, when artifact is already in the local repository, then the error isn't happening...

**Comment by mickaelistria** [comment]
I'm trying to write an automated test, but it's made trickier as we need to use a dedicated Maven repo (which makes the test considerably slower). If there a known good practice to mimic for that case? If not, should I just set the local repo to a temp directory to run this test?

**Comment by mickaelistria** [comment]
As I'm debugging, I can see that the line causing the issues are https://github.com/eclipse-tycho/tycho/blob/c2025b31b8d88cd0042d3555de63f4df32997e03/tycho-bundles/org.eclipse.tycho.core.shared/src/main/java/org/eclipse/tycho/p2/repository/MirroringArtifactProvider.java#L176..L181 which were introduce with #1980 .
This has let the "packed" artifact descriptors being listed and prioritized in Tycho, while it's actually not supported any longer. I'm trying a PR that just keep canonical artifacts.

**Comment by laeubi** [comment]
You should be able to do something like here where I clear out some specific items from the index:

https://github.com/eclipse-tycho/tycho/blob/a9bb8fbe9da512f890c3c7ecad471b4898e2226a/tycho-its/src/test/java/org/eclipse/tycho/test/p2Repository/P2RepositoryDownloadTest.java#L33-L46

if they are not at the index, Tycho should download them again. If that not work, let me know and I can take a look tomorrow how we can probably archive this without a full clean repo.
