### ISSUE TITLE
NoSuchMethodError: 'void org.eclipse.tycho.p2.metadata.PublisherOptions.<init>(boolean)'

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-tycho/tycho#2014]
See https://ci.eclipse.org/jdt/job/eclipse.jdt.ui-github/job/PR-406/1/console

```
 [ERROR] Failed to execute goal org.eclipse.tycho:tycho-p2-plugin:4.0.0-SNAPSHOT:p2-metadata-default (default-p2-metadata-default) on project org.eclipse.ltk.core.refactoring: Execution default-p2-metadata-default of goal org.eclipse.tycho:tycho-p2-plugin:4.0.0-SNAPSHOT:p2-metadata-default failed: An API incompatibility was encountered while executing org.eclipse.tycho:tycho-p2-plugin:4.0.0-SNAPSHOT:p2-metadata-default: java.lang.NoSuchMethodError: 'void org.eclipse.tycho.p2.metadata.PublisherOptions.<init>(boolean)'
```

**Comment by laeubi** [comment]
I'll take a look at this tomorrow.

**Comment by laeubi** [comment]
I have run a local build and could not yet find any problems, but suggest to enhance the maven options so we probably get better error reporting and ensure snapshots are always updated during build:
https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/407

**Comment by iloveeclipse** [comment]
Can be closed now. Whatever tycho version was deployed recently seem to have the fix.
