### ISSUE TITLE
Is tycho-snapshots down?

### ISSUE THREAD

**Issue by hd42** [eclipse-tycho/tycho#2016]
Today, my build is full of lines like this:
```
Downloading from tycho-snapshots: https://repo.eclipse.org/content/repositories/tycho-snapshots/org/eclipse/tycho/tycho-build/3.0.2-SNAPSHOT/maven-metadata.xml
[WARNING] Could not transfer metadata org.eclipse.tycho:tycho-build:3.0.2-SNAPSHOT/maven-metadata.xml from/to tycho-snapshots (https://repo.eclipse.org/content/repositories/tycho-snapshots/): transfer failed for https://repo.eclipse.org/content/repositories/tycho-snapshots/org/eclipse/tycho/tycho-build/3.0.2-SNAPSHOT/maven-metadata.xml, status: 503 Service Unavailable
```

and a manual call to https://repo.eclipse.org/content/repositories/tycho-snapshots/ in the browser displays

Application is not available

The application is currently not serving requests at this endpoint. It may not have been started or is still starting.

Possible reasons you are seeing this page:

    The host doesn't exist. Make sure the hostname was typed correctly and that a route matching this hostname exists.
    The host exists, but doesn't have a matching path. Check if the URL path was typed correctly and that the route was created using the desired path.
    Route and path matches, but all pods are down. Make sure that the resources exposed by this route (pods, services, deployment configs, etc) have at least one pod running.

**Comment by mickaelistria** [comment]
Most of Eclipse infra is in a bad state today: https://www.eclipsestatus.io/ . There is nothing we can do on project end, the issue is in the hands of Eclipse Foundation infrastructure team.

**Comment by hd42** [comment]
Thank you for the link
