### ISSUE TITLE
Used Tycho snapshot version can't be identified by looking at maven log

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-tycho/tycho#2018]
As mentioned in https://github.com/eclipse-tycho/tycho/issues/2006#issuecomment-1399220090, trying to identify where the Tycho problem appears and which exact Tycho **snapshot** version was used for which build is currently impossible.

> Unfortunately, looks like I can't find exact tycho build version, all what I see is Tycho Version:  4.0.0-SNAPSHOT in the log files

Same here https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/815#issuecomment-1401855127 - no idea which exact build fixed the problem.

Tycho snapshot versions should report **exact** version of the used code, means: add a git commit hash to the version reported or print that information by default, something "using snapshot 1.2.3-snapshot@commit xyz".

Otherwise bisecting / understanding build issues is impossible, considering that any time next build can pick next (unidentifiable) tycho snapshot.

**Comment by laeubi** [comment]
Jenkins has `GIT_COMMIT` environment variable so probably we can pass that to the build and put it in the version info then.
