### ISSUE TITLE
Multiple target file resolves if target file referece is used instead of a target project

### ISSUE THREAD

**Issue by vogella** [eclipse-tycho/tycho#2040]
In one of the projects I'm involved we see a serious performance increase if we use a target file instead of a target project.

It seems to have happened between 2.7.4 and 3.0.1, I ti

````
<target>
						<artifact>
							<groupId>com.example</groupId>
							<artifactId>target</artifactId>
							<version>1.0.0</version>
						</artifact>
					</target>
````
Run the build in around 5 minutes.

If we switch to using the file directly the build time increases to ~30 mins.

````
<target>
   <file>../target-platform/target-platform.target</file>
</target>
````

And we see that the Maven dependencies log message multiple times.

**Comment by vogella** [comment]
Example available at: https://github.com/vogellacompany/eclipse4book/tree/target-file-example

**Comment by vogella** [comment]
> @vogella I think there was already a fix for this in 4.x can you try out the current [tycho snapshot](https://github.com/eclipse/tycho/wiki#getting-tycho-snapshots) build?

Can do. What is the snapshot version? 4.0.0-SNAPSHOT?

**Comment by laeubi** [comment]
4.0.0-SNAPSHOT and 3.0.2-SNAPSHOT

**Comment by vogella** [comment]
Not fixed in 3.0.2-SNAPSHOT Now testing 4.0.0-SNAPSHOT

**Comment by vogella** [comment]
Fixed in 4.0.0-SNAPSHOT

**Comment by laeubi** [comment]
Thanks for verification.

**Comment by vogella** [comment]
@laeubi looks good with the upcoming 4.0.0 release. Do you want to downport this also to 3.0.2 or shall we close this bug report?

**Comment by laeubi** [comment]
Regarding back-ports please see https://github.com/eclipse-tycho/tycho/blob/master/CONTRIBUTING.md#backporting for details.
