### ISSUE TITLE
FTP connection should be kept alive/re-initialized during build process

### ISSUE THREAD

**Issue by lppedd** [eclipse-tycho/tycho#2054]
If a lot of time might pass by between FTP calls, the FTP connection might be dropped abruptly.  
A good enhancement might be using a background thread sending `NOOP` commands to keep the connection alive, or re-connect automatically when a `FTPConnectionClosedException` is thrown.

**Comment by laeubi** [comment]
Reconnection if connection is lost seems a good way.
