### ISSUE TITLE
includeAllSources doesn't work for a simple product

### ISSUE THREAD

**Issue by orionll** [eclipse-tycho/tycho#2078]
I've been trying to test the new option `includeAllSources` (#926) on our product. We want to build a repository with all plugins and theirs sources along with the product itself. I added the option to the configuration section of `tycho-p2-repository-plugin`, but the build still doesn't include the sources.

I've created a minimal reproducible example here: [orionll/com.example.e4.rcp](https://github.com/orionll/com.example.e4.rcp). It's a simple product with one plugin. You can clone it and run `mvn verify` with Java 17. The build will run fine but their will be no source plugins in `com.example.e4.rcp\com.example.e4.rcp.product\target\repository\plugins` folder.

I already spent two days debugging the build but with no luck.

Is this a bug in Tycho or did I misconfigure the build?

**Comment by laeubi** [comment]
@orionll I think this option is currently only supported when building an update-site but not products, if you like you can transform your example to an [integration-test](https://github.com/eclipse/tycho/wiki#providing-an-integration-test) to demonstrate the issue and we can try to enhance this to products as well (seems more an option of the `tycho-p2-director-plugin:materialize-products` goal then.

**Comment by mickaelistria** [comment]
> I think this option is currently only supported when building an update-site but not products

I believe it is supposed to work for products and category.xml equally, as both are "DependencySeeds" in the mirroring step. But it is not really tested as far as I know, so it's probably a bug that the p2 repo isn't properly populated when originating from a product.
@orionll would you be able to try fixing it and submitting a PR?

> we can try to enhance this to products as well (seems more an option of the tycho-p2-director-plugin:materialize-products goal then.

That (materializing the product greedily with sources) is almost a separate and unrelated topic in term of implementation. It would be worth a dedicated issue report, if it doesn't already exists.

**Comment by orionll** [comment]
Does this option work at all? I changed my product to an update site: https://github.com/orionll/com.example.e4.rcp. And I still get no sources after I run `mvn verify`.

**Comment by mickaelistria** [comment]
It does work for Eclipse Platform and other projects.

**Comment by laeubi** [comment]
Your example uses Tycho `3.0.3` but this feature is only available for Tycho 4 (SNAPSHOT) please
try out the current [tycho snapshot](https://github.com/eclipse/tycho/wiki#getting-tycho-snapshots) build.

**Comment by orionll** [comment]
I'm confused. The [release notes](https://github.com/eclipse-tycho/tycho/blob/tycho-3.0.0/RELEASE_NOTES.md) say that the option `includeAllSources` appeared in Tycho 3.0.0. So, is it non-working in Tycho 3 and works only in Tycho 4?

**Comment by laeubi** [comment]
As far as I know there was a bug in 3.x thats was fixed in 4.x so the simplest solution would be to check if 4.x works.

**Comment by laeubi** [comment]
@orionll I have checked this now and Tycho 3.x is missing the bugfix and it can not simply be cherrypicket but would require a full backport. So please try out the 4.x SNAPSHOT version.

**Comment by orionll** [comment]
Thanks, 4.x SNAPSHOT works. Are there any plans to backport it to 3.x?

**Comment by laeubi** [comment]
Regarding back-ports please see https://github.com/eclipse-tycho/tycho/blob/master/CONTRIBUTING.md#backporting for details.
