### ISSUE TITLE
jgit extension produces warnings with Maven 3.9.0

### ISSUE THREAD

**Issue by Bananeweizen** [eclipse-tycho/tycho#2080]
Maven 3.9.0 seems to validate entries in the configuration blocks against the declared parameters of a mojo. I've found some deprecated/removed config entries in other plugins that way. Unfortunately Tycho throws warnings simply because of not declared parameters in the jgit timestamp provider. The code of that plugin just XML-parses the configuration block instead of defining any parameters.
```
[INFO] ------------------< com.etas.common:com.etas.commons >------------------
[INFO] Building com.etas.commons 5.6.5-SNAPSHOT                          [2/51]
[INFO]   from ..\..\plugins\com.etas.commons\pom.xml
[INFO] ---------------------------[ eclipse-plugin ]---------------------------
[WARNING] Parameter 'jgit.dirtyWorkingTree' is unknown for plugin 'tycho-packaging-plugin:2.7.5:build-qualifier (default-build-qualifier)'
[WARNING] Parameter 'jgit.ignore' is unknown for plugin 'tycho-packaging-plugin:2.7.5:build-qualifier (default-build-qualifier)'
[WARNING] Parameter 'jgit.dirtyWorkingTree' is unknown for plugin 'tycho-packaging-plugin:2.7.5:validate-id (default-validate-id)'
[WARNING] Parameter 'jgit.ignore' is unknown for plugin 'tycho-packaging-plugin:2.7.5:validate-id (default-validate-id)'
[WARNING] Parameter 'jgit.dirtyWorkingTree' is unknown for plugin 'tycho-packaging-plugin:2.7.5:validate-version (default-validate-version)'
[WARNING] Parameter 'jgit.ignore' is unknown for plugin 'tycho-packaging-plugin:2.7.5:validate-version (default-validate-version)'
[WARNING] Parameter 'jgit.dirtyWorkingTree' is unknown for plugin 'tycho-packaging-plugin:2.7.5:update-consumer-pom (default-update-consumer-pom)'
[WARNING] Parameter 'jgit.ignore' is unknown for plugin 'tycho-packaging-plugin:2.7.5:update-consumer-pom (default-update-consumer-pom)'
[WARNING] Parameter 'jgit.dirtyWorkingTree' is unknown for plugin 'tycho-packaging-plugin:2.7.5:package-plugin (default-package-plugin)'
[WARNING] Parameter 'jgit.ignore' is unknown for plugin 'tycho-packaging-plugin:2.7.5:package-plugin (default-package-plugin)'
```
To reproduce, any configuration block like in the example here will be sufficient: https://wiki.eclipse.org/Tycho/Reproducible_Version_Qualifiers
I'm not sure where exactly the warning is raised, and whether there is something to disable this new feature.

**Comment by laeubi** [comment]
Tycho currently not support maven 3.9x
Also as jgit is an extension, we can't effectively declare its parameters here, I have already evaluated some alternatives but have not yet had the time to work on it.

**Comment by laeubi** [comment]
See also:
- https://github.com/eclipse-tycho/tycho/pull/2084

**Comment by Bananeweizen** [comment]
Honestly, does the jgit timestamp provider really have to be an extension of the default provider? Can't we make that 2 alternative implementations, and let people user either default or jgit? That way both could have their own configs, people would not be confused with dependencies, the POM would look much cleaner. And since 4.0 is a breaking change anyway, this would be fine to do now.
Code sharing between them would be as simple as before, given they live in the same repo.
