### ISSUE TITLE
Tycho docs typo "plkugin"

### ISSUE THREAD

**Issue by kjsmita6** [eclipse-tycho/tycho#2082]
<img width="1792" alt="Screenshot 2023-02-09 at 9 18 53 PM" src="https://user-images.githubusercontent.com/9405706/217983892-96e8626f-8202-403d-bd76-602fe1740a24.png">

**Comment by laeubi** [comment]
Don't hesitate to open a PR: https://github.com/eclipse-tycho/tycho/blob/tycho-3.0.x/src/site/site.xml :-)

**Comment by kjsmita6** [comment]
So I have to fork the repo, make the change, open a PR, and wait for it to
get accepted, just to change a few letters? While the whole time you
could've just pressed the edit button on that page you linked and been done
with it in about 5 seconds? It's like being on the couch and asking someone
on a different floor to bring you something that's on the coffee table.

Considering this is a VERY obvious typo on the front page of the docs
(which everyone looking up anything relating to Tycho would see) I would've
thought it's important enough that you could've just fixed it.

**Comment by laeubi** [comment]
You just need to click the edit button as well (github will do the fork if required), and afterwards github even suggest you to open the PR so with just a few clicks you can fix it (we usually merge documentation changes right away), in contrast you have:

1. Take a screenshot
2. Mark the typo
3. Insert in a new issue and enter a title
4. Wait for someone to take this up and fix it.

So it is more like

> If you give a man a fish, you feed him for a day. If you teach a man to fish, you feed him for a lifetime.

So this will empower you for future contributions and even if I can probably "just fix that" such trivial changes are a great way to start, maybe you even not want to change a typo but suggest some other doc enhancements later on, then you are all set and familiar with the process.

**Comment by laeubi** [comment]
Also now published in the docs: https://tycho.eclipseprojects.io/doc/3.0.2/index.html
