### ISSUE TITLE
Tycho 2.7.4 produces "tycho-specific" poms

### ISSUE THREAD

**Issue by Kellindil** [eclipse-tycho/tycho#2177]
Hello,

I have two successive builds, the first uses tycho to compile eclipse plugins and features through "clean install", the second uses the local artifacts built by this first build in a pure maven environment (no tycho plugins involved).

What I see for the dependency resolution of the second build, if the "mvn clean install" was done with tycho 2.6.0, is the following:

```
[DEBUG] group.id:artifact1.id:jar:1.0.2-SNAPSHOT
[DEBUG]    group.id:artifact2.id:jar:1.0.2-SNAPSHOT:compile
[DEBUG]    group.id:artifact3.id:jar:1.0.2-SNAPSHOT:compile
[DEBUG]    group.id:artifact4.id:jar:1.0.2-SNAPSHOT:compile
```

These dependencies I define myself in the poms of my project. This is what I expect. However, if I've built my first project using tycho 2.7.4, I'm seeing the following instead:

```
[DEBUG] group.id:artifact1.id:jar:1.0.2-SNAPSHOT
[DEBUG]    group.id:artifact2.id:jar:1.0.2-SNAPSHOT:compile
[DEBUG]    group.id:artifact3.id:jar:1.0.2-SNAPSHOT:compile
[DEBUG]      group.id:artifact4.id:eclipse-plugin:1.0.2-SNAPSHOT:compile
[DEBUG]    group.id:artifact4.id:jar:1.0.2-SNAPSHOT:compile
```

Tycho 2.7.4 has inserted a "eclipse-plugin" typed dependency in there, which a pure maven build cannot resolve (it will simply fail with ` Could not resolve dependencies for project group.id:artifact1.id:jar:1.0.2-SNAPSHOT: Failure to find group.id:artifact4.id:eclipse-plugin:1.0.2-SNAPSHOT in [redacted maven repo] was cached in the local repository, resolution will not be reattempted until the update interval of gitlab-maven has elapsed or updates are forced`). I had an extremely hard time debugging from that error message up to the pom tycho has generated for my artifact.

The built artifact now somehow contains "<dependency>" entries for every single dependency of my plugin, and all of them are "eclipse-plugin" typed :
```
<dependency>
      <groupId>group.id</groupId>
      <artifactId>artifact4.id</artifactId>
      <version>1.0.2-SNAPSHOT</version>
      <type>eclipse-plugin</type>
      <scope>compile</scope>
      <optional>false</optional>
    </dependency>
```

This cannot work and should not be the default, or at least a warning should be issues about this somehow to ease debugging. There is nothing I could find in the release notes about it either. How can I prevent tycho from messing up the poms?

**Comment by laeubi** [comment]
Please upgrade to a more recent Tycho version which has additional configuration options for this. 

For 2.7.x the only option is disabling pom generation:
https://tycho.eclipseprojects.io/doc/2.7.5/tycho-packaging-plugin/update-consumer-pom-mojo.html#skipPomGeneration

**Comment by Kellindil** [comment]
Thanks Christoph, skipPomGeneration did the trick. I believe this undocumented option should be better highlighted since this basically makes anything built by tycho incompatible with maven.

**Comment by laeubi** [comment]
> this basically makes anything built by tycho incompatible with maven.

This depends on your configuration and has already improved in 3.x and 4.x, but if you want you can still suggest a change for the release notes or any other documentation.

**Comment by Kellindil** [comment]
Well the only "configuration" I can think of that would have this work is to add the tycho-maven-plugin to the pom of my maven build, which kinda defeats the purpose :). I can't think of any other way for a maven build to understand what this `*:eclipse-plugin:*` typed artifact could be

**Comment by laeubi** [comment]
Tycho *is* a maven build... and not all configurations include the consumer pom, and as you said including the tycho-maven-plugin (with nothing else) will also make the mappings available.

Also please note that there is `2.7.5` version and even `3.0.3` already ...

**Comment by Kellindil** [comment]
2.7.5 had the same issue, and I cannot switch to 3.x or higher for now.
