### ISSUE TITLE
Tycho doesn't resolve org.junit dependencies

### ISSUE THREAD

**Issue by georgebax** [eclipse-tycho/tycho#2268]
I upgraded from tycho 1.7.0 to 2.7.5, and my project isn't building anymore, failing in the test-compile phase:
```
[DEBUG] Original compiler output: ----------
1. ERROR in /Users/.../ValidatorTest.java (at line 3)
	import static org.junit.jupiter.api.Assertions.assertFalse;
	              ^^^^^^^^^
The import org.junit cannot be resolved
----------
2. ERROR in /Users/.../ValidatorTest.java (at line 4)
	import static org.junit.jupiter.api.Assertions.assertTrue;
	              ^^^^^^^^^
The import org.junit cannot be resolved
...
``` 
The only change is the tycho version, and the junit bundles exist in the target platform in my IDE. 
![image](https://user-images.githubusercontent.com/19195396/226581790-d435b0a0-8e43-45da-aef9-4a10f12212ca.png)

**Comment by laeubi** [comment]
please note that the current latest release is Tycho `3.0.4` and usually it helps to provide a small example or even better provide an [integration-test](https://github.com/eclipse/tycho/wiki#providing-an-integration-test) to demonstrate the issue.

**Comment by georgebax** [comment]
The project is building with tycho 2.4.0, and the problem starts appearing in 2.5.0. 
I will try to provide a small example, but for now I can say with certainty that 2.5.0 is the version that introduces the problem. Also, we can't use 3.0.0+ because we have to use Java 11 for our project.

**Comment by laeubi** [comment]
You can use Tycho 3 to build Java 11 projects as well, it only needs Java 17 to run.
