### ISSUE TITLE
Regression: tycho-versions-plugin:set-version -Dproperties is sometimes "ignored" if using relative paths in "mvn --file"

### ISSUE THREAD

**Issue by sewe** [eclipse-tycho/tycho#2284]
I am currently facing a really weird regression in the `tycho-versions-plugin` when updating from 3.0.3 to 3.0.4 (and using Maven 3.8.6).

When I run the following command line on the large multi-module build of an internal project (whose `pom.xml` I unfortunately cannot share) ...

```
./mvnw --errors \
  -f /home/sewe/Development/gitlab.com/cqse/teamscale/teamscale/../teamscale/master/ide/../ide/eclipse \
  clean \
  org.eclipse.tycho:tycho-versions-plugin:set-version -DnewVersion=8.7.0-SNAPSHOT -Dproperties=teamscaleVersion
```

... then I get the following output:

```
INFO] -----------------------< com.teamscale:eclipse >------------------------
[INFO] Building Teamscale Integration for Eclipse 0.0.1-SNAPSHOT        [16/15]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO] 
[INFO] --- tycho-versions-plugin:3.0.4:set-version (default-cli) @ eclipse ---
[INFO] Making changes in /home/sewe/Development/gitlab.com/cqse/teamscale/teamscale/master/.gitlab/ci/../../ide/eclipse
[INFO]   pom.xml//project/properties/[ teamscaleVersion ] 0.0.1-SNAPSHOT => 8.7.0-SNAPSHOT
[INFO]   pom.xml//project/version: 0.0.1-SNAPSHOT => 8.7.0-SNAPSHOT
...
[INFO] Making changes in /home/sewe/Development/gitlab.com/cqse/teamscale/teamscale/master/ide/eclipse
[INFO]   pom.xml//project/version: 0.0.1-SNAPSHOT => 8.7.0-SNAPSHOT
...
```

In other words, the `pom.xml` in `ide/eclipse` is written to **twice**, once with setting the `teamscaleVersion` property and once without. Depending on which of these writes happens first, I end up with different results in the updated `pom.xml`s.

To make matters even more confusing, the order of the two writes seems to depend on the exact path passed to `mvn` via the `-f` option. 

AFAICT, the `pom.xml` is written to only once in the following cases:

- When using `tycho-versions-plugin` 3.0.3 (i.e., this is a regression)
- When not using relative paths in the `-f` option of the `mvn` invocation.

I hope that this is enough to help you debug the issue, even without an reproducer.

**Comment by laeubi** [comment]
@sewe  we plan a 3.0.5 bufix release so if you want to provide an [integration-test](https://github.com/eclipse/tycho/wiki#providing-an-integration-test) to demonstrate the issue and probably a fix it might can be included.

**Comment by sewe** [comment]
FYI, I don't see this behaviour in Tycho 4.0.9 anymore, so as far as I am concerned, this bug can be closed.
