### ISSUE TITLE
Tycho is fetching multiple copies of a dependency.

### ISSUE THREAD

**Issue by djreilly356** [eclipse-tycho/tycho#2286]
The doc says that it will accept the first repository that indicates that it can fulfill a requirement. What I am seeing is that it keeps looking and fetching until it ALWAYS gets the wrong copy of the plugin. I have a development copy of a plugin in one repository and a production copy in another. How do I get this thing to load the development copy?

**Comment by laeubi** [comment]
> The doc says that it will accept the first repository that indicates that it can fulfill a requirement. 

Can you give a link to that documentation? It might be outdated!

> What I am seeing is that it keeps looking and fetching until it ALWAYS gets the wrong copy of the plugin

Please give an example or provide an [integration-test](https://github.com/eclipse/tycho/wiki#providing-an-integration-test) to demonstrate the issue so we can see what "wrong" means.

> I have a development copy of a plugin in one repository and a production copy in another. How do I get this thing to load the development copy?

This heavily depends on your setup and what you intend to archive.

**Comment by djreilly356** [comment]
I figured out what the problem is. Closing this one.

**Comment by djreilly356** [comment]
closing

**Comment by laeubi** [comment]
> I figured out what the problem is. Closing this one.

Do you want to share your findings so others might can benefit from this later on?
