### ISSUE TITLE
Tycho 3.x.x doesn't resolve Composite P2 repository in the same way as Tycho 2.5.x

### ISSUE THREAD

**Issue by BenShelbourne** [eclipse-tycho/tycho#2331]
We are in the process of migrating from Tycho 2.5.0 -> 3.0.4 (latest). The problem we are seeing is that we use an internal composite p2 repository which contains other internal p2 repositories. By adding this as a `<repository>` we were able to access everything in the composite repository and all sub-repositories but now Tycho 3 requires authentication for each sub-repository inside the composite repository. We don't want to have to repeat the same authentication details with different ID's for each sub-repository so how can we get the same behaviour seen in 2.5.0, in 3.0.4 ?

**Comment by laeubi** [comment]
Can you explain the structure of your repo/subrepository?

Usually it should work to only use the "shortest path" as an ID to reuse the authentication for other repositories.

**Comment by laeubi** [comment]
So are they all form the same base url and is this base url configured with the credentials?

We have https://github.com/eclipse-tycho/tycho/blob/master/tycho-its/src/test/java/org/eclipse/tycho/test/target/PasswordProtectedM2RepositoryTest.java testcase, maybe you can enhance it to reproduce the issue you see?

**Comment by BenShelbourne** [comment]
So the url for each sub-repository is `<internal-composite-repository-url>/packages/package-A`. The `compositeArtifacts.xml` and `compositeContent.xml` in the bundle points to them via a relative path like so:
```
<?xml version='1.0' encoding='UTF-8'?>
<?compositeArtifactRepository version='1.0.0'?>
<repository name='Composite Repository'
    type='org.eclipse.equinox.internal.p2.artifact.repository.CompositeArtifactRepository' version='1.0.0'>
  <properties size='2'>
    <property name='p2.timestamp' value='1668781002'/>
    <property name='p2.atomic.composite.loading' value='false'/>
  </properties>
  <children size='3'>
    <child location='../../packages/package-A'/>
    <child location='../../packages/package-B'/>
    <child location='../../packages/package-Z'/>
  </children>
</repository>
```
We have the credentials for the bundles in our `settings.xml` but the credentials are the same for all repositories. I can take a look at the tescases. Do you know if anything might have changed from Tycho 2.5.0 until now regarding how you resolve composite repositories? I appreciate 2.5.0 is an *old* version!

**Comment by laeubi** [comment]
You should check if you have configured it for the host not for the site, e.g. assume your server is:

`http://internal-composite-repository-url/packages/package-A`

you should have a setting with user/password for

`http://internal-composite-repository-url/`

> Do you know if anything might have changed from Tycho 2.5.0 until now regarding how you resolve composite repositories? 

previously we used the P2 authentication that only uses the host name (what ever you specify) now we use a more fine grained approach, but its hard to tell without an real example.

Beside that, if it is crucial to your business you can find dedicated support options for Tycho here (e.g. to sign an NDA and share the real code/config):
https://github.com/eclipse-tycho/tycho#getting-support

**Comment by BenShelbourne** [comment]
I appreciate it's not much to go on so thank you for your help! I will ask people who are can make those decisions if we can go down this route.

If I change the POM so the url is `internal-composite-repository-url/` then it fails with `No repository found at <internal-composite-repository-url>` as there is no p2 metadata in that directory, it's only in `bundles/1.0.0` and `packages/package-x`. I should also add that it's a "silent failure" in the sense that it fails to resolve the target platform later in the build as there a missing plugins in the `packages` directory that it isn't able to resolve but it doesn't actually fail the build not being able to access the sub-repository. The "silent" error is

```
org.eclipse.equinox.p2.core.ProvisionException: Unable to read repository at https://internal-composite-repository-url/packages/package-A.
```

Does Tycho 3 still support Composite P2 repositories or do we need to change this?

**Comment by laeubi** [comment]
Do not change the URL of the repository but the url used for the authentication, I assume somewhere in your `settings.xml`

**Comment by BenShelbourne** [comment]
Sorry I'm not sure this makes sense. In `settings.xml` one has a block such as:
```
<server>
<id>some-id</id>
<username>my-username</username>
<password>my-password</password>
</server>
```

and then in the `pom.xml`:
```
<repository>
<id>some-id</id>
<url>internal-composite-repository-url</url>
</repository>
```

So you can't define a url directly in the `settings.xml` and so the only place we can change it to the base url is in the repository tag and as previously mentioned, that doesn't work.

**Comment by laeubi** [comment]
@BenShelbourne can you try out to use the server base url (e.g. `https://my.company.server.test`) in the settings.xml instead of the id of the repository?

**Comment by BenShelbourne** [comment]
There is nowhere to put a url in the `settings.xml`. That isn't supported. I'm not sure what you're asking me to do?

**Comment by BenShelbourne** [comment]
Hi, sorry I haven't had chance to look at this for a while. Since then, I have discovered where this new behaviour has been introduced https://github.com/eclipse-tycho/tycho/commit/b1b992c877026f9d0903f58011835d7dc4996559 when adding the new Tycho transport. Specifically, these 2 lines are what is needed for our project to resolve the composite p2 repo.

```
RemoteAgent.java:96-98
            // cache indices of p2 repositories in the local Maven repository
            RemoteRepositoryCacheManager cacheMgr = new RemoteRepositoryCacheManager(transport, mavenContext);
            agent.registerService(CacheManager.class, cacheMgr);
```

This class no longer exists in the latest version of Tycho. I'm wondering how these 2 lines worked and if the same logic has been applied in the new Tycho transport? Does it still cache indices of the p2 repository as the comment suggests it used to? If not, what is the expected use of a composite p2 repository that is hosted on an internal server requiring authentication? Currently, we see errors in Tycho 3.0.x unable to authenticate each of the indices of the composite p2 repo.

Any help here is greatly appreciated!

**Comment by laeubi** [comment]
Tycho caches any file requestd (including index) while P2 does not cache index files. The failure is because P2 saves authentication only on a host basis (that means every request is using the same credentials) but this is potential security risk.  e.g. in your example you provide credentials for `http://myhost/bundles/1.0.0` but try to access `http://myhost/packages/package-A` in the composite, if this is a shared host you probably would (accidentally) disclose your credentials to another user if "bundles" and "packages" where different user accounts/vhosts.


Therefore Tycho is now more strict with matching credentials, some idea how to solve it but without a public example or an [integration-test](https://github.com/eclipse/tycho/wiki#providing-an-integration-test) to demonstrate the issue, its hard to tell if such fix would help.

**Comment by BenShelbourne** [comment]
I've added a quick test to show the structure we're using and it fails with the same exception so hopefully is a good enough reproducer. https://github.com/eclipse-tycho/tycho/pull/2552
