### ISSUE TITLE
Regression in Tycho 3.x.x, tycho surefire parameters are ignored

### ISSUE THREAD

**Issue by jstroleny** [eclipse-tycho/tycho#2348]
Hello,

recently I've tried to update to the tycho version 3.x.x from 2.7.5, but I found that some of surefire parameters
seems to be ignored. (https://tycho.eclipseprojects.io/doc/latest/tycho-surefire-plugin/test-mojo.html)

I've tried to reproduce it on following example project: https://github.com/vogellacompany/tycho-example
and it is reproducible, just put following snippet into root `pom.xml` and run `./mvn verify `to execute tests which
are producing output to stdout (e.g. `com.vogella.tycho.rcp.tests.TweetClientTest`). 
Run it on tycho 2.7.5 and on tycho 3.0.0 (or 3.0.4). 
In previous version, the output is redirected correctly to the file and not shown on stdout.
Seems that parameter `showEclipseLog` is ignored as well (installation location is not shown as well on stdout).

 ```
<plugin>
        <groupId>org.eclipse.tycho</groupId>
        <artifactId>tycho-surefire-plugin</artifactId>
        <version>${tycho.version}</version>
        <configuration>
          <enableAssertions>true</enableAssertions>
          <showEclipseLog>true</showEclipseLog>
          <redirectTestOutputToFile>true</redirectTestOutputToFile>
        </configuration>
</plugin>
```

**Comment by laeubi** [comment]
@jstroleny we plan a 3.0.5 bufix release so if you want to provide an [integration-test](https://github.com/eclipse/tycho/wiki#providing-an-integration-test) to demonstrate the issue and probably a fix it might can be included.

**Comment by laeubi** [comment]
The provided fix is merged and will soon show up in the [tycho snapshot](https://github.com/eclipse/tycho/wiki#getting-tycho-snapshots) build, please verify that this fixes the issue you see.
