### ISSUE TITLE
Error authenticating to connect to P2 repo on S3/Cloudfront after upgrade

### ISSUE THREAD

**Issue by castortech** [eclipse-tycho/tycho#2349]
Just upgraded from 1.6.0 to 3.0.4 and now I am getting the following errors:

[INFO] Resolving target definition file:/data/jenkins/workspace/iriscommon-3.0/com.castortech.iris.common.target/iriscommon-target.target for environments=[win32/win32/x86_64, linux/gtk/x86_64, macosx/cocoa/x86_64], include source mode=honor, execution environment=StandardEEResolutionHints [executionEnvironment=OSGi profile 'JavaSE-11' { source level: 11, target level: 11}], remote p2 repository options=org.eclipse.tycho.p2.remote.RemoteAgent@507187c1...
[WARNING] Request to https://xxxxxxxxxxxx.cloudfront.net/targets/2021-09/p2.index failed, trying cache instead...
...many more similar warnings
[ERROR] Failed to resolve target definition file:/data/jenkins/workspace/iriscommon-3.0/com.castortech.iris.common.target/iriscommon-target.target: Failed to load p2 metadata repository from location https://xxxxxxxxxxx.cloudfront.net/passay-1.3.0/: Unable to read repository at https://d29rul8e3oj83q.cloudfront.net/passay-1.3.0. Server returned HTTP response code: 403 for URL: https://xxxxxxxxxxxxxx.cloudfront.net/passay-1.3.0/content.jar -> [Help 1]

I tried, unsuccessfully to switch back to ecf, but it doesn't seem to take:
[EnvInject] - Injecting environment variables from a build step.
[EnvInject] - Injecting as environment variables the properties content 
tycho.p2.transport=ecf

[EnvInject] - Variables injected successfully.
[iriscommon-3.0] $ /var/lib/jenkins/tools/hudson.tasks.Maven_MavenInstallation/maven-3.6.3/bin/mvn clean package
...scanning projects
[INFO] ### Using TychoRepositoryTransport for remote P2 access ###
[INFO]     Cache location:         /var/lib/jenkins/.m2/repository/.cache/tycho
[INFO]     Transport mode:         online
[INFO]     Update mode:            cache first
[INFO]     Minimum cache duration: 60 minutes
[INFO]       (you can configure this with -Dtycho.p2.transport.min-cache-minutes=<desired minimum cache duration>)

Has anything changed in regards to resolving credentials ? I inherited this setup and I am not fully sure about all the moving parts and have put off for the longest time upgrading, but now facing an issue with APT that is forcing me to do so and want to also avail ourselves of some neat new Tycho features :)

Thanks
Alain

**Comment by laeubi** [comment]
You are probably seeing this problem here:

- https://github.com/eclipse-tycho/tycho/issues/2331

But sadly currently there is no reproducing [integration-test](https://github.com/eclipse/tycho/wiki#providing-an-integration-test) to demonstrate the issue, so if you can provide one this will help looking into this issue.

**Comment by castortech** [comment]
I downloaded the repo and I can't see any reference to tycho.p2.transport being used and it only appears in the release notes.

I then downgraded to 3.0.0 and got the same issue. Finally I downgraded to 2.7.5 and the issue went away. Seems to be a potential regression with the release of v3.

**Comment by castortech** [comment]
> You are probably seeing this problem here:
> 
>     * [Tycho 3.x.x doesn't resolve Composite P2 repository in the same way as Tycho 2.5.x #2331](https://github.com/eclipse-tycho/tycho/issues/2331)
> 
Sorry I missed your reply, should have refreshed first.

We are not using composite, but what we have in our case is that Tycho is resolving a platform target, and AFAICT it probably uses the target name to resolve the server entry in the settings.xml (would make sense from the list that I see).

Then in the target the location points to a repository like:
`<location includeAllPlatforms="true" includeConfigurePhase="true" includeMode="slicer" includeSource="true" type="InstallableUnit">
<unit id="org.eclipse.jdt.feature.group" version="3.18.900.v20210906-0500"/>
<unit id="org.eclipse.jdt.source.feature.group" version="3.18.900.v20210906-0500"/>
<unit id="org.eclipse.pde.feature.group" version="3.14.900.v20210906-0500"/>
<unit id="org.eclipse.pde.source.feature.group" version="3.14.900.v20210906-0500"/>
<repository id="iris" location="https://xxxxxxxxxxx.cloudfront.net/targets/2021-09/"/>
</location>
`
Each of the location point to a standard non-composite p2 repository
`
aws s3 ls s3://irisba-dev/targets/2021-09/
                           PRE .blobstore/
                           PRE binary/
                           PRE features/
                           PRE plugins/
2021-10-10 06:08:03     859580 artifacts.jar
2021-10-10 06:08:07    2898816 content.jar
`
I think you might be more able to tell if the translates into the same issue or not.

Thanks

**Comment by castortech** [comment]
> We are not using composite, but what we have in our case is that Tycho is resolving a platform target, and AFAICT it probably uses the target name or repository name to resolve the server entry in the settings.xml (would make sense from the list that I see).
> 

Old Tycho shows:
[DEBUG] Setting credentials for p2 repository 'iris'

so that would confirm the use of the repository name from the target location/repository

**Comment by laeubi** [comment]
@castortech the main issue is that we have no test that shows this problem, so if you can provide an [integration-test](https://github.com/eclipse/tycho/wiki#providing-an-integration-test) to demonstrate the issue it would be great, we have one that covers password protected repositories but seem to not cover this case:

https://github.com/eclipse-tycho/tycho/blob/master/tycho-its/src/test/java/org/eclipse/tycho/test/target/PasswordProtectedP2RepositoryTest.java

**Comment by castortech** [comment]
I have now determine the cause of the issue but not how to address it. I ran maven in debug mode and I am getting an error since it can't find the secure storage provider.

In org.eclipse.equinox.internal.security.storage.PasswordProviderSelector#findStorageModule it is looking for module: org.eclipse.equinox.security.windowspasswordprovider64bit but the only registered extension point is for the org.eclipse.tycho.noopsecurity.id1.

I tried a few things to expose the org.eclipse.equinox.security.win32.x86_64 but I feel I don't understand how to do that. Have the feeling that it somehow is related to sisu, but that is all things that I'm not familiar with. But obviously we need a way for maven/tycho to make this extension point available so that the registry can find it and loaded when required.

Looking for your help to go further.

Alain

**Comment by laeubi** [comment]
Why do you think you need the windows passowrdprovider? This is not how Tycho works here...

**Comment by castortech** [comment]
Because that is what the debugging shows :)

In P2PasswordUtil#setCredentials it will retrieve the prefNode from the Equinox ISecurePreferences via:
prefNode.get(IRepository.PROP_USERNAME, username) and prefNode.get(IRepository.PROP_PASSWORD, password) which will call SecurePreferences#get which retrieves the moduleId from the encryptedValue which is: org.eclipse.equinox.security.windowspasswordprovider64bit

**Comment by castortech** [comment]
This is a password protected P2 repository and based on the URL Equinox secure storage finds an entry for the credentials that is mapped to a password provider, here being the windowspasswordprovider64bit.

It surely wouldn't be the windowspasswordprovider64bit when running in production in Linux, but during debug this is where it is stored.

**Comment by laeubi** [comment]
As said Tycho never has used `windowspasswordprovider64bit` because it reads the credentials from the maven config and store them using `noopsecurity` ... so even though it is not impossible to use `windowspasswordprovider64bit` (or any other provider) with Tycho it is usually not what you want and most likely will fail your CI-Build (unless it runs on the same user on the same machine).

**Comment by castortech** [comment]
I am trying to debug another issue so I am running in my environment.

Finally I found no other way than to delete the secure storage file (after taking a backup) and that sidestepped this issue. Maybe a good thing to know for the future or to document somewhere.

Thanks
