### ISSUE TITLE
On the issue of missing Requirement Bundle

### ISSUE THREAD

**Issue by dongchen1221** [eclipse-tycho/tycho#2365]
### Discussed in https://github.com/eclipse-tycho/tycho/discussions/2364

<div type='discussions-op-text'>

<sup>Originally posted by **dongchen1221** April 25, 2023</sup>
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:2.7.5:validate-classpath (default-validate-classpath) on project com.nucleisys.ide: Execution default-validate-classpath of goal org.eclipse.tycho:tycho-compiler-plugin:2.7.5:validate-classpath failed: org.osgi.framework.BundleException: Bundle com.nucleisys.ide cannot be resolved:com.nucleisys.ide [42]
[ERROR]   Unresolved requirement: Require-Bundle: org.eclipse.ui
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:2.7.5:validate-classpath (default-validate-classpath) on project com.nucleisys.ide: Execution default-validate-classpath of goal org.eclipse.tycho:tycho-compiler-plugin:2.7.5:validate-classpath failed: org.osgi.framework.BundleException: Bundle com.nucleisys.ide cannot be resolved:com.nucleisys.ide [42]
  Unresolved requirement: Require-Bundle: org.eclipse.ui

	<repositories>	
		<repository>
		  <id>license-feature</id>
		  <url>https://download.eclipse.org/tools/cdt/releases/9.10</url>
		  <layout>p2</layout>
		</repository>
		<repository>
		  <id>license-feature1</id>
		  <url>https://download.eclipse.org/embed-cdt/releases/5.1.1/p2/</url>
		  <layout>p2</layout>
		</repository>
	</repositories>	

Why is this situation happening? If it's a problem with the target platform, but you can find org.eclipse.ui in my target platform status view？
</div>

**Comment by laeubi** [comment]
Please keep this in the discussions instead of reopen an equivalent issue unless it is clear there is an issue to solve at Tycho.
