### ISSUE TITLE
Create a installer button to instantly start coding

### ISSUE THREAD

**Issue by laeubi** [eclipse-tycho/tycho#24]
Like with eclipse-m2e/m2e-core#120 but as we already have a setup file maybe just some additional wiring is required?

**Comment by laeubi** [comment]
@HannesWell if I remeber correctly you have done this for m2e already, do you think you can propose such a button for Tycho as well?

Here is a "clone into eclipse" button but it points to @mickaelistria repository (can we adjust this to use the tycho gh pages now?):

https://github.com/eclipse-tycho/tycho/blob/master/CONTRIBUTING.md

but m2e seems to have d dedicated button for the setup as well.

**Comment by mickaelistria** [comment]
> Here is a "clone into eclipse" button but it points to @mickaelistria repository

You'll need a proxy as GitHub doesn't allow non-https links. My repo is the proxy that just does a redirect. You can put this proxy someplace else, but I don't know what you'd gain from it.

**Comment by HannesWell** [comment]
> @HannesWell if I remeber correctly you have done this for m2e already, do you think you can propose such a button for Tycho as well?

Here we go: https://github.com/eclipse-tycho/tycho/pull/1459 :)
