### ISSUE TITLE
Pomless build with tycho 2.7.5 does not work with other tools

### ISSUE THREAD

**Issue by jan-pesta** [eclipse-tycho/tycho#2401]
I am migrating to newer tycho 2.7.5 from 1.4.0. 

I just find out that sonar analysis are not working with new extension.
When version on has been used, it generate following Source paths:
`[INFO] 02:42:40.417 Source paths: .polyglot.build.properties, src`
With version 2.7.5 it is generating 
`[INFO] 02:42:21.902 Source paths: .polyglot.META-INF`

In case of multiple source folders, the older version is correctly providing all source folders listed.

I am not able to test it with 3.x line as it is forcing to use newer java that 11, but it looks like is generating same Source paths as 2.7.5.

**Comment by jan-pesta** [comment]
When I just now retried with 1.4.0 again, I got following source files:
`[INFO] 10:16:36.413 Source paths: .polyglot.META-INF, src`

**Comment by jan-pesta** [comment]
I just find out that there is no class path resolution when running sonar analysis. 

Is there a way to force classpath resolution to be executed also when direct goal sonar:sonar is executed?

Seems this to be side effect of #460 .

**Comment by laeubi** [comment]
> Is there a way to force classpath resolution to be executed also when direct goal sonar:sonar is executed?

You can open a bug to the sonar-lint plugin that it does not require any classpath, beside that Tycho 4 has an option `-Dtycho.target.eager=true` to perform target platform resolution before any other plugin running.

**Comment by laeubi** [comment]
Can you provide an [integration-test](https://github.com/eclipse/tycho/wiki#providing-an-integration-test) to demonstrate the issue?

**Comment by jan-pesta** [comment]
I think important information was that classpath resolution has been refactored into compile time. I have solved the problem when I put sonar into one build with compilation.

so solution was to start `mvn clean install sonar:sonar` together, and issue is solved.

previously I have two mvn runs.
