### ISSUE TITLE
Maven 3.9.2 warns about using maven-compat

### ISSUE THREAD

**Issue by Bananeweizen** [eclipse-tycho/tycho#2402]
`mvn help:help -Dtycho.mode=maven` on a project using Tycho with Maven 3.9.2 produces this output for every tycho plugin:

```
[WARNING]  * org.eclipse.tycho:tycho-source-plugin:3.0.4
[WARNING]   Plugin issue(s):
[WARNING]    * Plugin depends on the deprecated Maven 2.x compatibility layer, which may not be supported in Maven 4.x
```
See https://issues.apache.org/jira/browse/MNG-7712 for the root cause. The expectation of the Maven core developer is that the maven-compat dependency shall be removed.

**Comment by akurtakov** [comment]
Please try with 4.0.0-SNAPSHOT. https://github.com/eclipse-tycho/tycho/commit/e619f250709e0fe73253dbe078ae152c5d8c6a12 makes maven-compat test only dependency.

**Comment by Bananeweizen** [comment]
Looks good. Thanks.
