### ISSUE TITLE
Fix for broken JDT null-analysis in tycho 3.x

### ISSUE THREAD

**Issue by cdietrich** [eclipse-tycho/tycho#2441]
Hi,

it would be nice to have a Tycho 3.x version with the final JDT 2023-06 artifacts with the fix for https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1007 as the problem is also visible in tycho as https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1093 demonstrates.

If a new 3.x version is not possible: is it possible to overide the jdt/ecj version the tycho compiler plugin uses?

**Comment by laeubi** [comment]
As soon as it is promoted to **Maven Central (!)** both is possible.

Custom compiler configuration:
```
<plugin>
  <groupId>org.eclipse.tycho</groupId>
  <artifactId>tycho-compiler-plugin</artifactId>
  <version>${tycho-version}</version>
  <dependencies>
    <dependency>
      <groupId>org.eclipse.jdt</groupId>
      <artifactId>ecj</artifactId>
      <version><yournewversion></version>
    </dependency>
  </dependencies>
</plugin>
```

**Comment by cdietrich** [comment]
nice.

i tested with

```
				<dependencies>
					<dependency>
						<groupId>org.eclipse.jdt</groupId>
						<artifactId>ecj</artifactId>
						<version>3.34.0-SNAPSHOT</version>
					</dependency>
				</dependencies>
```

```
	<pluginRepositories>
		<pluginRepository>
			<id>eclipse-snapshots</id>
			<url>https://repo.eclipse.org/content/groups/eclipse/</url>
			<releases>
				<enabled>false</enabled>
			</releases>
			<snapshots>
				<enabled>true</enabled>
			</snapshots>
		</pluginRepository>
	</pluginRepositories>
```

and the problem seems to be gone. thx

**Comment by laeubi** [comment]
@cdietrich I'll close this for now as release is on central and it seems you got a solution.
