### ISSUE TITLE
Cannot build tycho-its

### ISSUE THREAD

**Issue by vogella** [eclipse-tycho/tycho#246]
Running mvn clean verify in ~/git/tycho/tycho-its results in the following error:

[ERROR] Failed to execute goal on project tycho-its: Could not resolve dependencies for project org.eclipse.tycho:tycho-its:jar:2.5.0-SNAPSHOT: The following artifacts could not be resolved: org.eclipse.tycho:tycho-testing-harness:jar:2.5.0-SNAPSHOT, org.eclipse.tycho:tycho-core:jar:2.5.0-SNAPSHOT, org.eclipse.tycho:tycho-maven-plugin:jar:2.5.0-SNAPSHOT, org.eclipse.tycho:tycho-pomgenerator-plugin:jar:2.5.0-SNAPSHOT, org.eclipse.tycho:tycho-compiler-plugin:jar:2.5.0-SNAPSHOT, org.eclipse.tycho:tycho-packaging-plugin:jar:2.5.0-SNAPSHOT, org.eclipse.tycho:tycho-surefire-plugin:jar:2.5.0-SNAPSHOT, org.eclipse.tycho:tycho-source-plugin:jar:2.5.0-SNAPSHOT, org.eclipse.tycho:tycho-p2-plugin:jar:2.5.0-SNAPSHOT, org.eclipse.tycho:tycho-p2-publisher-plugin:jar:2.5.0-SNAPSHOT, org.eclipse.tycho:tycho-p2-repository-plugin:jar:2.5.0-SNAPSHOT, org.eclipse.tycho:tycho-p2-director-plugin:jar:2.5.0-SNAPSHOT, org.eclipse.tycho:target-platform-configuration:jar:2.5.0-SNAPSHOT, org.eclipse.tycho:tycho:pom:2.5.0-SNAPSHOT, org.eclipse.tycho:tycho-bundles-external:zip:2.5.0-SNAPSHOT, org.eclipse.tycho:org.eclipse.tycho.p2.resolver.shared:jar:2.5.0-SNAPSHOT, org.eclipse.tycho:org.eclipse.tycho.p2.resolver.impl:jar:2.5.0-SNAPSHOT, org.eclipse.tycho:org.eclipse.tycho.p2.maven.repository:jar:2.5.0-SNAPSHOT, org.eclipse.tycho:org.eclipse.tycho.p2.tools.impl:jar:2.5.0-SNAPSHOT: Could not find artifact org.eclipse.tycho:tycho-testing-harness:jar:2.5.0-SNAPSHOT -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by laeubi** [comment]
@vogella any feedback on this?
