### ISSUE TITLE
missing documentation for build-help-index

### ISSUE THREAD

**Issue by Bananeweizen** [eclipse-tycho/tycho#2536]
I've only learnt from the discussion in https://github.com/eclipse-platform/.github/issues/130 that Tycho can prebuild the help index. The generated documentation doesn't contain that goal: https://tycho.eclipseprojects.io/doc/latest/tycho-extras/tycho-document-bundle-plugin/plugin-info.html
What needs to be done to actually have the documentation generation pick up that goal?

**Comment by laeubi** [comment]
`latest` points to the current latest release (3.0.4), but this is currently only available at the `snapshots`:

- https://tycho.eclipseprojects.io/doc/master/tycho-extras/tycho-document-bundle-plugin/plugin-info.html

It is also mentioned at the release notes here:

- https://github.com/eclipse-tycho/tycho/blob/master/RELEASE_NOTES.md#new-document-bundle-mojo

This was also more an attempt to get rid of some ant scripts in platform (and now was removed completely) so great to hear this is of interest for others as well :-)

**Comment by Bananeweizen** [comment]
Thanks for the explanation. I just learned it also on my machine, when trying to run the goal on 3.0.4. :)
