### ISSUE TITLE
Clarification on pomDependencies consider

### ISSUE THREAD

**Issue by tivervac** [eclipse-tycho/tycho#2594]
We have a plugin that uses [ArchUnit](https://github.com/TNG/ArchUnit). ArchUnit contributes a JUnit test engine which, when added to our TP, confuses JUnit in Eclipse i.e. OSGi has to think for 30 seconds when running a JUnit Plugin Test and it then just spits out the infamous `Bundle "org.eclipse.jdt.junit5.runtime" not found`.

When we were still on Eclipse 2022-03, we solved this by adding ArchUnit as plain maven dependencies and using the `<pomDependencies>consider</pomDependencies>` of `target-platform-configuration`. While upgrading to 2023-03, we now have issues where incorrect Eclipse/OSGi dependencies are picked in our tycho build for Eclipse 2021-03 (our oldest supported target). Specifically, it picks an incorrect version (one that's not in our 2021-03 TP) for `org.eclipse.core.filesystem`. The 1.10 version it picked is only available transitively through our dependencies and is _not_ part of our TP. The one available in our TP is 1.7.700.

Now, if we remove the `<pomDependencies>consider</pomDependencies>`, everything runs smoothly, though ofcourse our tests don't work. This leads us to the question: **how does `pomConsider` work?**

We expected that `pomConsider` would just take our existing TP, and add the dependencies defined in the current pom.xml to it, without "leaking" these dependencies to other plugins in our multi-module setup. Apparently, it somehow also affects dependency resolution which seems rather odd.

Note that we only add three plain maven dependencies, all ArchUnit. ArchUnit itself does not (transitively) depend on anything Eclipse.

```
[ERROR] Unresolved requirement: Require-Bundle: org.eclipse.core.filesystem; bundle-version="[1.7.700,2.0.0)"
[ERROR]   -> Bundle-SymbolicName: org.eclipse.core.filesystem; bundle-version="1.10.0.v20230425-0513"; singleton:="true"

```

**Comment by laeubi** [comment]
The answer depends a little bit on the used Tycho version and your setup, but in general `pomDependencies=consider` means that all items you see with a `dependency:tree` of a project are scanned if they are a bundle and if yes added to the  result of the project dependency resolution.

**Comment by tivervac** [comment]
My bad I forgot the tycho versions. We originally saw this with Tycho 2.7.5. We then updated to 3.0.5, which gave the same result.

> all items you see with a dependency:tree

That would mean the transitive dependencies visible in the tree as well right?

**Comment by laeubi** [comment]
Yes it is (mostly) delegated to maven, so it works like maven, Tycho 4 uses a slightly different approach that gives precedence to the Target platform supplied items but without an example it is hard to tell if it helps in your case.

**Comment by tivervac** [comment]
Tycho 4.0 did seem to get rid of the compile errors without further pom changes, but since I didn't apply the migration steps, the build didn't work correctly yet. We've been able to workaround the issue by removing the pomconsider as well as the JUnit5 container in the .classpath. I consider this issue solved, thanks for explanation!
