### ISSUE TITLE
Sponsor resource pack

### ISSUE THREAD

**Issue by tivervac** [eclipse-tycho/tycho#2646]
Sigasi has one unused resource pack, Tycho's readme mentions that resource packs are welcome. If you agree, I'll put in a support request to donate our pack to Tycho. If you think another related project might need it more, let us know and we'll reconsider.

**Comment by laeubi** [comment]
@tivervac that would be great! Just let me know the ticket and I'll add your to the sponsor section!

**Comment by tivervac** [comment]
See https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3450
