### ISSUE TITLE
Detect some JavaSE from toolchains even without id

### ISSUE THREAD

**Issue by mickaelistria** [eclipse-tycho/tycho#2670]
In some environments, the toolchains.xml are properly defined for various versions, however the id doesn't set `JavaSE-XX` because it's not a very standard convention.
It would be nice for Tycho to work to some extents with such toolchains.
So if a toolchain id has `JavaSE-XX` it would be used, but if none if found, Tycho could lookup for a toolchain of type=jdk && version=XX and use it as fallback for the JavaSE-XX BREE.

**Comment by laeubi** [comment]
Can you share an example where it does not work? Actually Tycho already do it this way (Tycho 4+):
https://github.com/eclipse-tycho/tycho/blob/713fe84ff1e65d00d2fa2e7c531ecb5559485f4c/tycho-core/src/main/java/org/eclipse/tycho/core/ee/ExecutionEnvironmentUtils.java#L164-L192

**Comment by mickaelistria** [comment]
I will double-check but the issue happened with the setup-java goal of github actions, with JavaSE-1.8. But thinking mor about it after your comment, it could be a 8 vs 1.8 issue

**Comment by laeubi** [comment]
> it could be a 8 vs 1.8 issue

Yes that could be the case please note that Java 1.8 is no longer actively supported, but of course if you like you can add a PR to fix such an issue: https://github.com/eclipse-tycho/tycho/blob/master/RELEASE_NOTES.md#support-for-non-modular-jvms-no-longer-top-tier

Beside that, you can configure the ID used in the toolchains: https://github.com/actions/setup-java#maven-options

**Comment by mickaelistria** [comment]
JDT still has 1 bundle that targets Java 8. I'll check whether this can be removed.
In the meantime, I had found the way to override id for toolchains, and it works well.
I don't plan to work on this issue as the workaround is satisfying enough, so let's close it.
