### ISSUE TITLE
Publish test coverage results

### ISSUE THREAD

**Issue by akurtakov** [eclipse-tycho/tycho#287]
Tycho build already uses jacoco to gather the coverage data. It would be nice if either github or jenkins verification jobs publish the changes.

**Comment by akurtakov** [comment]
@laeubi  Do you think  you can help with that?

**Comment by laeubi** [comment]
I'll take a look it should be possible as I have seen some project having a "coverage" badge ... is this produced (where?) as part of the regular build or do wee need a special profile for that?

**Comment by laeubi** [comment]
https://github.com/marketplace/actions/jacoco-badge-generator

**Comment by akurtakov** [comment]
https://github.com/eclipse/tycho/blob/master/pom.xml#L500 is where the data is gathered.

**Comment by akurtakov** [comment]
And yes it's extra profie "coverage"

**Comment by laeubi** [comment]
For advanced reporting codecov seems suitable but maybe needs setup from an github-admin: https://docs.codecov.com/docs

**Comment by laeubi** [comment]
It also allows to comment on PRs https://docs.codecov.com/docs/pull-request-comments

**Comment by akurtakov** [comment]
It's time to admit no interest here.
