### ISSUE TITLE
org.eclipse.tycho:tycho-versions-plugin:bump-versions does not honor SNAPSHOT suffix

### ISSUE THREAD

**Issue by mlehmannm** [eclipse-tycho/tycho#2877]
When I use the bump-versions mojo as described [here](https://github.com/eclipse-tycho/tycho/blob/master/RELEASE_NOTES.md#new-tycho-versions-plugin-mojos), then the qualifier in the manifest and/or the snapshot suffix in the pom.xml of the bundle that get its version bumped is wiped out.

**Comment by laeubi** [comment]
@mlehmannm we have some integration test for the version plugin here:

https://github.com/eclipse-tycho/tycho/tree/master/tycho-its/src/test/java/org/eclipse/tycho/test/versionsplugin

Can you provide an [integration-test](https://github.com/eclipse/tycho/wiki#providing-an-integration-test) to demonstrate the issue?

**Comment by mlehmannm** [comment]
Give me some minutes and I'll provide a fix.
