### ISSUE TITLE
Release notes for 4.0.x, x > 0, are missing

### ISSUE THREAD

**Issue by dhendriks** [eclipse-tycho/tycho#2913]
See https://github.com/eclipse-tycho/tycho/blob/16eba006183677d3ee5db10d0da839f905fcec18/RELEASE_NOTES.md. The release notes for 3.0.0, 3.0.1, etc are present. 4.0.0 is present, but not 4.0.1 etc. The draft for 5.0.0 is present. I miss 4.0.1, 4,0.2, etc, which have already been released. I see their release notes in their tags, but on `master`.

**Comment by laeubi** [comment]
@dhendriks usually these are copied after a release but as we usually have only Bugfixes now there is not much "new", anyways if you like you can just open a PR to sync these into the master as well.

**Comment by dhendriks** [comment]
For 3.0.x it was included as well, even if it was only bugfixes/backports. Also, it is not only bugfixes/backports, see e.g. https://github.com/eclipse-tycho/tycho/blob/tycho-4.0.2/RELEASE_NOTES.md, which indicates 'new option to include referenced repositories when resolving the target platform'. Isn't it just good practice to have a complete overview of all the releases and their changes?

**Comment by laeubi** [comment]
As said, simply open a PR to copy over the parts from 4.x > master branch :-)

**Comment by dhendriks** [comment]
> As said, simply open a PR to copy over the parts from 4.x > master branch :-)

Fine, I've created #2920. Note that I don't think I should be doing this every time. I think whomever makes a release should do this.
