### ISSUE TITLE
Generated OSGi Metadata contains invalid Import-Package header

### ISSUE THREAD

**Issue by ptziegler** [eclipse-tycho/tycho#2941]
I'm not sure if there is anything that can be done on the Tycho side or if this is a pure BND problem, but here it goes:

Our target platform definition contains following Maven dependency:
```
<dependency>
    <groupId>net.sf.jazzy</groupId>
    <artifactId>jazzy-core</artifactId>
    <version>0.5.2</version>
</dependency>
```

Given its age, this artifact doesn't contain any OSGi headers and is therefore rebundled by Tycho as part of the target resolution.
If I try to build our project with Tycho 4.0.3 (and also the nigthly build), it fails with the following error:

> The default package '.' is not permitted by the Import-Package syntax.

Looking at the original jar, it seems like the maintainers have been very naughty and put classes inside the root folder, which seems to be confusing the BND tool.

![image](https://github.com/eclipse-tycho/tycho/assets/70652978/a3e20ab2-a560-4964-b182-9f005c05640e)

I assume that in the generated Manfest, all exported packages are also added to the `Import-Package` header, regardless of whether those are valid or not.
Note that this problem also shows up in m2e, but only starting with 2.3.0

**Comment by laeubi** [comment]
@ptziegler can you please open an issue here: https://github.com/bndtools/bnd/issues that BND is not trying to generate invalid `Import-Package` headers?

In the meanwhile I think you can fix this by providing custom BND instructions that don't export everything but only `Export-Package: com.*`

**Comment by laeubi** [comment]
@ptziegler by they way you probably also want to create an issue for them to

1. not use the default package
2. add OSGi headers by default using bnd-process maven goal.

**Comment by ptziegler** [comment]
> @ptziegler can you please open an issue here: https://github.com/bndtools/bnd/issues that BND is not trying to generate invalid Import-Package headers?

https://github.com/bndtools/bnd/issues/5830

> In the meanwhile I think you can fix this by providing custom BND instructions that don't export everything but only Export-Package: com.*

Sadly not. Even if I manually set the imported/exported packages, the error still shows up. Which, from my perspective, doesn't make sense at all. :(

> by they way you probably also want to create an issue for them to
> not use the default package
> add OSGi headers by default using bnd-process maven goal.

The first one sounds similar to the problem I'm facing right now. I also don't want to suddenly flood their issue tracker with problems, so let's wait and see what happens regarding the first one...

**Comment by laeubi** [comment]
> Sadly not. Even if I manually set the imported/exported packages, the error still shows up. Which, from my perspective, doesn't make sense at all.

If I must guess I think they are must have an import to their default package classes, so probably can you try using

```
Export-Package: com.*
Import-Package: !*
DynamicImport-Package: *
```

if that at least pass without an error?

**Comment by ptziegler** [comment]
> If I must guess I think they are must have an import to their default package classes, so probably can you try using
> 
> ```
> Export-Package: com.*
> Import-Package: !*
> DynamicImport-Package: *
> ```
> 
> if that at least pass without an error?

No, even with the following instructions, the error is still the same:

> Bundle-Name:           Bundle derived from maven artifact ${mvnGroupId}:${mvnArtifactId}:${mvnVersion}
version:               ${version_cleanup;${mvnVersion}}
Bundle-SymbolicName:   wrapped.${mvnGroupId}.${mvnArtifactId}
Bundle-Version:        ${version}
Export-Package:        com.*
Import-Package:        !*
DynamicImport-Package: *

My guess is that there really _is_ something going wrong inside BND, when it runs into such a weird jar.

**Comment by laeubi** [comment]
Then I fear there is not much at Tycho/m2e side to workaround :-\

**Comment by ptziegler** [comment]
No worries. I already appreciate the help you've offered.
As a workaround, we've taken the wrapped bundle and host it in our own repository. Meaning it's not an immediate issue, just something I'd like to resolve at some point in the future.
