### ISSUE TITLE
Tycho can't be build with Java 21 

### ISSUE THREAD

**Issue by akurtakov** [eclipse-tycho/tycho#2950]
Using Java 21 as system JVM (as e.g Fedora 39 ships with and probably others) makes compiling Tycho fail with:
```
[ERROR] Failed to execute goal org.codehaus.plexus:plexus-component-metadata:2.1.1:generate-metadata (default) on project p2-maven-plugin: Error generating metadata: : Failed to extract descriptors: Unsupported class file major version 65 -> [Help 1]
```

**Comment by akurtakov** [comment]
@laeubi There was some issue with moving away from it (as it's deprecated) but I can't recall the details

**Comment by laeubi** [comment]
It might work to use a more recent asm version as a dependency for that plugin:

https://mvnrepository.com/artifact/org.ow2.asm/asm

in general the problem was that the JSR annotations previously used an old version in maven so they don't work on Java 17 compiles classes, now we moved to Maven 3.9.x it should work, but is a lot of work to migrate.

But I'm a bit curious why java 21 is actually used, maybe we need some source/target configuration somewhere?

**Comment by akurtakov** [comment]
Would you please share an example of such migration to JSF (if you have handy)? In case someone decides to tackle this issue.

**Comment by akurtakov** [comment]
I figured it after asking, there is a pretty detailed doc on the topic https://github.com/eclipse/sisu.plexus/wiki/Plexus-to-JSR330

**Comment by laeubi** [comment]
Yes that's basically the reference, I planned to work on this for Maven4 /Tycho5 as we have to rewrite some stuff probably there ...

**Comment by alexsuter** [comment]
My build is failing when I set target level to 21:

```
Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:4.0.3:compile (default-compile) on project ch.****team.util.di: Fatal error compiling: target level should be in '1.1'...'1.8','9'...'20' (or '5.0'..'20.0') or cldc1.1: 21 -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:4.0.3:compile (default-compile) on project *i: Fatal error compiling
```

**Comment by laeubi** [comment]
> My build is failing when I set target level to 21

Yes JDT (the compiler used by Tycho) does not yet support Java 21, you can use a snapshot or wait for the next release on 2023-12
