### ISSUE TITLE
Virtual configuration IU in p2.inf does not work in 4.0.3 (works in 3.0.5)

### ISSUE THREAD

**Issue by mdaloia** [eclipse-tycho/tycho#2977]
### Discussed in https://github.com/eclipse-tycho/tycho/discussions/2972

<div type='discussions-op-text'>

<sup>Originally posted by **mdaloia** October 30, 2023</sup>
Hi,

We have a "virtual" IU provided and required in a p2.inf file of a bundle to add a touchpoint configuration (it really doesn't matter what it does) that used to work in 3.0.5. We are migrating to 4.0.3 and found that it fails with:
```
[ERROR] Cannot resolve project dependencies:
[ERROR]   Software being installed: p2.inf 1.0.0.qualifier
[ERROR]   Missing requirement: p2.inf 1.0.0.qualifier requires 'org.eclipse.equinox.p2.iu; configure.p2.inf 0.0.0' but it could not be found
```

I have reduced it to an example project: https://github.com/mdaloia/tycho-p2-inf

(**Environment used**: Maven 3.9.4 / Java 17)

If I build it with
- `mvn clean package -Dtycho.localArtifacts=ignore -Dtycho-version=4.0.3`
it fails with the mentioned error and no `target/p2content.xml` is created.

I tried adding `-Dtycho.resolver.classic=false` as explained in "[mixed reactor setups require the new resolver now](https://github.com/eclipse-tycho/tycho/blob/master/RELEASE_NOTES.md#mixed-reactor-setups-require-the-new-resolver-now)"  but I got the same error.

But if I only change the version:
- `mvn clean package -Dtycho.localArtifacts=ignore -Dtycho-version=3.0.5`
it works and in the `target/p2content.xml` file I see the `<unit id='configure.p2.inf'>` and the `<required namespace='org.eclipse.equinox.p2.iu' name='configure.p2.inf' range='0.0.0'/>`

This is because I have `<pomDependencies>consider</pomDependencies>` and it shows this message:
```
[INFO] The following requirements are not satisfied yet and must be provided through pom dependencies:
[INFO]    - org.eclipse.equinox.p2.iu; configure.p2.inf 0.0.0
```
If I remove this configuration it fails with the same error as using 4.0.3.
</div>

**Comment by mdaloia** [comment]
@laeubi Unfortunately the changes made in PR #2989 partially fixes it.

If you have another bundle in which the `Require-Bundle` references the bundle that has the `p2.inf` with the `provides` & `requires` the same error appears:

```
[ERROR] Cannot resolve project dependencies:
[ERROR]   Software being installed: pvu.bundle2 1.0.0.qualifier
[ERROR]   Missing requirement: pvu.bundle 1.0.0.qualifier requires 'org.eclipse.equinox.p2.iu; configure.pvu.bundle 0.0.0' but it could not be found
[ERROR]   Cannot satisfy dependency: pvu.bundle2 1.0.0.qualifier depends on: osgi.bundle; pvu.bundle 0.0.0
```

See these changes to the originally provided integration test: https://github.com/eclipse-tycho/tycho/compare/master...mdaloia:tycho:pr-2977-partial-fix

Try building it with: `mvn clean package -Dtycho.localArtifacts=ignore -Dtycho-version=4.0.4`

Let me know if do you want me to provide a PR with these modifications to the IT, create another IT, or any other thing.

Thanks in advance!

**Comment by laeubi** [comment]
@mdaloia I just thought that such case might came up... :-\

I think the best would be to have an additional case, so one can investigate to solve this, but maybe in such a case you want to make the requirement optional and greedy instead? Then it won't be required at build time.

**Comment by mdaloia** [comment]
@laeubi Thanks for the hint about using a requirement optional and greedy... it worked.

Ok, I will provide another reproducer example.

BTW, Do you know if there is any other documentation than this one https://wiki.eclipse.org/Equinox/p2/Customizing_Metadata that explains what is/means all the available options?

**Comment by laeubi** [comment]
> BTW, Do you know if there is any other documentation than this one https://wiki.eclipse.org/Equinox/p2/Customizing_Metadata that explains what is/means all the available options?

I fear not `p2.inf` usage is very very special area so if you like to improve that it would be best to [contribute it directly to p2](https://github.com/eclipse-equinox/p2) as even the wiki is about to shutdown soon :-\

Also Tycho has some docs that might deserve some docs about p2.inf usage: https://github.com/eclipse-tycho/tycho/tree/master/src/site

**Comment by mdaloia** [comment]
@laeubi I've just opened https://github.com/eclipse-tycho/tycho/pull/3039 with the new IT case.

Hope this helps. Let me know otherwise. Thanks!
