### ISSUE TITLE
Docu bug: Most recent snapshot site

### ISSUE THREAD

**Issue by vogella** [eclipse-tycho/tycho#3113]
The contributing guide says:

For documentation of the most recent snapshot build, see the [Snapshot Tycho Site](https://ci.eclipse.org/tycho/job/tycho-sitedocs/lastSuccessfulBuild/artifact/target/staging/index.html).

But that is a 404. Which URL is the correct one?

**Comment by mickaelistria** [comment]
I think it's https://tycho.eclipseprojects.io/doc/master/index.html . Feel free to open a PR changing it, that would be very welcome.
