### ISSUE TITLE
Make `referencedRepositoryMode=include` the default for `target-platform-configuration`

### ISSUE THREAD

**Issue by LorenzoBettini** [eclipse-tycho/tycho#3231]
As disccused here https://github.com/eclipse-tycho/tycho/pull/3229#issuecomment-1849992108

**Comment by LorenzoBettini** [comment]
@laeubi can these failures in my fork https://github.com/LorenzoBettini/tycho/actions/runs/7191995115/job/19590562389 be related to making  `referencedRepositoryMode=include` the default? It looks like it tries to contact sites that don't exist anymore. Of course, I can update the corresponding IT projects POMs.

**Comment by laeubi** [comment]
> It looks like it tries to contact sites that don't exist anymore

Yes thats very likely.

> I can update the corresponding IT projects POMs.

please do so, if you want to test locally usually a

`mvn clean install -T1C -DskipTests`

then
```
cd ~/git/laeubi/tycho/tycho-its
mvn clean install -Pits -Dtest=<your test>
```

works quite well.

**Comment by LorenzoBettini** [comment]
OK, locally I reproduced the problem and fixed that like that https://github.com/LorenzoBettini/tycho/commit/27d4db5dbf2b268ca3538776e3a6cf4c2105712e

some of the reported failed ITs work on my machine without any modification, I'll investigate further

**Comment by LorenzoBettini** [comment]
@laeubi everything seems to be green, I created the PR.
