### ISSUE TITLE
Included Maven artifacts (from "consider" or Maven location in .target) should include checksums

### ISSUE THREAD

**Issue by mickaelistria** [eclipse-tycho/tycho#336]
Included Maven artifacts (from "consider" or Maven location in .target) should include checksums to provide some safety. Those checksums should ideally be fetched from the Maven repo and copied unmodified to ensure we do consume the exact same artifact as what's upstream.

**Comment by laeubi** [comment]
I'm just wondering if not maven already verifies those? At least I get some warnings if they are missing that maven complains about unverifiable artifacts.

**Comment by laeubi** [comment]
> I see those checksums on maven-metadata.xml but not on actual artifacts.

They are stored as separate files here:
https://repo1.maven.org/maven2/commons-io/commons-io/2.6/

I'm not sure if this is really one of those "not a tycho issue", if one wants to verify he can add `--strict-checksums` and we simply calculate checksum on our own when producing an repository... only for PGP I think it is worth to carry them around as we can't regenerate the data but that's not very convenient (see first comment).
