### ISSUE TITLE
 Option to ignore p2 mirrors via the Maven settings and the new  eclipse.p2.mirrors option - not working?

### ISSUE THREAD

**Issue by Phillipus** [eclipse-tycho/tycho#3375]
@vogella 

https://github.com/eclipse-tycho/tycho/commit/22a18fdd79e203b7d3e3d7dbf97ed9093f481814

I'm testing this new option locally. A couple of things:

If I set `-Dtycho.disableP2Mirrors=true` in my `maven.config` file I see the warning about it being deprecated, but not if I have this in my global `settings.xml` file:

```
<properties>
    <tycho.disableP2Mirrors>true</tycho.disableP2Mirrors>
</properties>
```

Is the following trailing space supposed to be there? Does it matter?

```
String key = "eclipse.p2.mirrors ";
```

**Comment by vogella** [comment]
Thanks @Phillipus I will push a fix

**Comment by vogella** [comment]
cc @laeubi

**Comment by Phillipus** [comment]
Thanks. But I'm not sure it's reading the key and value from the `settings.xml` file as well as the system property, is it supposed to?

**Comment by vogella** [comment]
> Thanks. But I'm not sure it's reading the key and value from the `settings.xml` file as well as the system property, is it supposed to?

I would think that is what `mavenContext.getSession().getSystemProperties()` or `mavenContext.getSession().getUserProperties()` is for. @laeubi can you comment?

**Comment by Phillipus** [comment]
Should it check for `value` rather than `key` in that code block?

**Comment by vogella** [comment]
> Should it check for value rather than key in that code block?

I'm redfaced.... PR is coming

**Comment by Phillipus** [comment]
> I'm redfaced.... PR is coming

LOL, we all do it. :-)

**Comment by laeubi** [comment]
That's what happens if there are no test ... :-D

**Comment by Phillipus** [comment]
Even with that change `mavenContext.getSession().getSystemProperties().getProperty(key)` and `mavenContext.getSession().getUserProperties().getProperty(key)` is returning null. I have the following `settings.xml` file:

```xml
<?xml version="1.0" encoding="UTF8"?>
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 https://maven.apache.org/xsd/settings-1.0.0.xsd">

    <profiles>
        <profile>
            <id>tycho-snapshots</id>
            <pluginRepositories>
                <pluginRepository>
                    <id>tycho-snapshots</id>
                    <url>https://repo.eclipse.org/content/repositories/tycho-snapshots/</url>
                    <releases>
                        <enabled>false</enabled>
                    </releases>
                </pluginRepository>
            </pluginRepositories>
            <properties>
                <eclipse.p2.mirrors>true</eclipse.p2.mirrors>
            </properties>
        </profile>
    </profiles>

    <activeProfiles>
        <activeProfile>tycho-snapshots</activeProfile>
    </activeProfiles>
</settings>
```

(Note, I'm testing with locally compiled and installed Tycho 5.0.0-SNAPSHOT)
