### ISSUE TITLE
Authentication fails when trying to resolve a target platform over an authenticated mirror that is a composite repository

### ISSUE THREAD

**Issue by kevloral** [eclipse-tycho/tycho#3501]
Related to #2930, authentication still fails when the mirror that requires authentication is a composite repository . As a reminder, the mirror is declared like this in my Maven _settings.xml_ file:

```
<mirror>
	<id>nexus-p2</id>			
	<name>Nexus P2</name>
	<url>https://servidor.jma:8443/nexus/content/groups/global-p2/</url>
	<mirrorOf>eclipse_2022-06,eclipse_2023-06,mylyn_3.25,swtbot_snapshots,tpd_nightly</mirrorOf>
	<layout>p2</layout>
    <mirrorOfLayouts>p2</mirrorOfLayouts>
</mirror>
```

And its credentials are declared like this :
```

<server>
	<id>nexus-p2</id>
	<username>jm.arnesto</username>
	<password>********</password>
</server>
```

After the fixes we implemented in #2930, authentication works for the mirror itself, but still fails for the child locations it declares:

```
<?xml version='1.0' encoding='UTF-8'?>
<?compositeArtifactRepository version='1.0.0'?>
<repository name='generated-composite-metadata-repository' type='org.eclipse.equinox.internal.p2.artifact.repository.CompositeArtifactRepository' version='1'>
  <properties size='1'>
    <property name='p2.timestamp' value='1693774779425'/>
  </properties>
  <children size='7'>
    <child location='../../repositories/eclipse_2023-06'/>
    <child location='../../repositories/basis_23'/>
    <child location='../../repositories/eclipse_2022-06'/>
    <child location='../../repositories/basis_22'/>
    <child location='../../repositories/mylyn_3.25'/>
    <child location='../../repositories/swtbot_snapshots'/>
    <child location='../../repositories/tpd_nightly'/>
  </children>
</repository>
```

I will implement a test that reproduces the bug and propose a fix for it in a PR.

**Comment by laeubi** [comment]
@kevloral yes composited that points to childs below the base dir are a bit tricky.

> I will implement a test that reproduces the bug and propose a fix for it in a PR.

Thanks, I plan to make a new bugfix release soon, do you have an estimate so we can probably wait for your fix to be included?

**Comment by akurtakov** [comment]
As thsi bugfix release is aimed for 4.31 Platform build to not use snapshot Tycho 4.x release would have to be out next Monday (Feb 19th) at the very latest in order to have couple of days to propagate things to the RC1 build.

**Comment by kevloral** [comment]
I have updated the title given that the problem occurs when trying to resolve a target platform using a p2 composite repository that requires authentication, no matter whether it is acting as a mirror (_testTargetDefinitionAuthMirror_) or not (_testTargetDefinitionEncrypted_).

**Comment by kevloral** [comment]
I have restored the previous title, given that test _testTargetDefinitionEncrypted_ was failing for a completely different reason (that has already been fixed).

**Comment by kevloral** [comment]
The PR that contains the fix for this issue is now ready to be reviewed: https://github.com/eclipse-tycho/tycho/pull/3521
