### ISSUE TITLE
Goal fix-artifacts-metadata should support overriding configuration via System Properties (for invocation via CLI)

### ISSUE THREAD

**Issue by in-fke** [eclipse-tycho/tycho#3505]
We would like to run the goal from the command line as follows

`mvn -DrepositoryLocation=repository org.eclipse.tycho:tycho-p2-repository-plugin:fix-artifacts-metadata`

but apparently overriding `repositoryLocation` does not work this way (the Mojo needs to support it?).
See https://github.com/eclipse-tycho/tycho/blob/main/tycho-p2-repository-plugin/src/main/java/org/eclipse/tycho/plugins/p2/repository/AbstractRepositoryMojo.java

(probably, some prefix would be good, effectively somethine like `tycho.repositoryLocation`).

Also, a backport to 2.x would be great.

**Comment by laeubi** [comment]
> We would like to run the goal from the command line as follows
> 
> `mvn -DrepositoryLocation=repository org.eclipse.tycho:tycho-p2-repository-plugin:fix-artifacts-metadata`
> 

Can you explain the use case of that? The mojo is defiantly not meant to be executed on the CLI and I can't really think about why this would be useful.

> but apparently overriding repositoryLocation does not work this way (the Mojo needs to support it?).

The mojo currently has no system property to configure it from the commandline, but adding those would be rather trivial.

> Also, a backport to 2.x would be great.

Regarding back-ports please see https://github.com/eclipse-tycho/tycho/blob/master/CONTRIBUTING.md#backporting for details.

**Comment by in-fke** [comment]
Thanks for following up on this so quickly! ;)
Our use case is that we compose a repository, then sign all the JARs (for WebStart), and sometimes we want to revert an unnecessary re-signing of JARs so we don't bloat the commit history. I know we could a conditional signing of JARs if already signed, but we use copy-dependencies from the original repo and from their, they come unsigned. So after reverting some local changes in the git checkout, we want to run that "fix". It's a rather awkward way of managing a p2 repository, I know....

**Comment by laeubi** [comment]
> so we don't bloat the commit history

So you commit your repository to git? That's really unusual and actually Tycho should offer everything you need to fetch any dependencies and make a site from it including signing only unsigned items afterwards.

Just in case you need some dedicated commercial support please take a look here: https://github.com/eclipse-tycho/tycho?tab=readme-ov-file#getting-support
