### ISSUE TITLE
tycho-p2-director:director uses wrong directory when run on macOS

### ISSUE THREAD

**Issue by sratz** [eclipse-tycho/tycho#3548]
When `tycho-p2-director:director` is executed on macOS, the destination contains an additional `Contents/Eclipse/` directory.

This seems to have been introduced with dc99997b8e2ebd08592d30c9634a4a12baaef59d:
https://github.com/eclipse-tycho/tycho/blob/62f83cfca9b134546cb267a61359eec51a5a4d42/tycho-p2-director-plugin/src/main/java/org/eclipse/tycho/plugins/p2/director/DirectorMojo.java#L364

But this is incorrect. The **running** environment is not relevant for the target destination.

I'll provide an extension to the existing integration test that should fail when the test itself is executed on macOS.

**Comment by laeubi** [comment]
> But this is incorrect. The running environment is not relevant for the target destination.

It depends a bit how should director know the "target"? I would think about we use the configurable 

https://github.com/eclipse-tycho/tycho/blob/62f83cfca9b134546cb267a61359eec51a5a4d42/tycho-p2-director-plugin/src/main/java/org/eclipse/tycho/plugins/p2/director/DirectorMojo.java#L263

if given or check if the profile gives some hints but beside this its hard to guess.

**Comment by sratz** [comment]
If `-destination` is given a parameter that ends in `.app`, and `p2os` is `macosx`, the director already handles this itself.

**Comment by sratz** [comment]
https://github.com/eclipse-tycho/tycho/blob/62f83cfca9b134546cb267a61359eec51a5a4d42/tycho-core/src/main/java/org/eclipse/tycho/p2tools/copiedfromp2/DirectorApplication.java#L925-L932

So in `DirectorMojo`, the destination should be passed in to `-destination` without any pre-processing.

**Comment by laeubi** [comment]
> If `-destination` is given a parameter that ends in `.app`, and `p2os` is `macosx`, the director already handles this itself.

But this does not work if destination if a generic folder and one wants to use it on multiple platforms.

**Comment by laeubi** [comment]
Hard to tell but Tycho automatically detects this already for e.g. the p2 installed runtime in test so it seems at laest valid here as well.

For example `org.eclipse.tycho.p2.tools.director.shared.DirectorRuntime.getDestination(File, TargetEnvironment)` already checks if it is a valid layout and if that the case passes the path unchanged, so maybe one should just take into account the p2os and then everything will work as expsected.

**Comment by sratz** [comment]
> Hard to tell but Tycho automatically detects this already for e.g. the p2 installed runtime in test so it seems at laest valid here as well.
> For example `org.eclipse.tycho.p2.tools.director.shared.DirectorRuntime.getDestination(File, TargetEnvironment)` already checks if it is a valid layout and if that the case passes the path unchanged, so maybe one should just take into account the p2os and then everything will work as expsected.

But that would mean that `DirectorMojo` is not a 1:1 drop-in replacement for a

`eclipse -application org.eclipse.equinox.p2.director -destination <destination> ...`

stand-alone invocation, because `<destination>` is modified by Tycho, and the original logic of dealing with macOS app bundles defined in 
https://github.com/eclipse-tycho/tycho/blob/62f83cfca9b134546cb267a61359eec51a5a4d42/tycho-core/src/main/java/org/eclipse/tycho/p2tools/copiedfromp2/DirectorApplication.java#L925-L932
would never be hit anymore.

I think this is a bit counter-intuitive.

**Comment by laeubi** [comment]
> stand-alone invocation, because <destination> is modified by Tycho, and the original logic of dealing with macOS app bundles defined in

I'm not sure I really understand if it makes a difference where in Tycho code this check is performed, so maybe we should just remove that check altogether in DirectorApplication?

> This does not work for custom products, eg. we are using

This should be covered by `hasRequiredMacLayout`, but obviously there is no test for that currently.

**Comment by laeubi** [comment]
@sratz just a general comment, the main "issue" maybe is that there is only little documentation on the DirectorApp usage regarding mac and I just added it to be more convenient, but it seems you have some experience, so what do you think about we make 

```
<p2os>...</p2os>
<p2ws>...</p2ws>
<p2arch>..</p2arch>
```

somehow required and if not given forcefully set it to the running environment?

**Comment by sratz** [comment]
> > stand-alone invocation, because  is modified by Tycho, and the original logic of dealing with macOS app bundles defined in
> 
> I'm not sure I really understand if it makes a difference where in Tycho code this check is performed, so maybe we should just remove that check altogether in DirectorApplication?

Well there are two options:
1. We change the semantics and make
  `DirectorMojo`
  explicitly different in behavior to
  `eclipse -application org.eclipse.equinox.p2.director -destination <destination> ...`.
   That means instead of
    `<destination>target/ABAPDevelopmenTools.app</destination>`
    we would have to use
    `<destination>target/ABAPDevelopmenTools.app/Contents/Eclipse</destination>`
    in the pom.xml so  `hasRequiredMacLayout` understands our intention and to get the same directory layout result.
   (And `hasRequiredMacLayout` would need to be fixed to handle arbitrary app bundle names).
2. We keep the old semantics and revert line https://github.com/eclipse-tycho/tycho/blob/62f83cfca9b134546cb267a61359eec51a5a4d42/tycho-p2-director-plugin/src/main/java/org/eclipse/tycho/plugins/p2/director/DirectorMojo.java#L364 again.

> @sratz just a general comment, the main "issue" maybe is that there is only little documentation on the DirectorApp usage regarding mac and I just added it to be more convenient, ...

Yes, that's a great addition to Tycho and the original documentation is indeed lacking. So getting the original
`eclipse -application org.eclipse.equinox.p2.director -destination <destination> ...`
is already some obstacle :)
That's also why my vote would be to go with option 2) to allow for easy migration / compatibility / less surprises.

> ... but it seems you have some experience, so what do you think about we make
> 
> ```
> <p2os>...</p2os>
> <p2ws>...</p2ws>
> <p2arch>..</p2arch>
> ```
> 
> somehow required and if not given forcefully set it to the running environment?

This is relevant in case of option 1) above, in which case, yes, `<p2os>` & co. must be considered if given. If not given, a fallback could be made to the *running* environment.

**Comment by laeubi** [comment]
I think that sounds reasonable, do you like to add a testcase for the `<destination>target/ABAPDevelopmenTools.app</destination>` case as well? Sadly I have no access to any mac so its for me more flying blindly and hoping the PR validation shows any mac issues and if so debugging becomes a nightmare.

So to summarize I think as you suggested:

1. remove preprocessing of `destination` in `DirectorMojo`
2. if any `p2xx` is given all of them must be specified or mojo throws an error
3. if no `p2xx` is given, we derive them from running environment
4. Add more test-cases for different usages and maybe some more javadoc to the Mojo and its parameters

@sratz do you like to give it a try?

**Comment by sratz** [comment]
> So to summarize I think as you suggested:
> 
> 1. remove preprocessing of `destination` in `DirectorMojo`
> 2. if any `p2xx` is given all of them must be specified or mojo throws an error
> 3. if no `p2xx` is given, we derive them from running environment
> 4. Add more test-cases for different usages and maybe some more javadoc to the Mojo and its parameters

Yes, that sounds good.

> @sratz do you like to give it a try?

Yes, I'll provide a pull-request (or rather update #3549).
