### ISSUE TITLE
API Tools Plugin should fail the build if the baseline resolution fails

### ISSUE THREAD

**Issue by Kummallinen** [eclipse-tycho/tycho#3570]
The current API Tools Plugin only prints a warning if the API baseline resolution fails. 

I don't think it should be expected that developers or code reviewers search though the build logs every time to verify the API checks actually ran. This should be considered a fatal error, or at least configurable to be if you want to keep the current behaviour as default.

PDE based tooling would fail the build on a API baseline resolution failure.

Caused by https://github.com/eclipse-tycho/tycho/blob/f4752edc0adea7b3b262cf332144cdb78d47b543/tycho-apitools-plugin/src/main/java/org/eclipse/tycho/apitools/ApiAnalysisMojo.java#L163

**Comment by laeubi** [comment]
@Kummallinen do you like to propose a PR that makes this configurable? At best combined with an [integration-test](https://github.com/eclipse/tycho/wiki#providing-an-integration-test) to demonstrate the issue so we can make sure it doesn't break in the future.

**Comment by Kummallinen** [comment]
@laeubi I can do that, busy with other stuff at the moment so will probably be a few weeks
