### ISSUE TITLE
PRs with pending reviews are merged

### ISSUE THREAD

**Issue by akurtakov** [eclipse-tycho/tycho#3661]
E.g. https://github.com/eclipse-tycho/tycho/pull/3638 is merged despite licensecheck complaining as it finds out https://github.com/eclipse-tycho/tycho/actions/runs/8253529633/job/22575590947 there is iplab issue is open.

**Comment by laeubi** [comment]
@netomi do you have any hints for us? Actually the ip check should be a required check for the branch protection:

https://github.com/eclipse-tycho/.eclipsefdn/blob/a042ee8257838a90434a5f664b4598266768f777/otterdog/eclipse-tycho.jsonnet#L79

**Comment by netomi** [comment]
Looking at the latest data I can see that all checks for the PR passed:

![image](https://github.com/eclipse-tycho/tycho/assets/1048055/5d715d00-5379-4325-8775-c3d901edc1d1)

The number of required approvals is set to 0, but I guess dependabot is configured to auto-merge if all checks pass. Maybe you wanna disable that.

**Comment by laeubi** [comment]
The automerge is actually desired. I now found the offending commit here:

https://github.com/eclipse-tycho/tycho/actions/runs/8243909268/job/22562813997

it says that the check passed, but the logfile indicates differently @HannesWell  could it be that the request for a license (what now works automatically :+1: ) makes the result of the check "green"?

**Comment by netomi** [comment]
ah indeed I did not check the license checking workflow. It indeed output some error but does not propagate whether the job failed or not. I suggest to add a final step to the workflow to return 0 if all licenses are vetted or something else if not to be able to use it with branch protection rules and dependabot.

**Comment by HannesWell** [comment]
> it says that the check passed, but the logfile indicates differently @HannesWell could it be that the request for a license (what now works automatically 👍 ) makes the result of the check "green"?

I have to look it up again since the change of license work-flow to allow auto-request of dependa-bot PR is already some time in the past.
Can you tell why the auto-request works now? I'm not aware of a recent change in the workflow so it must be some configuration change.

**Comment by laeubi** [comment]
I just noticed that the comment seems to be added automatically there also for example:
- https://github.com/eclipse-tycho/tycho/pull/3660

maybe because github action is now a valid ECA user?

**Comment by HannesWell** [comment]
> maybe because github action is now a valid ECA user?

IIRC the problem that the automated requests of license reviews for dependabot PRs was on the GitHub side since the dependabot user didn't have access to repo/organisation secrets and therefore could not obtain the EF-Gitlab-token.
But if it works now that is great.

Nevertheless, I looked through the workflow and indeed the workflow false failed in case of automatically created vetting-requests.
I updated the logic to fix that in https://github.com/eclipse/dash-licenses/pull/328. I'll test it and submit it if it works as desired.

**Comment by HannesWell** [comment]
> Nevertheless, I looked through the workflow and indeed the workflow false failed in case of automatically created vetting-requests.
> I updated the logic to fix that in [eclipse/dash-licenses#328](https://github.com/eclipse/dash-licenses/pull/328). I'll test it and submit it if it works as desired.

All testing was successful and the PR is submitted. This issue should now be fixed.

**Comment by laeubi** [comment]
Thank you! This will further simplify things when upgrading!
