### ISSUE TITLE
tycho 2.7.5 not compatible with jdk11

### ISSUE THREAD

**Issue by raymond-pg** [eclipse-tycho/tycho#3669]
We used to build our project with tycho 2.7.5 in jdk11. But after March, 11, 2024, it is throwing error like:
**_java.lang.UnsupportedClassVersionError: org/eclipse/core/runtime/IProgressMonitor has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0_**

The reason is that org.eclipse.equinox.common was upgraded to 3.19 which is built under jdk 17, while our environment is still jkd11.
after checking the pom file of org.eclipse.equinox.p2.core which depends on org.eclipse.equinox.common, it actually defined  a version ragen from 3.5.0 to 4.0.0, but maven by default is downloading the latest(3.19)

May I know is there a way to configure the version of org.eclipse.equinox.common? (I would like to use 3.18.200)
And how to do it?

**Comment by akurtakov** [comment]
It's well explained in https://github.com/eclipse-tycho/tycho/discussions/3573 .
