### ISSUE TITLE
tycho-build 2.7.3 now requires Java17

### ISSUE THREAD

**Issue by frawa** [eclipse-tycho/tycho#3670]
Using tycho 2.7.3 as as a Maven extension via .mvn/extensions.xml now requires Java17.

That's because it depends on [org.eclipse.equinox.p2.core/2.9.0](https://mvnrepository.com/artifact/org.eclipse.platform/org.eclipse.equinox.p2.core/2.9.0),
which depends on a version range of [org.eclipse.equinox.common](https://mvnrepository.com/artifact/org.eclipse.platform/org.eclipse.equinox.common),
which released [3.19.0](https://mvnrepository.com/artifact/org.eclipse.platform/org.eclipse.equinox.common/3.19.0) four days ago, 11.4.2024, and requires Java17.

Having tycho-build depend on  [org.eclipse.equinox.p2.core/2.10.0](https://mvnrepository.com/artifact/org.eclipse.platform/org.eclipse.equinox.p2.core/2.10.0) seems to fix the problem, as it depends on (un-ranged) 3.18.0 of org.eclipse.equinox.common.

**Comment by akurtakov** [comment]
Workarounds, proper fixes and so on are at https://github.com/eclipse-tycho/tycho/discussions/3573
