### ISSUE TITLE
Broken links in the Eclipse/Github wiki

### ISSUE THREAD

**Issue by nbauma109** [eclipse-tycho/tycho#3770]
The broken links  from the original Eclipse wiki https://wiki.eclipse.org/Tycho/pomless are:

- [Tycho/pomless/Structured Build](https://wiki.eclipse.org/index.php?title=Tycho/pomless/Structured_Build&action=edit&redlink=1)
- [pomless aggregation of modules](https://wiki.eclipse.org/index.php?title=Pomless_aggregation_of_modules&action=edit&redlink=1)

Please fix directly in the new wiki page https://github.com/eclipse-tycho/tycho/wiki/Tycho-Pomless

**Comment by sratz** [comment]
Thanks for the report! Links are now fixed.
