### ISSUE TITLE
[tycho-version-plugin] Since 4.0.5 non-matching version of child modules are forcefully overwritten

### ISSUE THREAD

**Issue by sratz** [eclipse-tycho/tycho#3808]
`tycho-version-plugin:set-version` states:

_Sets the version of the current project and child projects **with the same version**, and updates references as necessary._

Consider the following structue:
```
pom.xml: version=2.0.0 [modules=P,Q]
P/pom.xml: version=2.0.0, parent=2.0.0 [modules=m1,m2]
P/m1/pom.xml: version=2.0.0, parent=2.0.0
P/m2/pom.xml: version=2.0.0, parent=2.0.0
Q/pom.xml: version=1.0.0, parent=2.0.0 [modules=m3,m4]
Q/m3/pom.xml: version=1.0.0, parent=1.0.0
Q/m4/pom.xml: version=1.0.0, parent=1.0.0
```

Execute: `set-version -DnewVersion=2.0.1`

Result with Tycho <= 4.0.4:
```
pom.xml: version=2.0.1 [modules=P,Q]
P/pom.xml: version=2.0.1, parent=2.0.1 [modules=m1,m2]
P/m1/pom.xml: version=2.0.1, parent=2.0.1
P/m2/pom.xml: version=2.0.1, parent=2.0.1
Q/pom.xml: version=1.0.0, parent=2.0.1 [modules=m3,m4]
Q/m3/pom.xml: version=1.0.0, parent=1.0.0
Q/m4/pom.xml: version=1.0.0, parent=1.0.0
```

Result with Tycho >= 4.0.5:
```
pom.xml: version=2.0.1 [modules=P,Q]
P/pom.xml: version=2.0.1, parent=2.0.1 [modules=m1,m2]
P/m1/pom.xml: version=2.0.1, parent=2.0.1
P/m2/pom.xml: version=2.0.1, parent=2.0.1
Q/pom.xml: version=2.0.1, parent=2.0.1 [modules=m3,m4]
Q/m3/pom.xml: version=2.0.1, parent=2.0.1
Q/m4/pom.xml: version=2.0.1, parent=2.0.1
```

This is incorrect as the _**with the same version**_ contract is violated and also all the mis-matching versions of 1.0.0 are forcefully updated to 2.0.1.

This is a side-effect of #3341 / #3343

**Comment by laeubi** [comment]
@sratz do you like to add this as a testcases here and propose a fix:

https://github.com/eclipse-tycho/tycho/tree/main/tycho-its/projects/tycho-version-plugin/set-version

**Comment by sratz** [comment]
> @sratz do you like to add this as a testcases here and propose a fix:
> 
> https://github.com/eclipse-tycho/tycho/tree/main/tycho-its/projects/tycho-version-plugin/set-version

Yes, however I am trying to put my head around the intention of #3341 / #3343: Am I understanding it right that
- before: Nested projects were only updated when a child module also had a `<parent>` reference back?
- after: Nested projects are also updated even when they do not have a `<parent>` reference?

Why was this needed? My gut feeling tells me that if a child module does *not* link to a `<parent>`, it should be considered more loosely coupled and not updating its version is probably OK?
