### ISSUE TITLE
sort order of root nodes in dependency-tree is unstable

### ISSUE THREAD

**Issue by Bananeweizen** [eclipse-tycho/tycho#3817]
Running the dependency-tree mojo on a larger project generates the tree items as such fine. However, in a larger reactor the order of root nodes is "random". So for a list of plugins the root nodes might be sorted

module foo:
* foo
* foo.source
* target platform extra requirements

module bar:
* target platform extra requirements
* bar
* bar.source

etc. Can we make them appear always in the same order? I guess the "randomness" comes from the algorithm that sorts the list of dependencies into the tree node structure, but I didn't easily find how to change it to get something like always foo, foo.source, extra requirements.

Maybe even something as simple as just sorting the root nodes alphabetically would be a quick solution?

**Comment by laeubi** [comment]
I think the function that prints the result might just order by ID then by Version should be fine.
