### ISSUE TITLE
[DS] Validation of transitive generated 'osgi.extender=osgi.component' requirement fails

### ISSUE THREAD

**Issue by HannesWell** [eclipse-tycho/tycho#3824]
When the `dsVersion=1.4` is used the `tycho-ds-plugin` automatically adds the following requirement to a bundle providing declarative service components:
`Require-Capability: osgi.extender; filter:="(&(osgi.extender=osgi.component)(version>=1.4.0)(!(version>=2.0.0)))"`

In general this is good to ensure a corresponding service component runtime is available at runtime, but it fails the build of depending projects, probably if they don't contain any DS-component:
```
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:4.0.7:validate-classpath (default-validate-classpath) on project foo.bar2: Execution default-validate-classpath of goal org.eclipse.tycho:tycho-compiler-plugin:4.0.7:validate-classpath failed: org.osgi.framework.BundleException: Bundle foo.bar2 cannot be resolved:foo.bar2 [157]
[ERROR]   Unresolved requirement: Require-Bundle: foo.bar1; bundle-version="4.0.0"
[ERROR]     -> Bundle-SymbolicName: foo.bar1; bundle-version="1.0.0.202405060842"; singleton:="true"
[ERROR]        foo.bar1 [155]
[ERROR]          Unresolved requirement: Require-Capability: osgi.extender; filter:="(&(osgi.extender=osgi.component)(version>=1.4.0)(!(version>=2.0.0)))"
```

Adding the requirement manually/explicitly to the `MANIFEST.MF` in the project makes the build work.

**Comment by laeubi** [comment]
Can you provide an [integration-test](https://github.com/eclipse/tycho/wiki#providing-an-integration-test) to demonstrate the issue?

**Comment by HannesWell** [comment]
> Can you provide an [integration-test](https://github.com/eclipse/tycho/wiki#providing-an-integration-test) to demonstrate the issue?

I'm working on it.

I forgot the mention that adding the requirement manually/explicitly to the `MANIFEST.MF` in the project makes the build work. Updated the initial comment.

**Comment by laeubi** [comment]
I think we should probably provide the capability here as a convenience, it has no real use at the compile stage.

**Comment by mwgmnn** [comment]
We switched to tycho 4.0.7 the other day (came from an old 2.6.0) and had the same problem. We helped us by adding a <dependency-resolution> with eclipse-plugin org.apache.felix.scr to our target-platform-configuration. The workaround with the manually added Require-Capability header works in our environment too, but we don't want to add the header to all of our manifest files.

And we had by the way a similar problem with an optional package import of org.osgi.service.component.annotations, which was not resolved at compile time. Removing the optional attribute fixed this, but we don't want the runtime dependency so we also solved that by adding org.osgi.service.component as a requirement in the <dependency-resolution>.

We can live with these workarounds but maybe there are better solutions to these resolution problems.

**Comment by laeubi** [comment]
> And we had by the way a similar problem with an optional package import of org.osgi.service.component.annotations, which was not resolved at compile time.

The package `org.osgi.service.component.annotations` should simply never be imported at all.

**Comment by laeubi** [comment]
The automatic added header itself can by the way be disabled with that option: https://tycho.eclipseprojects.io/doc/latest/tycho-packaging-plugin/package-plugin-mojo.html#deriveHeaderFromSource

**Comment by mwgmnn** [comment]
> 
> The package `org.osgi.service.component.annotations` should simply never be imported at all.

Yes, but unfortunately the classes need to be present at compile time because the annotations are used in component - classes so that eclipse is able generate the xml files automatically.

**Comment by laeubi** [comment]
> > The package `org.osgi.service.component.annotations` should simply never be imported at all.
> 
> Yes, but unfortunately the classes need to be present at compile time because the annotations are used in component - classes so that eclipse is able generate the xml files automatically.

If you are using quite recent Eclipse/Tycho everything will work automatically.

**Comment by mwgmnn** [comment]
> 
> If you are using quite recent Eclipse/Tycho everything will work automatically.

Indeed, you're right, it's functioning without this package import in the current versions. I didn't know that. Thanks for the info.
