### ISSUE TITLE
Not possible to remove qualifier for release build from bundles/features and product when using CI friendly versions

### ISSUE THREAD

**Issue by jstroleny** [eclipse-tycho/tycho#3887]
I struggle with qualifier a bit and how to get rid of it for release build, as described below in issues.
I'm using maven CI friendly versions in project (revision, changelist and qualifier) from this https://github.com/eclipse-tycho/tycho/commit/b9c5d7304593a05795787a9f072300324bb6c066
and based on related issues https://github.com/eclipse-tycho/tycho/issues/603 / https://github.com/eclipse-tycho/tycho/issues/611
where it was described how to have release build versions using maven CI friendly versions.

I run it with integration test provided in given commit where I just added product (with qualifier as well) and I run it following:
`./mvnw clean install -Dtycho.buildqualifier.format=\'my-snapshot-prefix-\'yyyy -Dchangelist= -Dqualifier= -DskipTests -Dtycho.strictVersions=false`
but result is that maven projects and bundles are build without qualifier correctly and installed in maven repo correctly, but when product build starts (materialize-products / archive-products / etc), it assigns qualifier anyway and it makes inconsistent result from build process from maven CI friendly version point of view. 
Is there some way how to remove qualifier also for product in similar way as it is done for each bundle separately for maven submodules?

I have tried also this:
`./mvnw clean install -Dtycho.buildqualifier.format= -Dchangelist= -Dqualifier= -DskipTests -Dtycho.strictVersions=false`
as I'm really not interested to format build qualifier anyhow for release build, but the build fails at first bundle with:

```
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-packaging-plugin:4.0.8:build-qualifier (default-build-qualifier) on project project.util: Invalid build qualifier '', it does not match the OSGi qualifier constraint ([0..9]|[a..zA..Z]|'_'|'-') -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.eclipse.tycho:tycho-packaging-plugin:4.0.8:build-qualifier (default-build-qualifier) on project project.util: Invalid build qualifier '', it does not match the OSGi qualifier constraint ([0..9]|[a..zA..Z]|'_'|'-')
Caused by: org.apache.maven.plugin.MojoFailureException: Invalid build qualifier '', it does not match the OSGi qualifier constraint ([0..9]|[a..zA..Z]|'_'|'-')
    at org.eclipse.tycho.buildversion.BuildQualifierMojo.validateQualifier (BuildQualifierMojo.java:220)
    at org.eclipse.tycho.buildversion.BuildQualifierMojo.calculateQualifiedVersion (BuildQualifierMojo.java:178)
    at org.eclipse.tycho.buildversion.BuildQualifierMojo.execute (BuildQualifierMojo.java:155)
```
so I looked into code and seems that `validateQualifier` expects that qualifier always have non-empty value, but maven CI friendly versions works with empty qualifier/changelist just fine, as shown in issues and fixes above. Is this just issue in `validateQualifier` method that it does not allow to proceed further with empty qualifier or why it has inconsistent behavior?

I also checked PDE Build and it offers `forceContextQualifier=none` which does exactly what I need to achieve, but tycho ignores this specific value, see https://help.eclipse.org/latest/index.jsp?topic=%2Forg.eclipse.pde.doc.user%2Ftasks%2Fpde_version_qualifiers.htm, if I use `forceContextQualifier=` the exception about invalid qualifier appears again.

**Comment by laeubi** [comment]
Thanks for looking into this, keep in mind that any version without a qualifier is considered *smaller* than any with a qualifier so if you already have published such bundles somewhere your released bundles will not be picked up!

Because of this, in the past the goal was more to only strip of a portion of the version from the *maven artifact version* but retain the qualifier for the *Manifest Version*, but the whole CI-Friendly version story is still something we need to improve.

> Is this just issue in `validateQualifier` method that it does not allow to proceed further with empty qualifier or why it has inconsistent behavior?

I think no one has ever tried this or didn't cared enough to report/fix it :-)

> I also checked PDE Build and it offers forceContextQualifier=none which does exactly what I need to achieve, but tycho ignores this specific value, see https://help.eclipse.org/latest/index.jsp?topic=%2Forg.eclipse.pde.doc.user%2Ftasks%2Fpde_version_qualifiers.htm, if I use forceContextQualifier= the exception about invalid qualifier appears again.

That's interesting, as tycho already supports `forceContextQualifier` we probably should support that case of supply `none` as a value where Tycho simply strip the qualifer off, that looks for me like the most sensible solution.
