### ISSUE TITLE
Comments are not fully ignored in pom.xml.

### ISSUE THREAD

**Issue by ewillink** [eclipse-tycho/tycho#4069]
The following lines in pom.xml

`    <!--executionEnvironment>J2SE-1.5</executionEnvironment>`
`    <source-java-version>1.5</source-java-version>`
`    <target-java-version>${source-java-version}</target-java-version-->`

caused a build to fail with 1.5 no longer supported. Changing to 1.8 within the comments and everything is ok.

**Comment by laeubi** [comment]
Please share a complete (at best executable) example, this snippet shows nothing that is directly relatable to Tycho and behavior obviously depends on the used version of Tycho and other plugins.

**Comment by ewillink** [comment]
It's a simple parser bug. The `<!-- ... -->` gets confused by the internal `< ... >` allowing at least the `<source-java-version>1.5</source-java-version>` to be processed.

**Comment by laeubi** [comment]
The please report this to the [maven project](https://maven.apache.org/), Tycho is not parsing the pom.xml
