### ISSUE TITLE
TODO in RemoteArtifactRepositoryManager.createRepository() can be fixed

### ISSUE THREAD

**Issue by tivervac** [eclipse-tycho/tycho#4162]
The TODO [here](https://github.com/eclipse-tycho/tycho/blob/main/p2-maven-plugin/src/main/java/org/eclipse/tycho/p2maven/transport/RemoteArtifactRepositoryManager.java#L75) can be fixed as [this MR](https://github.com/eclipse-equinox/p2/pull/415) was merged. I don't specifically know what needs to happen. I simply bumped into it while walking through the code.

**Comment by laeubi** [comment]
Good catch do you like to provide a PR for Tycho? Actually the surrounding synchronized should no longer be needed.
