### ISSUE TITLE
tycho-eclipserun still uses jdk17

### ISSUE THREAD

**Issue by Bananeweizen** [eclipse-tycho/tycho#4193]
Shouldn't we lift this to 21 with the recent platform requirements?
https://tycho.eclipseprojects.io/doc/latest/tycho-eclipse-plugin/eclipse-run-mojo.html#executionEnvironment

**Comment by laeubi** [comment]
Tycho is still Java 17, what platform component specifically requires Java 21?

**Comment by Bananeweizen** [comment]
I was trying to find some mailing list issue or similar now, but can't point to anything. Did I confuse that with "projects are allowed to require 21 independent of the platform" maybe?

**Comment by Bananeweizen** [comment]
Found it: https://www.eclipse.org/setups/sponsor/?scope=Eclipse%20IDE&campaign=2024-06 Starting with 2024-06 we need Java 21 to run the SDK, even though the platform still targets 17.
@laeubi I must admit I'm not sure what exactly that means for the tycho-eclipse mojo, you can probably judge that better.

**Comment by laeubi** [comment]
Basically that means that some Eclipse Plugins (e.g. m23, WWD, ..) require Java 21, and all SimRel Projects are in general allowed to use Java 21. But at the moment I'm not aware of any "core" bundle requiring it actually.

For Tycho the plan currently is to stay at Java 17 as long as possible, as soon as any "core" dependency requires a higher version we will upgrade Tycho 5.x to Java 21 (as it is a breaking change anyways).

For Tycho 4 we need to decide (might also depend on the time this happens and how far Tycho 5 line has evolved) if we just keep it at the current dependencies level, or we might make a Tycho 4.1.x line that requires higher Java version.

**Comment by Bananeweizen** [comment]
It's not just about the bundles. The EPP packaging also requires 21: 
![grafik](https://github.com/user-attachments/assets/61703e29-d6b4-45e6-8b4b-3821c9e35832)
As long as the runtime started by tycho-eclipse doesn't contain those, then it should be fine, agreed.

**Comment by merks** [comment]
Yes EPP forces Java 21. The eclipse SDK is happy with 17.  Very few bundles on the train actually require Java 21.  So most likely most folks using tycho can run with 17 currently.

**Comment by Bananeweizen** [comment]
Thanks for all the clarifications. I'll close the issue without changes then.
