### ISSUE TITLE
New Errors showing up in Xtext builds with Tycho 5

### ISSUE THREAD

**Issue by cdietrich** [eclipse-tycho/tycho#4226]
```
1) No implementation for TargetPlatformArtifactResolver was bound.
  while locating TargetPlatformWorkspaceReader
  at ClassRealm[extension>org.eclipse.tycho:tycho-maven-plugin:5.0.0-SNAPSHOT, parent: ClassLoaders$AppClassLoader@2cdf8d8a]
      \_ installed by: WireModule -> PlexusBindingModule
  while locating WorkspaceReader annotated with @Named("TargetPlatformWorkspaceReader")

1 error
```
https://github.com/xtext/xtext-reference-projects/actions/runs/10773540359/job/29873555998

does this ring a bell?

**Comment by cdietrich** [comment]
we use 3.9.1, will check with a newer

**Comment by cdietrich** [comment]
with 3.9.9 it looks better. maybe we need a newer version as 
requireMavenVersion

**Comment by laeubi** [comment]
Yes we need at a lest 3.9.6 as it seems. One problem is that this is only checked once the build runs (and we are using extensions here that are not checked at all).
