### ISSUE TITLE
Site generation is broken

### ISSUE THREAD

**Issue by laeubi** [eclipse-tycho/tycho#4288]
All these are empty now:

- https://tycho.eclipseprojects.io/doc/main/StructuredBuild.html
- https://tycho.eclipseprojects.io/doc/main/BuildProperties.html
- https://tycho.eclipseprojects.io/doc/main/SystemProperties.html
- https://tycho.eclipseprojects.io/doc/main/TychoProperties.html
- https://tycho.eclipseprojects.io/doc/main/TestingBundles.html
- https://tycho.eclipseprojects.io/doc/main/BndBuild.html
- https://tycho.eclipseprojects.io/doc/main/TychoCiFriendly.html

These work:
- https://tycho.eclipseprojects.io/doc/main/PackagingTypes.html
- https://tycho.eclipseprojects.io/doc/main/TargetPlatform.html
- https://tycho.eclipseprojects.io/doc/main/Category.html

**Comment by akurtakov** [comment]
Should be fixed by https://github.com/eclipse-tycho/tycho/pull/4289 but I've not marked it to be autoclosed in order to be expected manually.

**Comment by akurtakov** [comment]
Confirmed fixed.
