### ISSUE TITLE
Tycho doesn't use SmartBuilder

### ISSUE THREAD

**Issue by Bananeweizen** [eclipse-tycho/tycho#4402]
Shouldn't Tycho use the Takari builder when the thread count is larger than 1? I never get the smart builder: 
![image](https://github.com/user-attachments/assets/5cdde88c-75f8-4b77-93af-6e43d2ff253b)

I've been debugging this, and I don't get into TychoGraphBuilder.java at all, where that builder would be configured via session properties. What needs to be done to use TychoGraphBuilder? Be aware I don't use the polyglott stuff, if that's relevant.

**Comment by laeubi** [comment]
> Shouldn't Tycho use the Takari builder when the thread count is larger than 1? I never get the smart builder:

You need to enable `tycho-build` extension as described [here as a first step](https://tycho.eclipseprojects.io/doc/latest/StructuredBuild.html), but you are using project mode according to the log output.

**Comment by Bananeweizen** [comment]
Aaah, that makes sense now. 2 years ago I removed the extensions.xml because I thought that having the `<extension>true</extension>` flag would be sufficient, and then removing the otherwise useless file seamed cleaner.

Thanks @laeubi for the clarification.

**Comment by laeubi** [comment]
There are two kinds of extensions:

- project extensions: that can extend things once projects are loaded, e.g. new packaging types, participate once session is finalized)
- core extension: that can extends almost everything including how projects are read/and or scheduled

of course if you only want to use smart-builder, you can also opt-in to enable it as a standalone extension, but in the light of Maven 4 Tycho will probably move towards requiring `tycho-build` anyways.
