### ISSUE TITLE
Read maven information from META-INF/maven

### ISSUE THREAD

**Issue by laeubi** [eclipse-tycho/tycho#607]
Currently we read the Maven infos from the IU attributes. We could think about reading them from the META-INF/maven location also if not present.

**Comment by mickaelistria** [comment]
That would require to 1st download the artifact before getting Maven coordinates of a p2 bundle. I think it's not too bad though as the Maven coordinates aren't necessary before p2 resolves dependencies (so it wouldn't download useless artifacts early), are they?

**Comment by laeubi** [comment]
At that stage where maven dependencies are injected we already have the artifact downloaded.

**Comment by mickaelistria** [comment]
Perfect!

**Comment by laeubi** [comment]
> Perfect!

What is "not so perfect" is that orbit seems to ship bad meta-data here. But thanks to the Workspace resolver, we *might* just use that info anyways and resolve it to a system-scoped one, if someone complains blame it to the orbit project so they produce good metadata instead?

**Comment by mickaelistria** [comment]
> if someone complains blame it to the orbit project so they produce good metadata instead?

Just driving people towards not using Orbit and using Maven artifacts in p2 builds with Tycho is the best path forward.

**Comment by laeubi** [comment]
The recent added support for resolving maven dependencies in the consumer pom phase seems more valuable than in the injection phase.
