### ISSUE TITLE
Logo/Artwork for Tycho

### ISSUE THREAD

**Issue by laeubi** [eclipse-tycho/tycho#68]
I always wondered if there is a logo image for Tycho?

The [project page](https://projects.eclipse.org/projects/technology.tycho) only shows a default eclipse-icon, also the [Github Readme](https://github.com/eclipse/tycho/blob/master/README.md) do not contain one.

Even though Tycho being a command-line tool I think something that visually represents tycho would be cool (and handy should I ever get the time to work on tycho-eclipse tooling in the future). It might also be nice for people writing articles / blog post about tycho and it would make the overall appearance of the Github-Readme more appealing.

I have seen that sometimes there is an art-contest or something for projects, does anyone knows how to apply for such a thing at eclipse-foundation? I think tycho defiantly deserves one :+1:

**Comment by mickaelistria** [comment]
Tycho currently has no logo.

> I have seen that sometimes there is an art-contest or something for projects, does anyone knows how to apply for such a thing at eclipse-foundation? I think tycho defiantly deserves one +1

Sure, why not. Please contact marketing@eclipse-foundation.org to see what they can suggest as artwork or as process. There used to be some budget available to fund a contest on sites like designonclick.com (that's the last one I used something like 7 or 8 years ago, so maybe it's not the most hype of these days; but I expect Eclipse Marketing team could recommend the best website).

**Comment by laeubi** [comment]
I have contacted EF, lets see what is possible here :+1:

**Comment by laeubi** [comment]
correction... TRIED to...

```
This is a permanent error. The following address(es) failed:

  marketing@eclipse-foundation.org
    host aspmx.l.google.com [74.125.133.26]
    SMTP error from remote mail server after RCPT TO:<marketing@eclipse-foundation.org>:
    550-5.1.1 The email account that you tried to reach does not exist. 
```

**Comment by laeubi** [comment]
@mickaelistria do you know of any alternative contact address?

**Comment by mickaelistria** [comment]
See https://www.eclipse.org/org/foundation/contact.php

**Comment by laeubi** [comment]
I got a response from the emo:

> there is information regarding the project logos in the handbook: https://www.eclipse.org/projects/handbook/#trademarks-project-logo
> In the past we've had some success stories using the 99designs website.

If I understand right the project leader has to (or should?) init the process and get a refund but otherwise free to choose the platform and how the logo is created.

**Comment by laeubi** [comment]
@mickaelistria @akurtakov  could you, as a project lead, initiate the process?

**Comment by laeubi** [comment]
See 
- https://github.com/eclipse-tycho/tycho/discussions/2305
