### ISSUE TITLE
Use DS annotations for tycho components

### ISSUE THREAD

**Issue by laeubi** [eclipse-tycho/tycho#750]
Currently we use hand crafted `component.xml` using DS-Annotations would automate this process and make it much more convenient and clear.

**Comment by akurtakov** [comment]
Would you please ellaborate what should/could be done here?

**Comment by laeubi** [comment]
We currently have for example here some component definitions, hand crafted:

https://github.com/eclipse/tycho/tree/master/tycho-bundles/org.eclipse.tycho.p2.resolver.impl/OSGI-INF

the in code then these methods are (sometimes) marked with `// for DS usage`.

On the other hand one can use DS Annotations with the following advantages:

1. Automatic validation and generation of the XML (e.g. missing methods)
2. One can work "in code" to change something without taking care of the XML
3. The annotations already document that these is used for DS so one don't think they are unused
4. With recent Tycho 2.7.3 you don't even need to check in the XML as they are generated by the build

**Comment by laeubi** [comment]
@akurtakov do you plan to further work on this?

**Comment by akurtakov** [comment]
I hope to find time for it before 3.0

**Comment by laeubi** [comment]
Great let me know if you need any help.

**Comment by kwin** [comment]
@laeubi Is this fixed in Tycho 3.0.0? Is the MANIFEST.MF also extended with the service metadata references?

**Comment by laeubi** [comment]
@kwin this is about Tycho using DS internally (and is somehow obsolete now).

The wiki itself is heavily outdated and mostly would need a complete overhaul. From the user side you can use all the annotations and Tycho will generate the xml, but you will need to add the  service metadata references (or mostly PDE will do this for you if you enable DS annotation processing).
