### ISSUE TITLE
Java 17 compilation fails when running on Java 11 (missing `--system` compiler argument)

### ISSUE THREAD

**Issue by aumann** [eclipse-tycho/tycho#950]
Following the discussion linked below:

My intuition would have been that `BREE`,  Manifest `JavaSE-17` and setting the execution environment in the target platform to `JavaSE-17` is enough. However, as soon as we use actual additions from the 17 runtime library (like `List.toStream()`) the compiler starts complaining. The compile errors vanish as soon as tycho itself runs on a JDK 17.

Maybe my expectations are just wrong? Otherwise, I'd open an issue.

Versions: 2.6.0, 2.7.1 and 2.7.2

I will open a draft pull request containing the test project inside tycho-it

_Originally posted by @aumann in https://github.com/eclipse/tycho/discussions/938_

**Comment by mickaelistria** [comment]
https://github.com/eclipse-tycho/tycho/pull/1351 is expected to fix it, however it's very hard to create an integration test using toolchains, so it's not covered by automated test.
